# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pcoedge_design.ui'
#
# Created: Fri Jan 17 12:44:10 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(770, 718)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDisplay = QtGui.QLabel(Form)
        self.labelDisplay.setGeometry(QtCore.QRect(250, 10, 512, 512))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDisplay.sizePolicy().hasHeightForWidth())
        self.labelDisplay.setSizePolicy(sizePolicy)
        self.labelDisplay.setMinimumSize(QtCore.QSize(512, 512))
        self.labelDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelDisplay.setText(_fromUtf8(""))
        self.labelDisplay.setObjectName(_fromUtf8("labelDisplay"))
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(250, 520, 512, 94))
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Min/Max", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalSlider_min = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_min.setMinimumSize(QtCore.QSize(360, 0))
        self.horizontalSlider_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_min.setObjectName(_fromUtf8("horizontalSlider_min"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.horizontalSlider_min)
        self.label_minSlider = QtGui.QLabel(self.groupBox_5)
        self.label_minSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_minSlider.setText(QtGui.QApplication.translate("Form", "Min: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_minSlider.setObjectName(_fromUtf8("label_minSlider"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_minSlider)
        self.horizontalSlider_max = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_max.setMinimumSize(QtCore.QSize(360, 0))
        self.horizontalSlider_max.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_max.setObjectName(_fromUtf8("horizontalSlider_max"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.horizontalSlider_max)
        self.label_maxSlider = QtGui.QLabel(self.groupBox_5)
        self.label_maxSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_maxSlider.setText(QtGui.QApplication.translate("Form", "Max: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_maxSlider.setObjectName(_fromUtf8("label_maxSlider"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_maxSlider)
        self.checkBoxAutoscale = QtGui.QCheckBox(self.groupBox_5)
        self.checkBoxAutoscale.setText(QtGui.QApplication.translate("Form", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoscale.setChecked(True)
        self.checkBoxAutoscale.setTristate(False)
        self.checkBoxAutoscale.setObjectName(_fromUtf8("checkBoxAutoscale"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBoxAutoscale)
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 231, 101))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Data saving settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lineEdit_fileName = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_fileName.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_fileName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_fileName.setObjectName(_fromUtf8("lineEdit_fileName"))
        self.gridLayout_8.addWidget(self.lineEdit_fileName, 1, 1, 1, 1)
        self.label_fn = QtGui.QLabel(self.groupBox)
        self.label_fn.setText(QtGui.QApplication.translate("Form", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fn.setObjectName(_fromUtf8("label_fn"))
        self.gridLayout_8.addWidget(self.label_fn, 1, 0, 1, 1)
        self.spinBox_fileNameIndex = QtGui.QSpinBox(self.groupBox)
        self.spinBox_fileNameIndex.setObjectName(_fromUtf8("spinBox_fileNameIndex"))
        self.gridLayout_8.addWidget(self.spinBox_fileNameIndex, 1, 2, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox)
        self.label_21.setText(QtGui.QApplication.translate("Form", "Suffix:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 2, 0, 1, 1)
        self.comboBox_filename = QtGui.QComboBox(self.groupBox)
        self.comboBox_filename.setEditable(True)
        self.comboBox_filename.setObjectName(_fromUtf8("comboBox_filename"))
        self.gridLayout_8.addWidget(self.comboBox_filename, 2, 1, 1, 1)
        self.label_currentDir = QtGui.QLabel(self.groupBox)
        self.label_currentDir.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_currentDir.setObjectName(_fromUtf8("label_currentDir"))
        self.gridLayout_8.addWidget(self.label_currentDir, 3, 0, 1, 3)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 110, 231, 121))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Filming", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.pushButton_RecordMemory = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RecordMemory.sizePolicy().hasHeightForWidth())
        self.pushButton_RecordMemory.setSizePolicy(sizePolicy)
        self.pushButton_RecordMemory.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_RecordMemory.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_RecordMemory.setPalette(palette)
        self.pushButton_RecordMemory.setText(QtGui.QApplication.translate("Form", "Record Memory", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_RecordMemory.setObjectName(_fromUtf8("pushButton_RecordMemory"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButton_RecordMemory)
        self.resetPreview_pushButton = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetPreview_pushButton.sizePolicy().hasHeightForWidth())
        self.resetPreview_pushButton.setSizePolicy(sizePolicy)
        self.resetPreview_pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.resetPreview_pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.resetPreview_pushButton.setText(QtGui.QApplication.translate("Form", "Reset Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.resetPreview_pushButton.setObjectName(_fromUtf8("resetPreview_pushButton"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.resetPreview_pushButton)
        self.pushButton_SaveImages = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_SaveImages.sizePolicy().hasHeightForWidth())
        self.pushButton_SaveImages.setSizePolicy(sizePolicy)
        self.pushButton_SaveImages.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_SaveImages.setText(QtGui.QApplication.translate("Form", "Save Images", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SaveImages.setObjectName(_fromUtf8("pushButton_SaveImages"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.FieldRole, self.pushButton_SaveImages)
        self.pushButton_RecordDAX = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_RecordDAX.sizePolicy().hasHeightForWidth())
        self.pushButton_RecordDAX.setSizePolicy(sizePolicy)
        self.pushButton_RecordDAX.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_RecordDAX.setMaximumSize(QtCore.QSize(100, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_RecordDAX.setPalette(palette)
        self.pushButton_RecordDAX.setText(QtGui.QApplication.translate("Form", "Record DAX", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_RecordDAX.setObjectName(_fromUtf8("pushButton_RecordDAX"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButton_RecordDAX)
        self.memToDAX_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.memToDAX_pushButton.setText(QtGui.QApplication.translate("Form", "Memory to DAX", None, QtGui.QApplication.UnicodeUTF8))
        self.memToDAX_pushButton.setObjectName(_fromUtf8("memToDAX_pushButton"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.memToDAX_pushButton)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 310, 232, 256))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settings = QtGui.QWidget()
        self.settings.setEnabled(True)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.verticalLayoutWidget = QtGui.QWidget(self.settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 111, 231))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.settings1_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings1_radioButton.setText(QtGui.QApplication.translate("Form", "settings1", None, QtGui.QApplication.UnicodeUTF8))
        self.settings1_radioButton.setObjectName(_fromUtf8("settings1_radioButton"))
        self.verticalLayout_3.addWidget(self.settings1_radioButton)
        self.settings2_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings2_radioButton.setText(QtGui.QApplication.translate("Form", "settings2", None, QtGui.QApplication.UnicodeUTF8))
        self.settings2_radioButton.setObjectName(_fromUtf8("settings2_radioButton"))
        self.verticalLayout_3.addWidget(self.settings2_radioButton)
        self.settings3_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings3_radioButton.setText(QtGui.QApplication.translate("Form", "settings3", None, QtGui.QApplication.UnicodeUTF8))
        self.settings3_radioButton.setObjectName(_fromUtf8("settings3_radioButton"))
        self.verticalLayout_3.addWidget(self.settings3_radioButton)
        self.settings4_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings4_radioButton.setText(QtGui.QApplication.translate("Form", "settings4", None, QtGui.QApplication.UnicodeUTF8))
        self.settings4_radioButton.setObjectName(_fromUtf8("settings4_radioButton"))
        self.verticalLayout_3.addWidget(self.settings4_radioButton)
        self.settings5_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings5_radioButton.setText(QtGui.QApplication.translate("Form", "settings5", None, QtGui.QApplication.UnicodeUTF8))
        self.settings5_radioButton.setObjectName(_fromUtf8("settings5_radioButton"))
        self.verticalLayout_3.addWidget(self.settings5_radioButton)
        self.settings6_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings6_radioButton.setText(QtGui.QApplication.translate("Form", "settings6", None, QtGui.QApplication.UnicodeUTF8))
        self.settings6_radioButton.setObjectName(_fromUtf8("settings6_radioButton"))
        self.verticalLayout_3.addWidget(self.settings6_radioButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.Timing = QtGui.QWidget()
        self.Timing.setEnabled(True)
        self.Timing.setObjectName(_fromUtf8("Timing"))
        self.gridLayout = QtGui.QGridLayout(self.Timing)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.Timing)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Exposure time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.lineEdit_ExposureTime = QtGui.QLineEdit(self.Timing)
        self.lineEdit_ExposureTime.setObjectName(_fromUtf8("lineEdit_ExposureTime"))
        self.gridLayout.addWidget(self.lineEdit_ExposureTime, 2, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.Timing)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Delay time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.lineEdit_DelayTime = QtGui.QLineEdit(self.Timing)
        self.lineEdit_DelayTime.setObjectName(_fromUtf8("lineEdit_DelayTime"))
        self.gridLayout.addWidget(self.lineEdit_DelayTime, 5, 0, 1, 1)
        self.pushButton_SetTimings = QtGui.QPushButton(self.Timing)
        self.pushButton_SetTimings.setText(QtGui.QApplication.translate("Form", "Set Timings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SetTimings.setObjectName(_fromUtf8("pushButton_SetTimings"))
        self.gridLayout.addWidget(self.pushButton_SetTimings, 7, 0, 1, 1)
        self.comboBox_expunits = QtGui.QComboBox(self.Timing)
        self.comboBox_expunits.setEditable(False)
        self.comboBox_expunits.setMinimumContentsLength(0)
        self.comboBox_expunits.setObjectName(_fromUtf8("comboBox_expunits"))
        self.gridLayout.addWidget(self.comboBox_expunits, 2, 1, 1, 1)
        self.comboBox_delayunits = QtGui.QComboBox(self.Timing)
        self.comboBox_delayunits.setObjectName(_fromUtf8("comboBox_delayunits"))
        self.gridLayout.addWidget(self.comboBox_delayunits, 5, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 3, 0, 1, 1)
        self.labelExposure = QtGui.QLabel(self.Timing)
        self.labelExposure.setText(QtGui.QApplication.translate("Form", "Actual: --", None, QtGui.QApplication.UnicodeUTF8))
        self.labelExposure.setObjectName(_fromUtf8("labelExposure"))
        self.gridLayout.addWidget(self.labelExposure, 3, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 6, 0, 1, 1)
        self.labelDelay = QtGui.QLabel(self.Timing)
        self.labelDelay.setText(QtGui.QApplication.translate("Form", "Actual: --", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDelay.setObjectName(_fromUtf8("labelDelay"))
        self.gridLayout.addWidget(self.labelDelay, 6, 1, 1, 1)
        self.tabWidget.addTab(self.Timing, _fromUtf8(""))
        self.Size = QtGui.QWidget()
        self.Size.setObjectName(_fromUtf8("Size"))
        self.label_16 = QtGui.QLabel(self.Size)
        self.label_16.setGeometry(QtCore.QRect(10, 61, 51, 16))
        self.label_16.setText(QtGui.QApplication.translate("Form", "x0, y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.x0_lineEdit = QtGui.QLineEdit(self.Size)
        self.x0_lineEdit.setGeometry(QtCore.QRect(50, 61, 41, 20))
        self.x0_lineEdit.setObjectName(_fromUtf8("x0_lineEdit"))
        self.y0_lineEdit = QtGui.QLineEdit(self.Size)
        self.y0_lineEdit.setGeometry(QtCore.QRect(100, 61, 41, 20))
        self.y0_lineEdit.setObjectName(_fromUtf8("y0_lineEdit"))
        self.widget = QtGui.QWidget(self.Size)
        self.widget.setGeometry(QtCore.QRect(9, 0, 141, 51))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.widget)
        self.label_8.setText(QtGui.QApplication.translate("Form", "x0: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.x0_label = QtGui.QLabel(self.widget)
        self.x0_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.x0_label.setObjectName(_fromUtf8("x0_label"))
        self.gridLayout_3.addWidget(self.x0_label, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        self.label_10.setText(QtGui.QApplication.translate("Form", "y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.y0_label = QtGui.QLabel(self.widget)
        self.y0_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.y0_label.setObjectName(_fromUtf8("y0_label"))
        self.gridLayout_3.addWidget(self.y0_label, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setText(QtGui.QApplication.translate("Form", "x1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.x1_label = QtGui.QLabel(self.widget)
        self.x1_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.x1_label.setObjectName(_fromUtf8("x1_label"))
        self.gridLayout_3.addWidget(self.x1_label, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        self.label_13.setText(QtGui.QApplication.translate("Form", "y1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 2, 1, 1)
        self.y1_label = QtGui.QLabel(self.widget)
        self.y1_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.y1_label.setObjectName(_fromUtf8("y1_label"))
        self.gridLayout_3.addWidget(self.y1_label, 1, 3, 1, 1)
        self.x1_lineEdit = QtGui.QLineEdit(self.Size)
        self.x1_lineEdit.setGeometry(QtCore.QRect(50, 90, 41, 20))
        self.x1_lineEdit.setObjectName(_fromUtf8("x1_lineEdit"))
        self.label_17 = QtGui.QLabel(self.Size)
        self.label_17.setGeometry(QtCore.QRect(10, 90, 51, 16))
        self.label_17.setText(QtGui.QApplication.translate("Form", "x1, y1:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.y1_lineEdit = QtGui.QLineEdit(self.Size)
        self.y1_lineEdit.setGeometry(QtCore.QRect(100, 90, 41, 20))
        self.y1_lineEdit.setObjectName(_fromUtf8("y1_lineEdit"))
        self.setROI_pushButton = QtGui.QPushButton(self.Size)
        self.setROI_pushButton.setGeometry(QtCore.QRect(160, 60, 51, 51))
        self.setROI_pushButton.setText(QtGui.QApplication.translate("Form", "Set ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.setROI_pushButton.setObjectName(_fromUtf8("setROI_pushButton"))
        self.labelROIDisplay = QtGui.QLabel(self.Size)
        self.labelROIDisplay.setGeometry(QtCore.QRect(10, 120, 201, 111))
        self.labelROIDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelROIDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelROIDisplay.setText(_fromUtf8(""))
        self.labelROIDisplay.setObjectName(_fromUtf8("labelROIDisplay"))
        self.tabWidget.addTab(self.Size, _fromUtf8(""))
        self.Buffer = QtGui.QWidget()
        self.Buffer.setObjectName(_fromUtf8("Buffer"))
        self.label_11 = QtGui.QLabel(self.Buffer)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 131, 16))
        self.label_11.setText(QtGui.QApplication.translate("Form", "Buffer update time (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.updateTime_lineEdit = QtGui.QLineEdit(self.Buffer)
        self.updateTime_lineEdit.setGeometry(QtCore.QRect(140, 10, 61, 20))
        self.updateTime_lineEdit.setObjectName(_fromUtf8("updateTime_lineEdit"))
        self.printRecStruct_pushButton = QtGui.QPushButton(self.Buffer)
        self.printRecStruct_pushButton.setGeometry(QtCore.QRect(10, 140, 201, 23))
        self.printRecStruct_pushButton.setText(QtGui.QApplication.translate("Form", "Print Recording Structure", None, QtGui.QApplication.UnicodeUTF8))
        self.printRecStruct_pushButton.setObjectName(_fromUtf8("printRecStruct_pushButton"))
        self.setRingBuffer_pushButton = QtGui.QPushButton(self.Buffer)
        self.setRingBuffer_pushButton.setGeometry(QtCore.QRect(10, 170, 75, 23))
        self.setRingBuffer_pushButton.setText(QtGui.QApplication.translate("Form", "Ring Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.setRingBuffer_pushButton.setObjectName(_fromUtf8("setRingBuffer_pushButton"))
        self.setSeqBuffer_pushButton = QtGui.QPushButton(self.Buffer)
        self.setSeqBuffer_pushButton.setGeometry(QtCore.QRect(100, 170, 75, 23))
        self.setSeqBuffer_pushButton.setText(QtGui.QApplication.translate("Form", "Seq. Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.setSeqBuffer_pushButton.setObjectName(_fromUtf8("setSeqBuffer_pushButton"))
        self.label_14 = QtGui.QLabel(self.Buffer)
        self.label_14.setGeometry(QtCore.QRect(10, 70, 141, 16))
        self.label_14.setText(QtGui.QApplication.translate("Form", "Number of buffers to queue:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.bufsToQueue_lineEdit = QtGui.QLineEdit(self.Buffer)
        self.bufsToQueue_lineEdit.setGeometry(QtCore.QRect(160, 70, 61, 20))
        self.bufsToQueue_lineEdit.setObjectName(_fromUtf8("bufsToQueue_lineEdit"))
        self.label_20 = QtGui.QLabel(self.Buffer)
        self.label_20.setGeometry(QtCore.QRect(10, 40, 131, 16))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Update display time (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.updateDisplayTime_lineEdit = QtGui.QLineEdit(self.Buffer)
        self.updateDisplayTime_lineEdit.setGeometry(QtCore.QRect(140, 40, 61, 20))
        self.updateDisplayTime_lineEdit.setObjectName(_fromUtf8("updateDisplayTime_lineEdit"))
        self.displayTxtInfo_checkBox = QtGui.QCheckBox(self.Buffer)
        self.displayTxtInfo_checkBox.setGeometry(QtCore.QRect(10, 100, 121, 17))
        self.displayTxtInfo_checkBox.setText(QtGui.QApplication.translate("Form", "Display txt info?", None, QtGui.QApplication.UnicodeUTF8))
        self.displayTxtInfo_checkBox.setChecked(True)
        self.displayTxtInfo_checkBox.setObjectName(_fromUtf8("displayTxtInfo_checkBox"))
        self.tabWidget.addTab(self.Buffer, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_22 = QtGui.QLabel(self.tab)
        self.label_22.setGeometry(QtCore.QRect(5, 20, 181, 20))
        self.label_22.setText(QtGui.QApplication.translate("Form", "Initial number of frames to acquire:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.initFramesMP_lineEdit = QtGui.QLineEdit(self.tab)
        self.initFramesMP_lineEdit.setGeometry(QtCore.QRect(180, 20, 41, 20))
        self.initFramesMP_lineEdit.setObjectName(_fromUtf8("initFramesMP_lineEdit"))
        self.endMP_pushButton = QtGui.QPushButton(self.tab)
        self.endMP_pushButton.setGeometry(QtCore.QRect(10, 50, 75, 23))
        self.endMP_pushButton.setText(QtGui.QApplication.translate("Form", "End MP", None, QtGui.QApplication.UnicodeUTF8))
        self.endMP_pushButton.setObjectName(_fromUtf8("endMP_pushButton"))
        self.stateOfMP_pushButton = QtGui.QPushButton(self.tab)
        self.stateOfMP_pushButton.setGeometry(QtCore.QRect(130, 50, 75, 23))
        self.stateOfMP_pushButton.setText(QtGui.QApplication.translate("Form", "State of MPs", None, QtGui.QApplication.UnicodeUTF8))
        self.stateOfMP_pushButton.setObjectName(_fromUtf8("stateOfMP_pushButton"))
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 90, 191, 131))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Testing MP", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_27 = QtGui.QLabel(self.groupBox_4)
        self.label_27.setText(QtGui.QApplication.translate("Form", "Emit signal after frame:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 0, 0, 1, 1)
        self.emitSigFrame_lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.emitSigFrame_lineEdit.setObjectName(_fromUtf8("emitSigFrame_lineEdit"))
        self.gridLayout_4.addWidget(self.emitSigFrame_lineEdit, 0, 1, 1, 1)
        self.label_28 = QtGui.QLabel(self.groupBox_4)
        self.label_28.setText(QtGui.QApplication.translate("Form", "Capture every:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 1, 0, 1, 1)
        self.captureFrame_lineEdit = QtGui.QLineEdit(self.groupBox_4)
        self.captureFrame_lineEdit.setObjectName(_fromUtf8("captureFrame_lineEdit"))
        self.gridLayout_4.addWidget(self.captureFrame_lineEdit, 1, 1, 1, 1)
        self.setMPTesting_pushButton = QtGui.QPushButton(self.groupBox_4)
        self.setMPTesting_pushButton.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.setMPTesting_pushButton.setObjectName(_fromUtf8("setMPTesting_pushButton"))
        self.gridLayout_4.addWidget(self.setMPTesting_pushButton, 2, 0, 1, 1)
        self.flushImQ_pushButton = QtGui.QPushButton(self.groupBox_4)
        self.flushImQ_pushButton.setText(QtGui.QApplication.translate("Form", "Flush Image Queue", None, QtGui.QApplication.UnicodeUTF8))
        self.flushImQ_pushButton.setObjectName(_fromUtf8("flushImQ_pushButton"))
        self.gridLayout_4.addWidget(self.flushImQ_pushButton, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_23 = QtGui.QLabel(self.tab_2)
        self.label_23.setText(QtGui.QApplication.translate("Form", "Rows:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 0, 0, 1, 1)
        self.subimRows_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.subimRows_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.subimRows_lineEdit.setObjectName(_fromUtf8("subimRows_lineEdit"))
        self.gridLayout_5.addWidget(self.subimRows_lineEdit, 0, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setText(QtGui.QApplication.translate("Form", "Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_5.addWidget(self.label_24, 1, 0, 1, 1)
        self.subimCols_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.subimCols_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.subimCols_lineEdit.setObjectName(_fromUtf8("subimCols_lineEdit"))
        self.gridLayout_5.addWidget(self.subimCols_lineEdit, 1, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.tab_2)
        self.label_25.setText(QtGui.QApplication.translate("Form", "X Shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_5.addWidget(self.label_25, 2, 0, 1, 1)
        self.subimX_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.subimX_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.subimX_lineEdit.setObjectName(_fromUtf8("subimX_lineEdit"))
        self.gridLayout_5.addWidget(self.subimX_lineEdit, 2, 1, 1, 1)
        self.label_26 = QtGui.QLabel(self.tab_2)
        self.label_26.setText(QtGui.QApplication.translate("Form", "Y Shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 3, 0, 1, 1)
        self.subimY_lineEdit = QtGui.QLineEdit(self.tab_2)
        self.subimY_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.subimY_lineEdit.setObjectName(_fromUtf8("subimY_lineEdit"))
        self.gridLayout_5.addWidget(self.subimY_lineEdit, 3, 1, 1, 1)
        self.subimSet_pushButton = QtGui.QPushButton(self.tab_2)
        self.subimSet_pushButton.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.subimSet_pushButton.setObjectName(_fromUtf8("subimSet_pushButton"))
        self.gridLayout_5.addWidget(self.subimSet_pushButton, 4, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 570, 231, 141))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.labelMin = QtGui.QLabel(self.layoutWidget)
        self.labelMin.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMin.setObjectName(_fromUtf8("labelMin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelMin)
        self.label = QtGui.QLabel(self.layoutWidget)
        self.label.setText(QtGui.QApplication.translate("Form", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.labelMax = QtGui.QLabel(self.layoutWidget)
        self.labelMax.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMax.setObjectName(_fromUtf8("labelMax"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelMax)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.labelMean = QtGui.QLabel(self.layoutWidget)
        self.labelMean.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMean.setObjectName(_fromUtf8("labelMean"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelMean)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Median:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.labelMedian = QtGui.QLabel(self.layoutWidget)
        self.labelMedian.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMedian.setObjectName(_fromUtf8("labelMedian"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.labelMedian)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Images: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.labelImagesInRAM = QtGui.QLabel(self.layoutWidget)
        self.labelImagesInRAM.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImagesInRAM.setObjectName(_fromUtf8("labelImagesInRAM"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.labelImagesInRAM)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.labelResolution = QtGui.QLabel(self.layoutWidget)
        self.labelResolution.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelResolution.setObjectName(_fromUtf8("labelResolution"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.labelResolution)
        self.label_19 = QtGui.QLabel(self.layoutWidget)
        self.label_19.setText(QtGui.QApplication.translate("Form", "Pending: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_19)
        self.labelImagesPending = QtGui.QLabel(self.layoutWidget)
        self.labelImagesPending.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImagesPending.setObjectName(_fromUtf8("labelImagesPending"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.labelImagesPending)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 231, 71))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Fast filming", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setText(QtGui.QApplication.translate("Form", "Number of frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 0, 1, 1)
        self.fastImagesToGet_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.fastImagesToGet_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.fastImagesToGet_lineEdit.setObjectName(_fromUtf8("fastImagesToGet_lineEdit"))
        self.gridLayout_2.addWidget(self.fastImagesToGet_lineEdit, 0, 1, 1, 1)
        self.acquireFastImages_pushButton = QtGui.QPushButton(self.groupBox_3)
        self.acquireFastImages_pushButton.setMaximumSize(QtCore.QSize(50, 16777215))
        self.acquireFastImages_pushButton.setText(QtGui.QApplication.translate("Form", "Acquire", None, QtGui.QApplication.UnicodeUTF8))
        self.acquireFastImages_pushButton.setObjectName(_fromUtf8("acquireFastImages_pushButton"))
        self.gridLayout_2.addWidget(self.acquireFastImages_pushButton, 0, 2, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setText(QtGui.QApplication.translate("Form", "Display frame #:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 1, 0, 1, 1)
        self.displayFastImage_lineEdit = QtGui.QLineEdit(self.groupBox_3)
        self.displayFastImage_lineEdit.setObjectName(_fromUtf8("displayFastImage_lineEdit"))
        self.gridLayout_2.addWidget(self.displayFastImage_lineEdit, 1, 1, 1, 1)
        self.graphicsView = ImageView(Form)
        self.graphicsView.setGeometry(QtCore.QRect(260, 610, 501, 101))
        self.graphicsView.setObjectName(_fromUtf8("graphicsView"))

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(4)
        self.comboBox_expunits.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtGui.QApplication.translate("Form", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timing), QtGui.QApplication.translate("Form", "Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Size), QtGui.QApplication.translate("Form", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Buffer), QtGui.QApplication.translate("Form", "Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Multiprocessing", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Subimage", None, QtGui.QApplication.UnicodeUTF8))

from pyqtgraph import ImageView
