# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thorlabsMotors_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(604, 379)
        self.gridLayoutWidget = QtGui.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 59, 283, 131))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_position = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_position.sizePolicy().hasHeightForWidth())
        self.label_position.setSizePolicy(sizePolicy)
        self.label_position.setObjectName(_fromUtf8("label_position"))
        self.gridLayout.addWidget(self.label_position, 0, 1, 1, 1)
        self.lineEdit_stepsize = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_stepsize.setObjectName(_fromUtf8("lineEdit_stepsize"))
        self.gridLayout.addWidget(self.lineEdit_stepsize, 1, 2, 1, 1)
        self.lineEdit_absolute = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_absolute.setObjectName(_fromUtf8("lineEdit_absolute"))
        self.gridLayout.addWidget(self.lineEdit_absolute, 1, 1, 1, 1)
        self.label_stepsize = QtGui.QLabel(self.gridLayoutWidget)
        self.label_stepsize.setObjectName(_fromUtf8("label_stepsize"))
        self.gridLayout.addWidget(self.label_stepsize, 0, 2, 1, 1)
        self.pushButton_stepsize = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stepsize.sizePolicy().hasHeightForWidth())
        self.pushButton_stepsize.setSizePolicy(sizePolicy)
        self.pushButton_stepsize.setObjectName(_fromUtf8("pushButton_stepsize"))
        self.gridLayout.addWidget(self.pushButton_stepsize, 2, 2, 1, 1)
        self.pushButton_absolute = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_absolute.sizePolicy().hasHeightForWidth())
        self.pushButton_absolute.setSizePolicy(sizePolicy)
        self.pushButton_absolute.setObjectName(_fromUtf8("pushButton_absolute"))
        self.gridLayout.addWidget(self.pushButton_absolute, 2, 1, 1, 1)
        self.lineEdit_relative = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_relative.sizePolicy().hasHeightForWidth())
        self.lineEdit_relative.setSizePolicy(sizePolicy)
        self.lineEdit_relative.setObjectName(_fromUtf8("lineEdit_relative"))
        self.gridLayout.addWidget(self.lineEdit_relative, 1, 3, 1, 1)
        self.label_relative = QtGui.QLabel(self.gridLayoutWidget)
        self.label_relative.setObjectName(_fromUtf8("label_relative"))
        self.gridLayout.addWidget(self.label_relative, 0, 3, 1, 1)
        self.pushButton_relative = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_relative.sizePolicy().hasHeightForWidth())
        self.pushButton_relative.setSizePolicy(sizePolicy)
        self.pushButton_relative.setObjectName(_fromUtf8("pushButton_relative"))
        self.gridLayout.addWidget(self.pushButton_relative, 2, 3, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(370, 60, 91, 201))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_up = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_up.sizePolicy().hasHeightForWidth())
        self.pushButton_up.setSizePolicy(sizePolicy)
        self.pushButton_up.setObjectName(_fromUtf8("pushButton_up"))
        self.verticalLayout.addWidget(self.pushButton_up)
        self.pushButton_home = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_home.sizePolicy().hasHeightForWidth())
        self.pushButton_home.setSizePolicy(sizePolicy)
        self.pushButton_home.setObjectName(_fromUtf8("pushButton_home"))
        self.verticalLayout.addWidget(self.pushButton_home)
        self.pushButton_down = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_down.sizePolicy().hasHeightForWidth())
        self.pushButton_down.setSizePolicy(sizePolicy)
        self.pushButton_down.setObjectName(_fromUtf8("pushButton_down"))
        self.verticalLayout.addWidget(self.pushButton_down)
        self.horizontalLayoutWidget = QtGui.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 200, 281, 80))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_BL = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_BL.sizePolicy().hasHeightForWidth())
        self.label_BL.setSizePolicy(sizePolicy)
        self.label_BL.setObjectName(_fromUtf8("label_BL"))
        self.verticalLayout_3.addWidget(self.label_BL)
        self.lineEdit_BL = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_BL.setObjectName(_fromUtf8("lineEdit_BL"))
        self.verticalLayout_3.addWidget(self.lineEdit_BL)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.pushButton_BL = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BL.sizePolicy().hasHeightForWidth())
        self.pushButton_BL.setSizePolicy(sizePolicy)
        self.pushButton_BL.setObjectName(_fromUtf8("pushButton_BL"))
        self.horizontalLayout.addWidget(self.pushButton_BL)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_position.setText(_translate("Dialog", "Absolute", None))
        self.label_stepsize.setText(_translate("Dialog", "Stepsize", None))
        self.pushButton_stepsize.setText(_translate("Dialog", "Stepsize", None))
        self.pushButton_absolute.setText(_translate("Dialog", "Position", None))
        self.label_relative.setText(_translate("Dialog", "Relative", None))
        self.pushButton_relative.setText(_translate("Dialog", "Relative", None))
        self.pushButton_up.setText(_translate("Dialog", "up", None))
        self.pushButton_home.setText(_translate("Dialog", "Home", None))
        self.pushButton_down.setText(_translate("Dialog", "down", None))
        self.label_BL.setText(_translate("Dialog", "Backlash_begin", None))
        self.pushButton_BL.setText(_translate("Dialog", "BL_correct", None))

