# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xySeries_PCIe_design.ui'
#
# Created: Wed Apr 08 11:00:59 2015
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(722, 547)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "SLM", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Geometry", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.checkBoxCalibration = QtGui.QCheckBox(self.groupBox)
        self.checkBoxCalibration.setText(QtGui.QApplication.translate("Form", "Calibration reticle", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxCalibration.setObjectName(_fromUtf8("checkBoxCalibration"))
        self.gridLayout.addWidget(self.checkBoxCalibration, 5, 1, 1, 2)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("Form", "Center x:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.doubleSpinBoxCx = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxCx.setDecimals(1)
        self.doubleSpinBoxCx.setMaximum(511.0)
        self.doubleSpinBoxCx.setProperty("value", 255.5)
        self.doubleSpinBoxCx.setObjectName(_fromUtf8("doubleSpinBoxCx"))
        self.gridLayout.addWidget(self.doubleSpinBoxCx, 0, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Diameter:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.doubleSpinBoxDiameter = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxDiameter.setDecimals(1)
        self.doubleSpinBoxDiameter.setMaximum(511.0)
        self.doubleSpinBoxDiameter.setProperty("value", 421.0)
        self.doubleSpinBoxDiameter.setObjectName(_fromUtf8("doubleSpinBoxDiameter"))
        self.gridLayout.addWidget(self.doubleSpinBoxDiameter, 2, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Center y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 1, 1, 1)
        self.doubleSpinBoxCy = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxCy.setDecimals(1)
        self.doubleSpinBoxCy.setMaximum(511.0)
        self.doubleSpinBoxCy.setProperty("value", 250.5)
        self.doubleSpinBoxCy.setObjectName(_fromUtf8("doubleSpinBoxCy"))
        self.gridLayout.addWidget(self.doubleSpinBoxCy, 1, 2, 1, 1)
        self.doubleSpinBoxCSTilt = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxCSTilt.setMinimum(-90.0)
        self.doubleSpinBoxCSTilt.setMaximum(90.0)
        self.doubleSpinBoxCSTilt.setSingleStep(0.01)
        self.doubleSpinBoxCSTilt.setObjectName(_fromUtf8("doubleSpinBoxCSTilt"))
        self.gridLayout.addWidget(self.doubleSpinBoxCSTilt, 3, 2, 1, 1)
        self.doubleSpinBoxCSTiltDir = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxCSTiltDir.setMaximum(360.0)
        self.doubleSpinBoxCSTiltDir.setObjectName(_fromUtf8("doubleSpinBoxCSTiltDir"))
        self.gridLayout.addWidget(self.doubleSpinBoxCSTiltDir, 4, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setText(QtGui.QApplication.translate("Form", "Coverslip tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout.addWidget(self.label_12, 3, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setText(QtGui.QApplication.translate("Form", "CS tilt direction", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBoxSli4Pi = QtGui.QGroupBox(Form)
        self.groupBoxSli4Pi.setEnabled(True)
        self.groupBoxSli4Pi.setTitle(QtGui.QApplication.translate("Form", "Single lens 4Pi", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxSli4Pi.setCheckable(True)
        self.groupBoxSli4Pi.setChecked(False)
        self.groupBoxSli4Pi.setObjectName(_fromUtf8("groupBoxSli4Pi"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBoxSli4Pi)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_5 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_5.setEnabled(True)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Wavelength:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_9.setEnabled(True)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Focal length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 4, 0, 1, 1)
        self.doubleSpinBoxDMF = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxDMF.setEnabled(True)
        self.doubleSpinBoxDMF.setMinimum(-10.0)
        self.doubleSpinBoxDMF.setMaximum(10.0)
        self.doubleSpinBoxDMF.setObjectName(_fromUtf8("doubleSpinBoxDMF"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxDMF, 6, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_11.setEnabled(True)
        self.label_11.setText(QtGui.QApplication.translate("Form", "d(focus,mirror):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 6, 0, 1, 1)
        self.doubleSpinBoxZ0 = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxZ0.setEnabled(True)
        self.doubleSpinBoxZ0.setMinimum(-20.0)
        self.doubleSpinBoxZ0.setMaximum(20.0)
        self.doubleSpinBoxZ0.setProperty("value", 2.0)
        self.doubleSpinBoxZ0.setObjectName(_fromUtf8("doubleSpinBoxZ0"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxZ0, 5, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_10.setEnabled(True)
        self.label_10.setText(QtGui.QApplication.translate("Form", "d(molecule,mirror):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 5, 0, 1, 1)
        self.doubleSpinBoxFocalLength = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxFocalLength.setEnabled(True)
        self.doubleSpinBoxFocalLength.setMinimum(500.0)
        self.doubleSpinBoxFocalLength.setMaximum(5000.0)
        self.doubleSpinBoxFocalLength.setProperty("value", 3333.33)
        self.doubleSpinBoxFocalLength.setObjectName(_fromUtf8("doubleSpinBoxFocalLength"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxFocalLength, 4, 2, 1, 1)
        self.doubleSpinBoxNA = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxNA.setEnabled(True)
        self.doubleSpinBoxNA.setMinimum(0.1)
        self.doubleSpinBoxNA.setMaximum(2.0)
        self.doubleSpinBoxNA.setSingleStep(0.1)
        self.doubleSpinBoxNA.setProperty("value", 1.27)
        self.doubleSpinBoxNA.setObjectName(_fromUtf8("doubleSpinBoxNA"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxNA, 3, 2, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_8.setEnabled(True)
        self.label_8.setText(QtGui.QApplication.translate("Form", "Numerical aperture:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 3, 0, 1, 1)
        self.doubleSpinBoxRefractiveIndex = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxRefractiveIndex.setEnabled(True)
        self.doubleSpinBoxRefractiveIndex.setMinimum(1.0)
        self.doubleSpinBoxRefractiveIndex.setMaximum(2.0)
        self.doubleSpinBoxRefractiveIndex.setSingleStep(0.1)
        self.doubleSpinBoxRefractiveIndex.setProperty("value", 1.33)
        self.doubleSpinBoxRefractiveIndex.setObjectName(_fromUtf8("doubleSpinBoxRefractiveIndex"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxRefractiveIndex, 2, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_7.setEnabled(True)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Refractive index:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.doubleSpinBoxWavelength = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxWavelength.setEnabled(True)
        self.doubleSpinBoxWavelength.setMinimum(0.2)
        self.doubleSpinBoxWavelength.setMaximum(0.9)
        self.doubleSpinBoxWavelength.setSingleStep(0.1)
        self.doubleSpinBoxWavelength.setProperty("value", 0.68)
        self.doubleSpinBoxWavelength.setObjectName(_fromUtf8("doubleSpinBoxWavelength"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxWavelength, 1, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_4.setEnabled(True)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Mirror V Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_5.addWidget(self.label_4, 7, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBoxSli4Pi)
        self.label_6.setEnabled(True)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Mirror H Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 8, 0, 1, 1)
        self.doubleSpinBoxMirrorVTilt = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxMirrorVTilt.setEnabled(True)
        self.doubleSpinBoxMirrorVTilt.setMinimum(-99.99)
        self.doubleSpinBoxMirrorVTilt.setObjectName(_fromUtf8("doubleSpinBoxMirrorVTilt"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxMirrorVTilt, 7, 2, 1, 1)
        self.doubleSpinBoxMirrorHTilt = QtGui.QDoubleSpinBox(self.groupBoxSli4Pi)
        self.doubleSpinBoxMirrorHTilt.setEnabled(True)
        self.doubleSpinBoxMirrorHTilt.setMinimum(-99.99)
        self.doubleSpinBoxMirrorHTilt.setObjectName(_fromUtf8("doubleSpinBoxMirrorHTilt"))
        self.gridLayout_5.addWidget(self.doubleSpinBoxMirrorHTilt, 8, 2, 1, 1)
        self.labelMirrorCorrection = QtGui.QLabel(self.groupBoxSli4Pi)
        self.labelMirrorCorrection.setEnabled(True)
        self.labelMirrorCorrection.setAcceptDrops(True)
        self.labelMirrorCorrection.setText(QtGui.QApplication.translate("Form", "- drop file -", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMirrorCorrection.setObjectName(_fromUtf8("labelMirrorCorrection"))
        self.gridLayout_5.addWidget(self.labelMirrorCorrection, 9, 2, 1, 1)
        self.checkBoxMirrorCorrection = QtGui.QCheckBox(self.groupBoxSli4Pi)
        self.checkBoxMirrorCorrection.setEnabled(True)
        self.checkBoxMirrorCorrection.setText(QtGui.QApplication.translate("Form", "Mirror correction", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMirrorCorrection.setObjectName(_fromUtf8("checkBoxMirrorCorrection"))
        self.gridLayout_5.addWidget(self.checkBoxMirrorCorrection, 9, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBoxSli4Pi)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.groupBoxZernike = QtGui.QGroupBox(Form)
        self.groupBoxZernike.setTitle(QtGui.QApplication.translate("Form", "Zernike set", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxZernike.setCheckable(True)
        self.groupBoxZernike.setObjectName(_fromUtf8("groupBoxZernike"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBoxZernike)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.checkBoxHTilt = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxHTilt.setText(QtGui.QApplication.translate("Form", "H Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxHTilt.setObjectName(_fromUtf8("checkBoxHTilt"))
        self.gridLayout_3.addWidget(self.checkBoxHTilt, 1, 1, 1, 1)
        self.checkBoxDefocus = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxDefocus.setText(QtGui.QApplication.translate("Form", "Defocus", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxDefocus.setObjectName(_fromUtf8("checkBoxDefocus"))
        self.gridLayout_3.addWidget(self.checkBoxDefocus, 3, 1, 1, 1)
        self.checkBox0Astigmatism = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBox0Astigmatism.setText(QtGui.QApplication.translate("Form", "0° Astigmatism", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox0Astigmatism.setObjectName(_fromUtf8("checkBox0Astigmatism"))
        self.gridLayout_3.addWidget(self.checkBox0Astigmatism, 5, 1, 1, 1)
        self.checkBoxHComa = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxHComa.setText(QtGui.QApplication.translate("Form", "H Coma", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxHComa.setObjectName(_fromUtf8("checkBoxHComa"))
        self.gridLayout_3.addWidget(self.checkBoxHComa, 7, 1, 1, 1)
        self.checkBox3rdSpherical = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBox3rdSpherical.setText(QtGui.QApplication.translate("Form", "3rd Spherical", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox3rdSpherical.setObjectName(_fromUtf8("checkBox3rdSpherical"))
        self.gridLayout_3.addWidget(self.checkBox3rdSpherical, 9, 1, 1, 1)
        self.doubleSpinBoxHTilt = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxHTilt.setMinimum(-100.0)
        self.doubleSpinBoxHTilt.setSingleStep(0.05)
        self.doubleSpinBoxHTilt.setObjectName(_fromUtf8("doubleSpinBoxHTilt"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxHTilt, 1, 2, 1, 1)
        self.doubleSpinBoxDefocus = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxDefocus.setMinimum(-100.0)
        self.doubleSpinBoxDefocus.setSingleStep(0.05)
        self.doubleSpinBoxDefocus.setObjectName(_fromUtf8("doubleSpinBoxDefocus"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxDefocus, 3, 2, 1, 1)
        self.doubleSpinBox0Astigmatism = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBox0Astigmatism.setMinimum(-100.0)
        self.doubleSpinBox0Astigmatism.setSingleStep(0.05)
        self.doubleSpinBox0Astigmatism.setObjectName(_fromUtf8("doubleSpinBox0Astigmatism"))
        self.gridLayout_3.addWidget(self.doubleSpinBox0Astigmatism, 5, 2, 1, 1)
        self.doubleSpinBoxHComa = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxHComa.setMinimum(-100.0)
        self.doubleSpinBoxHComa.setSingleStep(0.05)
        self.doubleSpinBoxHComa.setObjectName(_fromUtf8("doubleSpinBoxHComa"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxHComa, 7, 2, 1, 1)
        self.doubleSpinBox3rdSpherical = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBox3rdSpherical.setMinimum(-100.0)
        self.doubleSpinBox3rdSpherical.setSingleStep(0.05)
        self.doubleSpinBox3rdSpherical.setObjectName(_fromUtf8("doubleSpinBox3rdSpherical"))
        self.gridLayout_3.addWidget(self.doubleSpinBox3rdSpherical, 9, 2, 1, 1)
        self.checkBoxMore = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxMore.setText(QtGui.QApplication.translate("Form", "More:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxMore.setObjectName(_fromUtf8("checkBoxMore"))
        self.gridLayout_3.addWidget(self.checkBoxMore, 16, 1, 1, 1)
        self.lineEditMore = QtGui.QLineEdit(self.groupBoxZernike)
        self.lineEditMore.setObjectName(_fromUtf8("lineEditMore"))
        self.gridLayout_3.addWidget(self.lineEditMore, 18, 1, 1, 2)
        self.checkBox45Astigmatism = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBox45Astigmatism.setText(QtGui.QApplication.translate("Form", "45° Astigmatism", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox45Astigmatism.setObjectName(_fromUtf8("checkBox45Astigmatism"))
        self.gridLayout_3.addWidget(self.checkBox45Astigmatism, 4, 1, 1, 1)
        self.doubleSpinBox45Astigmatism = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBox45Astigmatism.setMinimum(-100.0)
        self.doubleSpinBox45Astigmatism.setSingleStep(0.05)
        self.doubleSpinBox45Astigmatism.setObjectName(_fromUtf8("doubleSpinBox45Astigmatism"))
        self.gridLayout_3.addWidget(self.doubleSpinBox45Astigmatism, 4, 2, 1, 1)
        self.checkBoxVComa = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxVComa.setText(QtGui.QApplication.translate("Form", "V Coma", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxVComa.setObjectName(_fromUtf8("checkBoxVComa"))
        self.gridLayout_3.addWidget(self.checkBoxVComa, 6, 1, 1, 1)
        self.doubleSpinBoxVComa = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxVComa.setMinimum(-100.0)
        self.doubleSpinBoxVComa.setSingleStep(0.05)
        self.doubleSpinBoxVComa.setObjectName(_fromUtf8("doubleSpinBoxVComa"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxVComa, 6, 2, 1, 1)
        self.checkBoxVTilt = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxVTilt.setText(QtGui.QApplication.translate("Form", "V Tilt", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxVTilt.setObjectName(_fromUtf8("checkBoxVTilt"))
        self.gridLayout_3.addWidget(self.checkBoxVTilt, 0, 1, 1, 1)
        self.doubleSpinBoxVTilt = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxVTilt.setMinimum(-100.0)
        self.doubleSpinBoxVTilt.setSingleStep(0.05)
        self.doubleSpinBoxVTilt.setObjectName(_fromUtf8("doubleSpinBoxVTilt"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxVTilt, 0, 2, 1, 1)
        self.checkBoxTreX = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxTreX.setText(QtGui.QApplication.translate("Form", "Trefoil X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTreX.setObjectName(_fromUtf8("checkBoxTreX"))
        self.gridLayout_3.addWidget(self.checkBoxTreX, 10, 1, 1, 1)
        self.checkBoxTreY = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxTreY.setText(QtGui.QApplication.translate("Form", "Trefoil Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTreY.setObjectName(_fromUtf8("checkBoxTreY"))
        self.gridLayout_3.addWidget(self.checkBoxTreY, 11, 1, 1, 1)
        self.checkBoxTetX = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxTetX.setText(QtGui.QApplication.translate("Form", "Tetrafoil X", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTetX.setObjectName(_fromUtf8("checkBoxTetX"))
        self.gridLayout_3.addWidget(self.checkBoxTetX, 12, 1, 1, 1)
        self.checkBoxTetY = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBoxTetY.setText(QtGui.QApplication.translate("Form", "Tetrafoil Y", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxTetY.setObjectName(_fromUtf8("checkBoxTetY"))
        self.gridLayout_3.addWidget(self.checkBoxTetY, 13, 1, 1, 1)
        self.checkBox45Ast2 = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBox45Ast2.setText(QtGui.QApplication.translate("Form", "45° Astigmatism 2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox45Ast2.setObjectName(_fromUtf8("checkBox45Ast2"))
        self.gridLayout_3.addWidget(self.checkBox45Ast2, 14, 1, 1, 1)
        self.checkBox0Ast2 = QtGui.QCheckBox(self.groupBoxZernike)
        self.checkBox0Ast2.setText(QtGui.QApplication.translate("Form", "0° Astigmatism 2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox0Ast2.setObjectName(_fromUtf8("checkBox0Ast2"))
        self.gridLayout_3.addWidget(self.checkBox0Ast2, 15, 1, 1, 1)
        self.doubleSpinBoxTreX = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxTreX.setMinimum(-99.0)
        self.doubleSpinBoxTreX.setSingleStep(0.05)
        self.doubleSpinBoxTreX.setObjectName(_fromUtf8("doubleSpinBoxTreX"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxTreX, 10, 2, 1, 1)
        self.doubleSpinBoxTreY = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxTreY.setMinimum(-99.0)
        self.doubleSpinBoxTreY.setSingleStep(0.05)
        self.doubleSpinBoxTreY.setObjectName(_fromUtf8("doubleSpinBoxTreY"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxTreY, 11, 2, 1, 1)
        self.doubleSpinBoxTetX = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxTetX.setMinimum(-99.0)
        self.doubleSpinBoxTetX.setSingleStep(0.05)
        self.doubleSpinBoxTetX.setObjectName(_fromUtf8("doubleSpinBoxTetX"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxTetX, 12, 2, 1, 1)
        self.doubleSpinBoxTetY = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxTetY.setMinimum(-99.0)
        self.doubleSpinBoxTetY.setSingleStep(0.05)
        self.doubleSpinBoxTetY.setObjectName(_fromUtf8("doubleSpinBoxTetY"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxTetY, 13, 2, 1, 1)
        self.doubleSpinBoxAst452 = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxAst452.setMinimum(-99.0)
        self.doubleSpinBoxAst452.setSingleStep(0.05)
        self.doubleSpinBoxAst452.setObjectName(_fromUtf8("doubleSpinBoxAst452"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxAst452, 14, 2, 1, 1)
        self.doubleSpinBoxAst02 = QtGui.QDoubleSpinBox(self.groupBoxZernike)
        self.doubleSpinBoxAst02.setMinimum(-99.0)
        self.doubleSpinBoxAst02.setSingleStep(0.05)
        self.doubleSpinBoxAst02.setObjectName(_fromUtf8("doubleSpinBoxAst02"))
        self.gridLayout_3.addWidget(self.doubleSpinBoxAst02, 15, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.groupBoxZernike)
        self.groupBoxFromFile = QtGui.QGroupBox(Form)
        self.groupBoxFromFile.setMinimumSize(QtCore.QSize(170, 0))
        self.groupBoxFromFile.setAcceptDrops(True)
        self.groupBoxFromFile.setTitle(QtGui.QApplication.translate("Form", "From file", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxFromFile.setCheckable(True)
        self.groupBoxFromFile.setObjectName(_fromUtf8("groupBoxFromFile"))
        self.verticalLayoutFromFile = QtGui.QVBoxLayout(self.groupBoxFromFile)
        self.verticalLayoutFromFile.setObjectName(_fromUtf8("verticalLayoutFromFile"))
        self.labelDropFile = QtGui.QLabel(self.groupBoxFromFile)
        self.labelDropFile.setAcceptDrops(False)
        self.labelDropFile.setText(QtGui.QApplication.translate("Form", "- drop files here -", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDropFile.setObjectName(_fromUtf8("labelDropFile"))
        self.verticalLayoutFromFile.addWidget(self.labelDropFile)
        self.verticalLayout_5.addWidget(self.groupBoxFromFile)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(Form)
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.labelDisplay = QtGui.QLabel(self.groupBox_5)
        self.labelDisplay.setMinimumSize(QtCore.QSize(256, 256))
        self.labelDisplay.setMaximumSize(QtCore.QSize(256, 256))
        self.labelDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelDisplay.setText(_fromUtf8(""))
        self.labelDisplay.setObjectName(_fromUtf8("labelDisplay"))
        self.gridLayout_2.addWidget(self.labelDisplay, 0, 0, 1, 3)
        self.checkBoxModulate = QtGui.QCheckBox(self.groupBox_5)
        self.checkBoxModulate.setText(QtGui.QApplication.translate("Form", "Modulate", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxModulate.setChecked(True)
        self.checkBoxModulate.setObjectName(_fromUtf8("checkBoxModulate"))
        self.gridLayout_2.addWidget(self.checkBoxModulate, 1, 0, 1, 1)
        self.pushButtonSave = QtGui.QPushButton(self.groupBox_5)
        self.pushButtonSave.setText(QtGui.QApplication.translate("Form", "Save to file", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonSave.setObjectName(_fromUtf8("pushButtonSave"))
        self.gridLayout_2.addWidget(self.pushButtonSave, 1, 2, 1, 1)
        self.pushButton_invert = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_invert.setText(QtGui.QApplication.translate("Form", "Invert", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_invert.setObjectName(_fromUtf8("pushButton_invert"))
        self.gridLayout_2.addWidget(self.pushButton_invert, 2, 0, 1, 1)
        self.pushButton_flipud = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_flipud.setText(QtGui.QApplication.translate("Form", "Flip Up-Down", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_flipud.setObjectName(_fromUtf8("pushButton_flipud"))
        self.gridLayout_2.addWidget(self.pushButton_flipud, 3, 0, 1, 1)
        self.pushButton_fliplr = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_fliplr.setText(QtGui.QApplication.translate("Form", "Flip Left-Right", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_fliplr.setObjectName(_fromUtf8("pushButton_fliplr"))
        self.gridLayout_2.addWidget(self.pushButton_fliplr, 4, 0, 1, 1)
        self.pushButton_rot90 = QtGui.QPushButton(self.groupBox_5)
        self.pushButton_rot90.setText(QtGui.QApplication.translate("Form", "Rotate 90", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_rot90.setObjectName(_fromUtf8("pushButton_rot90"))
        self.gridLayout_2.addWidget(self.pushButton_rot90, 5, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_5)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Adjust SLM Modulation\'s Position", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.pushButton_left = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_left.setGeometry(QtCore.QRect(90, 40, 31, 23))
        self.pushButton_left.setText(QtGui.QApplication.translate("Form", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_left.setObjectName(_fromUtf8("pushButton_left"))
        self.pushButton_right = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_right.setGeometry(QtCore.QRect(150, 40, 31, 23))
        self.pushButton_right.setText(QtGui.QApplication.translate("Form", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_right.setObjectName(_fromUtf8("pushButton_right"))
        self.pushButton_up = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_up.setGeometry(QtCore.QRect(120, 20, 31, 23))
        self.pushButton_up.setText(QtGui.QApplication.translate("Form", "/\\", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_up.setObjectName(_fromUtf8("pushButton_up"))
        self.pushButton_down = QtGui.QPushButton(self.groupBox_2)
        self.pushButton_down.setGeometry(QtCore.QRect(120, 60, 31, 23))
        self.pushButton_down.setText(QtGui.QApplication.translate("Form", "\\/", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_down.setObjectName(_fromUtf8("pushButton_down"))
        self.gridLayout_2.addWidget(self.groupBox_2, 6, 0, 1, 3)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

