# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccd_design.ui'
#
# Created: Sat Mar 09 16:18:14 2013
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(733, 585)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7 = QtGui.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 10, 201, 241))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Form", "Camera Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setText(QtGui.QApplication.translate("Form", "Exposure Time (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        self.exposuretime_lineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.exposuretime_lineEdit.setText(QtGui.QApplication.translate("Form", "0.01", None, QtGui.QApplication.UnicodeUTF8))
        self.exposuretime_lineEdit.setObjectName(_fromUtf8("exposuretime_lineEdit"))
        self.gridLayout_4.addWidget(self.exposuretime_lineEdit, 6, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_22 = QtGui.QLabel(self.groupBox_7)
        self.label_22.setText(QtGui.QApplication.translate("Form", "x,y shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_5.addWidget(self.label_22, 2, 0, 1, 1)
        self.lineEdit_yshape = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_yshape.setText(QtGui.QApplication.translate("Form", "768", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_yshape.setObjectName(_fromUtf8("lineEdit_yshape"))
        self.gridLayout_5.addWidget(self.lineEdit_yshape, 2, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setText(QtGui.QApplication.translate("Form", "x_0, y_0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 3, 0, 1, 1)
        self.lineEdit_y0 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_y0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_y0.setObjectName(_fromUtf8("lineEdit_y0"))
        self.gridLayout_5.addWidget(self.lineEdit_y0, 3, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.lineEdit_xshape = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_xshape.setText(QtGui.QApplication.translate("Form", "768", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_xshape.setObjectName(_fromUtf8("lineEdit_xshape"))
        self.gridLayout_5.addWidget(self.lineEdit_xshape, 2, 1, 1, 1)
        self.lineEdit_x0 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_x0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_x0.setObjectName(_fromUtf8("lineEdit_x0"))
        self.gridLayout_5.addWidget(self.lineEdit_x0, 3, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 2, 0, 1, 2)
        self.pushButton_preview = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_preview.setText(QtGui.QApplication.translate("Form", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_preview.setObjectName(_fromUtf8("pushButton_preview"))
        self.gridLayout_4.addWidget(self.pushButton_preview, 4, 0, 1, 2)
        self.checkBox_autoscale = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_autoscale.setText(QtGui.QApplication.translate("Form", "Autoscale", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_autoscale.setObjectName(_fromUtf8("checkBox_autoscale"))
        self.gridLayout_4.addWidget(self.checkBox_autoscale, 0, 0, 1, 1)
        self.checkBox_showTarget = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_showTarget.setText(QtGui.QApplication.translate("Form", "Show target", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_showTarget.setObjectName(_fromUtf8("checkBox_showTarget"))
        self.gridLayout_4.addWidget(self.checkBox_showTarget, 1, 0, 1, 1)
        self.pushButton_setROI = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_setROI.setText(QtGui.QApplication.translate("Form", "Set ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setROI.setObjectName(_fromUtf8("pushButton_setROI"))
        self.gridLayout_4.addWidget(self.pushButton_setROI, 3, 0, 1, 2)
        self.labelDisplay = QtGui.QLabel(Form)
        self.labelDisplay.setGeometry(QtCore.QRect(210, 10, 512, 512))
        self.labelDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelDisplay.setText(_fromUtf8(""))
        self.labelDisplay.setObjectName(_fromUtf8("labelDisplay"))
        self.label_xy = QtGui.QLabel(Form)
        self.label_xy.setGeometry(QtCore.QRect(210, 530, 131, 16))
        self.label_xy.setText(QtGui.QApplication.translate("Form", "x,y: -,-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_xy.setObjectName(_fromUtf8("label_xy"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 250, 201, 171))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Save Image", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_fn = QtGui.QLabel(self.groupBox)
        self.label_fn.setText(QtGui.QApplication.translate("Form", "Filename: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fn.setObjectName(_fromUtf8("label_fn"))
        self.gridLayout.addWidget(self.label_fn, 0, 0, 1, 1)
        self.lineEdit_fileName = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_fileName.setObjectName(_fromUtf8("lineEdit_fileName"))
        self.gridLayout.addWidget(self.lineEdit_fileName, 0, 1, 1, 1)
        self.pushButton_saveImage = QtGui.QPushButton(self.groupBox)
        self.pushButton_saveImage.setText(QtGui.QApplication.translate("Form", "Save Image", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_saveImage.setObjectName(_fromUtf8("pushButton_saveImage"))
        self.gridLayout.addWidget(self.pushButton_saveImage, 1, 1, 1, 1)
        self.spinBox_fileNameIndex = QtGui.QSpinBox(self.groupBox)
        self.spinBox_fileNameIndex.setObjectName(_fromUtf8("spinBox_fileNameIndex"))
        self.gridLayout.addWidget(self.spinBox_fileNameIndex, 0, 2, 1, 1)
        self.pushButton_recordMovie = QtGui.QPushButton(self.groupBox)
        self.pushButton_recordMovie.setText(QtGui.QApplication.translate("Form", "Record Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_recordMovie.setObjectName(_fromUtf8("pushButton_recordMovie"))
        self.gridLayout.addWidget(self.pushButton_recordMovie, 3, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Disk time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.lineEdit_toDiskTime = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_toDiskTime.setObjectName(_fromUtf8("lineEdit_toDiskTime"))
        self.gridLayout.addWidget(self.lineEdit_toDiskTime, 2, 1, 1, 1)
        self.pushButton_stopRecord = QtGui.QPushButton(self.groupBox)
        self.pushButton_stopRecord.setText(QtGui.QApplication.translate("Form", "Stop Movie", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stopRecord.setObjectName(_fromUtf8("pushButton_stopRecord"))
        self.gridLayout.addWidget(self.pushButton_stopRecord, 4, 1, 1, 1)
        self.widget = QtGui.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 430, 201, 101))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.formLayout = QtGui.QFormLayout(self.widget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.widget)
        self.label.setText(QtGui.QApplication.translate("Form", "Min: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.labelMin = QtGui.QLabel(self.widget)
        self.labelMin.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMin.setObjectName(_fromUtf8("labelMin"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.labelMin)
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.labelMax = QtGui.QLabel(self.widget)
        self.labelMax.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMax.setObjectName(_fromUtf8("labelMax"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelMax)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Mean: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.labelMean = QtGui.QLabel(self.widget)
        self.labelMean.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMean.setObjectName(_fromUtf8("labelMean"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelMean)
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Median: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.labelMedian = QtGui.QLabel(self.widget)
        self.labelMedian.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMedian.setObjectName(_fromUtf8("labelMedian"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelMedian)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Ims Recorded: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_5)
        self.label_nImsRec = QtGui.QLabel(self.widget)
        self.label_nImsRec.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_nImsRec.setObjectName(_fromUtf8("label_nImsRec"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.label_nImsRec)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.lineEdit_xshape, self.lineEdit_yshape)
        Form.setTabOrder(self.lineEdit_yshape, self.lineEdit_x0)
        Form.setTabOrder(self.lineEdit_x0, self.lineEdit_y0)
        Form.setTabOrder(self.lineEdit_y0, self.pushButton_preview)
        Form.setTabOrder(self.pushButton_preview, self.exposuretime_lineEdit)

    def retranslateUi(self, Form):
        pass

