# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pump_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(522, 355)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 151, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_settings = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_settings.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_settings.setObjectName("verticalLayout_settings")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_settings.addWidget(self.label)
        self.comboBox_dia = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_dia.sizePolicy().hasHeightForWidth())
        self.comboBox_dia.setSizePolicy(sizePolicy)
        self.comboBox_dia.setObjectName("comboBox_dia")
        self.comboBox_dia.addItem("")
        self.comboBox_dia.addItem("")
        self.comboBox_dia.addItem("")
        self.comboBox_dia.addItem("")
        self.verticalLayout_settings.addWidget(self.comboBox_dia)
        self.label_direction = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_direction.setObjectName("label_direction")
        self.verticalLayout_settings.addWidget(self.label_direction)
        self.comboBox_drt = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_drt.setObjectName("comboBox_drt")
        self.comboBox_drt.addItem("")
        self.comboBox_drt.addItem("")
        self.verticalLayout_settings.addWidget(self.comboBox_drt)
        self.label_flrate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_flrate.setObjectName("label_flrate")
        self.verticalLayout_settings.addWidget(self.label_flrate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_rat = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_rat.setObjectName("lineEdit_rat")
        self.horizontalLayout_2.addWidget(self.lineEdit_rat)
        self.comboBox_rat = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_rat.setObjectName("comboBox_rat")
        self.comboBox_rat.addItem("")
        self.comboBox_rat.addItem("")
        self.comboBox_rat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_rat)
        self.verticalLayout_settings.addLayout(self.horizontalLayout_2)
        self.label_vol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_vol.setObjectName("label_vol")
        self.verticalLayout_settings.addWidget(self.label_vol)
        self.lineEdit_vol = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.verticalLayout_settings.addWidget(self.lineEdit_vol)
        self.checkBox_max = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_max.setFont(font)
        self.checkBox_max.setObjectName("checkBox_max")
        self.verticalLayout_settings.addWidget(self.checkBox_max)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(200, 20, 181, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_clt = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clt.sizePolicy().hasHeightForWidth())
        self.pushButton_clt.setSizePolicy(sizePolicy)
        self.pushButton_clt.setObjectName("pushButton_clt")
        self.gridLayout.addWidget(self.pushButton_clt, 2, 0, 1, 1)
        self.pushButton_rst = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rst.sizePolicy().hasHeightForWidth())
        self.pushButton_rst.setSizePolicy(sizePolicy)
        self.pushButton_rst.setObjectName("pushButton_rst")
        self.gridLayout.addWidget(self.pushButton_rst, 4, 0, 1, 1)
        self.pushButton_stp = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stp.sizePolicy().hasHeightForWidth())
        self.pushButton_stp.setSizePolicy(sizePolicy)
        self.pushButton_stp.setObjectName("pushButton_stp")
        self.gridLayout.addWidget(self.pushButton_stp, 1, 0, 1, 1)
        self.pushButton_run = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        self.pushButton_run.setObjectName("pushButton_run")
        self.gridLayout.addWidget(self.pushButton_run, 0, 0, 1, 1)
        self.pushButton_cla = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cla.sizePolicy().hasHeightForWidth())
        self.pushButton_cla.setSizePolicy(sizePolicy)
        self.pushButton_cla.setObjectName("pushButton_cla")
        self.gridLayout.addWidget(self.pushButton_cla, 3, 0, 1, 1)
        self.checkBox_clt = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_clt.setObjectName("checkBox_clt")
        self.gridLayout.addWidget(self.checkBox_clt, 2, 1, 1, 1)
        self.checkBox_cla = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.checkBox_cla.setObjectName("checkBox_cla")
        self.gridLayout.addWidget(self.checkBox_cla, 3, 1, 1, 1)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(200, 220, 181, 71))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.TE_status = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget_2)
        self.TE_status.setLineWidth(1)
        self.TE_status.setReadOnly(True)
        self.TE_status.setObjectName("TE_status")
        self.verticalLayout.addWidget(self.TE_status)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Syringe Pump"))
        self.label.setText(_translate("Form", "Pump diameter"))
        self.comboBox_dia.setItemText(0, _translate("Form", "1mL (4.61)"))
        self.comboBox_dia.setItemText(1, _translate("Form", "2.5 mL (7.28)"))
        self.comboBox_dia.setItemText(2, _translate("Form", "3 mL (8.66)"))
        self.comboBox_dia.setItemText(3, _translate("Form", "5 mL (10.30)"))
        self.label_direction.setText(_translate("Form", "Direction"))
        self.comboBox_drt.setItemText(0, _translate("Form", "Infusion"))
        self.comboBox_drt.setItemText(1, _translate("Form", "Reverse"))
        self.label_flrate.setText(_translate("Form", "Flow rate"))
        self.comboBox_rat.setItemText(0, _translate("Form", "ULH"))
        self.comboBox_rat.setItemText(1, _translate("Form", "ULM"))
        self.comboBox_rat.setItemText(2, _translate("Form", "MLM"))
        self.label_vol.setText(_translate("Form", "Target volume (uL)"))
        self.checkBox_max.setText(_translate("Form", "Maxrate?"))
        self.pushButton_clt.setText(_translate("Form", "Clear target"))
        self.pushButton_rst.setText(_translate("Form", "Reset"))
        self.pushButton_stp.setText(_translate("Form", "Stop"))
        self.pushButton_run.setText(_translate("Form", "Run"))
        self.pushButton_cla.setText(_translate("Form", "Clear accumu"))
        self.checkBox_clt.setText(_translate("Form", "Withdraw"))
        self.checkBox_cla.setText(_translate("Form", "Withdraw"))
        self.label_2.setText(_translate("Form", "Current status"))

