# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pump_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(428, 301)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 20, 151, 261))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_settings = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_settings.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_settings.setObjectName("verticalLayout_settings")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout_settings.addWidget(self.label)
        self.comboBox_dia = QtWidgets.QComboBox(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_dia.sizePolicy().hasHeightForWidth())
        self.comboBox_dia.setSizePolicy(sizePolicy)
        self.comboBox_dia.setObjectName("comboBox_dia")
        self.comboBox_dia.addItem("")
        self.comboBox_dia.addItem("")
        self.comboBox_dia.addItem("")
        self.comboBox_dia.addItem("")
        self.verticalLayout_settings.addWidget(self.comboBox_dia)
        self.label_direction = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_direction.setObjectName("label_direction")
        self.verticalLayout_settings.addWidget(self.label_direction)
        self.comboBox_dir = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_dir.setObjectName("comboBox_dir")
        self.comboBox_dir.addItem("")
        self.comboBox_dir.addItem("")
        self.verticalLayout_settings.addWidget(self.comboBox_dir)
        self.label_flrate = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_flrate.setObjectName("label_flrate")
        self.verticalLayout_settings.addWidget(self.label_flrate)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_rat = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_rat.setObjectName("lineEdit_rat")
        self.horizontalLayout_2.addWidget(self.lineEdit_rat)
        self.comboBox_rat = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_rat.setObjectName("comboBox_rat")
        self.comboBox_rat.addItem("")
        self.comboBox_rat.addItem("")
        self.comboBox_rat.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_rat)
        self.verticalLayout_settings.addLayout(self.horizontalLayout_2)
        self.label_vol = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_vol.setObjectName("label_vol")
        self.verticalLayout_settings.addWidget(self.label_vol)
        self.lineEdit_vol = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_vol.setObjectName("lineEdit_vol")
        self.verticalLayout_settings.addWidget(self.lineEdit_vol)
        self.checkBox_max = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_max.setFont(font)
        self.checkBox_max.setObjectName("checkBox_max")
        self.verticalLayout_settings.addWidget(self.checkBox_max)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(220, 20, 91, 221))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_btn = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_btn.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_btn.setObjectName("verticalLayout_btn")
        self.pushButton_run = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_run.sizePolicy().hasHeightForWidth())
        self.pushButton_run.setSizePolicy(sizePolicy)
        self.pushButton_run.setObjectName("pushButton_run")
        self.verticalLayout_btn.addWidget(self.pushButton_run)
        self.pushButton_stp = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stp.sizePolicy().hasHeightForWidth())
        self.pushButton_stp.setSizePolicy(sizePolicy)
        self.pushButton_stp.setObjectName("pushButton_stp")
        self.verticalLayout_btn.addWidget(self.pushButton_stp)
        self.pushButton_clr = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clr.sizePolicy().hasHeightForWidth())
        self.pushButton_clr.setSizePolicy(sizePolicy)
        self.pushButton_clr.setObjectName("pushButton_clr")
        self.verticalLayout_btn.addWidget(self.pushButton_clr)
        self.pushButton_clv = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clv.sizePolicy().hasHeightForWidth())
        self.pushButton_clv.setSizePolicy(sizePolicy)
        self.pushButton_clv.setObjectName("pushButton_clv")
        self.verticalLayout_btn.addWidget(self.pushButton_clv)
        self.pushButton_rst = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_rst.sizePolicy().hasHeightForWidth())
        self.pushButton_rst.setSizePolicy(sizePolicy)
        self.pushButton_rst.setObjectName("pushButton_rst")
        self.verticalLayout_btn.addWidget(self.pushButton_rst)
        self.plainTextEdit_status = QtWidgets.QPlainTextEdit(Form)
        self.plainTextEdit_status.setGeometry(QtCore.QRect(220, 250, 171, 31))
        self.plainTextEdit_status.setLineWidth(1)
        self.plainTextEdit_status.setReadOnly(True)
        self.plainTextEdit_status.setObjectName("plainTextEdit_status")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Syringe Pump"))
        self.label.setText(_translate("Form", "Pump diameter"))
        self.comboBox_dia.setItemText(0, _translate("Form", "1mL (4.61)"))
        self.comboBox_dia.setItemText(1, _translate("Form", "2.5 mL (7.28)"))
        self.comboBox_dia.setItemText(2, _translate("Form", "3 mL (8.66)"))
        self.comboBox_dia.setItemText(3, _translate("Form", "5 mL (10.30)"))
        self.label_direction.setText(_translate("Form", "Direction"))
        self.comboBox_dir.setItemText(0, _translate("Form", "Forward"))
        self.comboBox_dir.setItemText(1, _translate("Form", "Reverse"))
        self.label_flrate.setText(_translate("Form", "Flow rate"))
        self.comboBox_rat.setItemText(0, _translate("Form", "ULH"))
        self.comboBox_rat.setItemText(1, _translate("Form", "ULM"))
        self.comboBox_rat.setItemText(2, _translate("Form", "MLM"))
        self.label_vol.setText(_translate("Form", "Volume (uL)"))
        self.checkBox_max.setText(_translate("Form", "Maxrate?"))
        self.pushButton_run.setText(_translate("Form", "Run"))
        self.pushButton_stp.setText(_translate("Form", "Stop"))
        self.pushButton_clr.setText(_translate("Form", "Clear rate"))
        self.pushButton_clv.setText(_translate("Form", "Clear volume"))
        self.pushButton_rst.setText(_translate("Form", "Reset"))

