# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'stage_design.ui'
#
# Created: Wed Jul 08 13:19:54 2015
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(415, 428)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Marzhauser stage", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Position Control", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelSetX = QtGui.QLabel(self.groupBox)
        self.labelSetX.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSetX.setObjectName(_fromUtf8("labelSetX"))
        self.gridLayout.addWidget(self.labelSetX, 0, 0, 1, 1)
        self.labelSetY = QtGui.QLabel(self.groupBox)
        self.labelSetY.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSetY.setObjectName(_fromUtf8("labelSetY"))
        self.gridLayout.addWidget(self.labelSetY, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setText(QtGui.QApplication.translate("Form", "xy", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.pushButtonUp = QtGui.QPushButton(self.groupBox)
        self.pushButtonUp.setText(QtGui.QApplication.translate("Form", "^", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonUp.setObjectName(_fromUtf8("pushButtonUp"))
        self.gridLayout.addWidget(self.pushButtonUp, 1, 5, 1, 1)
        self.pushButtonHomeXY = QtGui.QPushButton(self.groupBox)
        self.pushButtonHomeXY.setText(QtGui.QApplication.translate("Form", "Home", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonHomeXY.setObjectName(_fromUtf8("pushButtonHomeXY"))
        self.gridLayout.addWidget(self.pushButtonHomeXY, 2, 5, 1, 1)
        self.pushButtonDown = QtGui.QPushButton(self.groupBox)
        self.pushButtonDown.setText(QtGui.QApplication.translate("Form", "v", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonDown.setObjectName(_fromUtf8("pushButtonDown"))
        self.gridLayout.addWidget(self.pushButtonDown, 3, 5, 1, 1)
        self.pushButtonLeft = QtGui.QPushButton(self.groupBox)
        self.pushButtonLeft.setText(QtGui.QApplication.translate("Form", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonLeft.setObjectName(_fromUtf8("pushButtonLeft"))
        self.gridLayout.addWidget(self.pushButtonLeft, 2, 2, 1, 1)
        self.pushButtonRight = QtGui.QPushButton(self.groupBox)
        self.pushButtonRight.setText(QtGui.QApplication.translate("Form", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonRight.setObjectName(_fromUtf8("pushButtonRight"))
        self.gridLayout.addWidget(self.pushButtonRight, 2, 6, 1, 1)
        self.doubleSpinBoxStep = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxStep.setProperty("value", 1.0)
        self.doubleSpinBoxStep.setObjectName(_fromUtf8("doubleSpinBoxStep"))
        self.gridLayout.addWidget(self.doubleSpinBoxStep, 3, 1, 1, 1)
        self.lineEdit_xpos = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_xpos.setObjectName(_fromUtf8("lineEdit_xpos"))
        self.gridLayout.addWidget(self.lineEdit_xpos, 0, 1, 1, 1)
        self.lineEdit_ypos = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_ypos.setObjectName(_fromUtf8("lineEdit_ypos"))
        self.gridLayout.addWidget(self.lineEdit_ypos, 1, 1, 1, 1)
        self.axisstatus_pushButton = QtGui.QPushButton(self.groupBox)
        self.axisstatus_pushButton.setText(QtGui.QApplication.translate("Form", "STATUS", None, QtGui.QApplication.UnicodeUTF8))
        self.axisstatus_pushButton.setObjectName(_fromUtf8("axisstatus_pushButton"))
        self.gridLayout.addWidget(self.axisstatus_pushButton, 0, 6, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Information", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setText(QtGui.QApplication.translate("Form", "Position [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 1, 1, 1, 1)
        self.labelGetX = QtGui.QLabel(self.groupBox_3)
        self.labelGetX.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGetX.setObjectName(_fromUtf8("labelGetX"))
        self.gridLayout_3.addWidget(self.labelGetX, 3, 0, 1, 1)
        self.labelGetY = QtGui.QLabel(self.groupBox_3)
        self.labelGetY.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.labelGetY.setObjectName(_fromUtf8("labelGetY"))
        self.gridLayout_3.addWidget(self.labelGetY, 4, 0, 1, 1)
        self.labelX = QtGui.QLabel(self.groupBox_3)
        self.labelX.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelX.setObjectName(_fromUtf8("labelX"))
        self.gridLayout_3.addWidget(self.labelX, 3, 1, 1, 1)
        self.labelY = QtGui.QLabel(self.groupBox_3)
        self.labelY.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelY.setObjectName(_fromUtf8("labelY"))
        self.gridLayout_3.addWidget(self.labelY, 4, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.groupBox_3)
        self.label_21.setText(QtGui.QApplication.translate("Form", "Range [um]", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_3.addWidget(self.label_21, 1, 2, 1, 1)
        self.labelRangeX = QtGui.QLabel(self.groupBox_3)
        self.labelRangeX.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRangeX.setObjectName(_fromUtf8("labelRangeX"))
        self.gridLayout_3.addWidget(self.labelRangeX, 3, 2, 1, 1)
        self.labelRangeY = QtGui.QLabel(self.groupBox_3)
        self.labelRangeY.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelRangeY.setObjectName(_fromUtf8("labelRangeY"))
        self.gridLayout_3.addWidget(self.labelRangeY, 4, 2, 1, 1)
        self.updateInfo_checkBox = QtGui.QCheckBox(self.groupBox_3)
        self.updateInfo_checkBox.setText(QtGui.QApplication.translate("Form", "update info?", None, QtGui.QApplication.UnicodeUTF8))
        self.updateInfo_checkBox.setObjectName(_fromUtf8("updateInfo_checkBox"))
        self.gridLayout_3.addWidget(self.updateInfo_checkBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Saw-tooth movement", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.xsawtooth_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.xsawtooth_radioButton.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.xsawtooth_radioButton.setObjectName(_fromUtf8("xsawtooth_radioButton"))
        self.gridLayout_2.addWidget(self.xsawtooth_radioButton, 0, 1, 1, 1)
        self.ysawtooth_radioButton = QtGui.QRadioButton(self.groupBox_2)
        self.ysawtooth_radioButton.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.ysawtooth_radioButton.setObjectName(_fromUtf8("ysawtooth_radioButton"))
        self.gridLayout_2.addWidget(self.ysawtooth_radioButton, 0, 2, 1, 1)
        self.sawtoothMovement_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.sawtoothMovement_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sawtoothMovement_lineEdit.setObjectName(_fromUtf8("sawtoothMovement_lineEdit"))
        self.gridLayout_2.addWidget(self.sawtoothMovement_lineEdit, 0, 3, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setText(QtGui.QApplication.translate("Form", "microns", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("Form", "repeats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 6, 1, 1)
        self.sawtoothRepeats_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.sawtoothRepeats_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sawtoothRepeats_lineEdit.setObjectName(_fromUtf8("sawtoothRepeats_lineEdit"))
        self.gridLayout_2.addWidget(self.sawtoothRepeats_lineEdit, 0, 5, 1, 1)
        self.sawtoothTimeDelay_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.sawtoothTimeDelay_lineEdit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.sawtoothTimeDelay_lineEdit.setObjectName(_fromUtf8("sawtoothTimeDelay_lineEdit"))
        self.gridLayout_2.addWidget(self.sawtoothTimeDelay_lineEdit, 0, 7, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(QtGui.QApplication.translate("Form", "ms time delay", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 8, 1, 1)
        self.go_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.go_pushButton.setText(QtGui.QApplication.translate("Form", "Go", None, QtGui.QApplication.UnicodeUTF8))
        self.go_pushButton.setObjectName(_fromUtf8("go_pushButton"))
        self.gridLayout_2.addWidget(self.go_pushButton, 1, 8, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Velocity", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.pushButton_getSpeed = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_getSpeed.setGeometry(QtCore.QRect(20, 20, 75, 23))
        self.pushButton_getSpeed.setText(QtGui.QApplication.translate("Form", "Get Speed", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_getSpeed.setObjectName(_fromUtf8("pushButton_getSpeed"))
        self.label_vx = QtGui.QLabel(self.groupBox_4)
        self.label_vx.setGeometry(QtCore.QRect(110, 20, 81, 16))
        self.label_vx.setText(QtGui.QApplication.translate("Form", "vx: ----", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vx.setObjectName(_fromUtf8("label_vx"))
        self.label_vy = QtGui.QLabel(self.groupBox_4)
        self.label_vy.setGeometry(QtCore.QRect(110, 40, 81, 16))
        self.label_vy.setText(QtGui.QApplication.translate("Form", "vy: ----", None, QtGui.QApplication.UnicodeUTF8))
        self.label_vy.setObjectName(_fromUtf8("label_vy"))
        self.lineEdit_vx = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_vx.setGeometry(QtCore.QRect(240, 20, 51, 20))
        self.lineEdit_vx.setObjectName(_fromUtf8("lineEdit_vx"))
        self.lineEdit_vy = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_vy.setGeometry(QtCore.QRect(240, 50, 51, 20))
        self.lineEdit_vy.setObjectName(_fromUtf8("lineEdit_vy"))
        self.label_6 = QtGui.QLabel(self.groupBox_4)
        self.label_6.setGeometry(QtCore.QRect(210, 20, 31, 16))
        self.label_6.setText(QtGui.QApplication.translate("Form", "X Vel.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setGeometry(QtCore.QRect(210, 50, 31, 16))
        self.label_7.setText(QtGui.QApplication.translate("Form", "Y Vel.", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton_setVX = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_setVX.setGeometry(QtCore.QRect(300, 20, 51, 23))
        self.pushButton_setVX.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setVX.setObjectName(_fromUtf8("pushButton_setVX"))
        self.pushButton_setVY = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_setVY.setGeometry(QtCore.QRect(300, 50, 51, 23))
        self.pushButton_setVY.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_setVY.setObjectName(_fromUtf8("pushButton_setVY"))
        self.verticalLayout.addWidget(self.groupBox_4)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

