# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nanodrive_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(449, 280)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.labelSetX = QtWidgets.QLabel(self.groupBox)
        self.labelSetX.setObjectName("labelSetX")
        self.gridLayout.addWidget(self.labelSetX, 0, 0, 1, 1)
        self.labelSetY = QtWidgets.QLabel(self.groupBox)
        self.labelSetY.setObjectName("labelSetY")
        self.gridLayout.addWidget(self.labelSetY, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 5, 1, 1)
        self.pushButtonUp = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonUp.setObjectName("pushButtonUp")
        self.gridLayout.addWidget(self.pushButtonUp, 1, 5, 1, 1)
        self.pushButtonHomeXY = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonHomeXY.setObjectName("pushButtonHomeXY")
        self.gridLayout.addWidget(self.pushButtonHomeXY, 2, 5, 1, 1)
        self.pushButtonDown = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDown.setObjectName("pushButtonDown")
        self.gridLayout.addWidget(self.pushButtonDown, 3, 5, 1, 1)
        self.pushButtonLeft = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.gridLayout.addWidget(self.pushButtonLeft, 2, 2, 1, 1)
        self.pushButtonRight = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.gridLayout.addWidget(self.pushButtonRight, 2, 6, 1, 1)
        self.pushButtonUpZ = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonUpZ.setObjectName("pushButtonUpZ")
        self.gridLayout.addWidget(self.pushButtonUpZ, 1, 7, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 7, 1, 1)
        self.pushButtonHomeZ = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonHomeZ.setObjectName("pushButtonHomeZ")
        self.gridLayout.addWidget(self.pushButtonHomeZ, 2, 7, 1, 1)
        self.pushButtonDownZ = QtWidgets.QPushButton(self.groupBox)
        self.pushButtonDownZ.setObjectName("pushButtonDownZ")
        self.gridLayout.addWidget(self.pushButtonDownZ, 3, 7, 1, 1)
        self.doubleSpinBoxX = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxX.setObjectName("doubleSpinBoxX")
        self.gridLayout.addWidget(self.doubleSpinBoxX, 0, 1, 1, 1)
        self.doubleSpinBoxY = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxY.setObjectName("doubleSpinBoxY")
        self.gridLayout.addWidget(self.doubleSpinBoxY, 1, 1, 1, 1)
        self.doubleSpinBoxZ = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxZ.setObjectName("doubleSpinBoxZ")
        self.gridLayout.addWidget(self.doubleSpinBoxZ, 2, 1, 1, 1)
        self.doubleSpinBoxStep = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxStep.setProperty("value", 1.0)
        self.doubleSpinBoxStep.setObjectName("doubleSpinBoxStep")
        self.gridLayout.addWidget(self.doubleSpinBoxStep, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_18 = QtWidgets.QLabel(self.groupBox_3)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 1, 1, 1, 1)
        self.labelGetX = QtWidgets.QLabel(self.groupBox_3)
        self.labelGetX.setObjectName("labelGetX")
        self.gridLayout_3.addWidget(self.labelGetX, 3, 0, 1, 1)
        self.labelGetY = QtWidgets.QLabel(self.groupBox_3)
        self.labelGetY.setObjectName("labelGetY")
        self.gridLayout_3.addWidget(self.labelGetY, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 5, 0, 1, 1)
        self.labelX = QtWidgets.QLabel(self.groupBox_3)
        self.labelX.setObjectName("labelX")
        self.gridLayout_3.addWidget(self.labelX, 3, 1, 1, 1)
        self.labelY = QtWidgets.QLabel(self.groupBox_3)
        self.labelY.setObjectName("labelY")
        self.gridLayout_3.addWidget(self.labelY, 4, 1, 1, 1)
        self.labelZ = QtWidgets.QLabel(self.groupBox_3)
        self.labelZ.setObjectName("labelZ")
        self.gridLayout_3.addWidget(self.labelZ, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 2, 1, 1)
        self.labelRangeX = QtWidgets.QLabel(self.groupBox_3)
        self.labelRangeX.setObjectName("labelRangeX")
        self.gridLayout_3.addWidget(self.labelRangeX, 3, 2, 1, 1)
        self.labelRangeY = QtWidgets.QLabel(self.groupBox_3)
        self.labelRangeY.setObjectName("labelRangeY")
        self.gridLayout_3.addWidget(self.labelRangeY, 4, 2, 1, 1)
        self.labelRangeZ = QtWidgets.QLabel(self.groupBox_3)
        self.labelRangeZ.setObjectName("labelRangeZ")
        self.gridLayout_3.addWidget(self.labelRangeZ, 5, 2, 1, 1)
        self.updateInfo_checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.updateInfo_checkBox.setObjectName("updateInfo_checkBox")
        self.gridLayout_3.addWidget(self.updateInfo_checkBox, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Piezo stage"))
        self.groupBox.setTitle(_translate("Form", "Position Control"))
        self.labelSetX.setText(_translate("Form", "x"))
        self.labelSetY.setText(_translate("Form", "y"))
        self.label_3.setText(_translate("Form", "z"))
        self.label_4.setText(_translate("Form", "Step:"))
        self.label_5.setText(_translate("Form", "xy"))
        self.pushButtonUp.setText(_translate("Form", "^"))
        self.pushButtonHomeXY.setText(_translate("Form", "Home"))
        self.pushButtonDown.setText(_translate("Form", "v"))
        self.pushButtonLeft.setText(_translate("Form", "<"))
        self.pushButtonRight.setText(_translate("Form", ">"))
        self.pushButtonUpZ.setText(_translate("Form", "^"))
        self.label_6.setText(_translate("Form", "z"))
        self.pushButtonHomeZ.setText(_translate("Form", "Home"))
        self.pushButtonDownZ.setText(_translate("Form", "v"))
        self.groupBox_3.setTitle(_translate("Form", "Information"))
        self.label_18.setText(_translate("Form", "Position [um]"))
        self.labelGetX.setText(_translate("Form", "x"))
        self.labelGetY.setText(_translate("Form", "y"))
        self.label_16.setText(_translate("Form", "z"))
        self.labelX.setText(_translate("Form", "-"))
        self.labelY.setText(_translate("Form", "-"))
        self.labelZ.setText(_translate("Form", "-"))
        self.label_21.setText(_translate("Form", "Range [um]"))
        self.labelRangeX.setText(_translate("Form", "-"))
        self.labelRangeY.setText(_translate("Form", "-"))
        self.labelRangeZ.setText(_translate("Form", "-"))
        self.updateInfo_checkBox.setText(_translate("Form", "Update info?"))

