# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMC_multicorrection_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(968, 698)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Preferred, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 440, 171, 118))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Acquisition_settings = QtGui.QWidget.QGridLayout(self.gridLayoutWidget)
        self.Acquisition_settings.setContentsMargins(0, 0, 0, 0)
        self.Acquisition_settings.setObjectName("Acquisition_settings")
        self.label_nsteps = QtGui.QWidget.QLabel(self.gridLayoutWidget)
        self.label_nsteps.setObjectName("label_nsteps")
        self.Acquisition_settings.addWidget(self.label_nsteps, 2, 0, 1, 1)
        self.Filename = QtGui.QWidget.QLineEdit(self.gridLayoutWidget)
        self.Filename.setObjectName("Filename")
        self.Acquisition_settings.addWidget(self.Filename, 0, 2, 1, 1)
        self.label_fname = QtGui.QWidget.QLabel(self.gridLayoutWidget)
        self.label_fname.setObjectName("label_fname")
        self.Acquisition_settings.addWidget(self.label_fname, 0, 0, 1, 1)
        self.lineEdit_dz = QtGui.QWidget.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dz.setObjectName("lineEdit_dz")
        self.Acquisition_settings.addWidget(self.lineEdit, 1, 2, 1, 1)
        self.label_stepsize = QtGui.QWidget.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Preferred, QtGui.QWidget.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stepsize.sizePolicy().hasHeightForWidth())
        self.label_stepsize.setSizePolicy(sizePolicy)
        self.label_stepsize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_stepsize.setObjectName("label_stepsize")
        self.Acquisition_settings.addWidget(self.label_stepsize, 1, 0, 1, 1)
        self.spinbox_Nsteps = QtGui.QWidget.QSpinBox(self.gridLayoutWidget)
        self.spinbox_Nsteps.setMinimum(3)
        self.spinbox_Nsteps.setMaximum(50)
        self.spinbox_Nsteps.setObjectName("spinbox_Nsteps")
        self.Acquisition_settings.addWidget(self.spinbox_Nsteps, 2, 2, 1, 1)
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(210, 440, 451, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout = QtGui.QWidget.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout.setSizeConstraint(QtGui.QWidget.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_synthesize = QtGui.QWidget.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Expanding, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_synthesize.sizePolicy().hasHeightForWidth())
        self.pushButton_synthesize.setSizePolicy(sizePolicy)
        self.pushButton_synthesize.setObjectName("pushButton_synthesize")
        self.gridLayout.addWidget(self.pushButton_synthesize, 0, 1, 1, 1)
        self.pushButton_clear = QtGui.QWidget.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Expanding, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.gridLayout.addWidget(self.pushButton_clear, 0, 4, 1, 1)
        self.pushButton_apply2mirror = QtGui.QWidget.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Minimum, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_apply2mirror.sizePolicy().hasHeightForWidth())
        self.pushButton_apply2mirror.setSizePolicy(sizePolicy)
        self.pushButton_apply2mirror.setObjectName("pushButton_apply2mirror")
        self.gridLayout.addWidget(self.pushButton_apply2mirror, 1, 1, 1, 1)
        self.pushButton_reset = QtGui.QWidget.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Minimum, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 1, 4, 1, 1)
        self.pushButton_acquire = QtGui.QWidget.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Expanding, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_acquire.sizePolicy().hasHeightForWidth())
        self.pushButton_acquire.setSizePolicy(sizePolicy)
        self.pushButton_acquire.setObjectName("pushButton_acquire")
        self.gridLayout.addWidget(self.pushButton_acquire, 0, 0, 1, 1)
        self.pushButton_snapshot = QtGui.QWidget.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtGui.QWidget.QSizePolicy(QtGui.QWidget.QSizePolicy.Expanding, QtGui.QWidget.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_snapshot.sizePolicy().hasHeightForWidth())
        self.pushButton_snapshot.setSizePolicy(sizePolicy)
        self.pushButton_snapshot.setObjectName("pushButton_snapshot")
        self.gridLayout.addWidget(self.pushButton_snapshot, 1, 0, 1, 1)
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(679, 80, 271, 501))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout = QtGui.QWidget.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_Zcoeffs = QtGui.QWidget.QTableWidget(self.verticalLayoutWidget_2)
        self.table_Zcoeffs.setObjectName("table_Zcoeffs")
        self.table_Zcoeffs.setColumnCount(1)
        self.table_Zcoeffs.setRowCount(22)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(0, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(1, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(2, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(3, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(4, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(5, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(6, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(7, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(8, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(9, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(10, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(11, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(12, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(13, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(14, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(15, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(16, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(17, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(18, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(19, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(20, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(21, item)
        item = QtGui.QWidget.QTableWidgetItem()
        self.table_Zcoeffs.setHorizontalHeaderItem(0, item)
        self.verticalLayout.addWidget(self.table_Zcoeffs)
        self.label_Zselect = QtGui.QWidget.QLabel(self.verticalLayoutWidget_2)
        self.label_Zselect.setObjectName("label_Zselect")
        self.verticalLayout.addWidget(self.label_Zselect)
        self.spinbox_Zmode = QtGui.QWidget.QSpinBox(self.verticalLayoutWidget_2)
        self.spinbox_Zmode.setAutoFillBackground(False)
        self.spinbox_Zmode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinbox_Zmode.setObjectName("spinbox_Zmode")
        self.verticalLayout.addWidget(self.spinbox_Zmode)
        self.slider_Zmode = QtGui.QWidget.QSlider(self.verticalLayoutWidget_2)
        self.slider_Zmode.setMinimum(-50)
        self.slider_Zmode.setMaximum(50)
        self.slider_Zmode.setSingleStep(1)
        self.slider_Zmode.setOrientation(QtCore.Qt.Horizontal)
        self.slider_Zmode.setObjectName("slider_Zmode")
        self.verticalLayout.addWidget(self.slider_Zmode)
        self.tab_display = QtGui.QWidget.QTabWidget(self.centralwidget)
        self.tab_display.setGeometry(QtCore.QRect(10, 50, 661, 381))
        self.tab_display.setObjectName("tab_display")
        self.tab_image_phase = QtGui.QWidget()
        self.tab_image_phase.setObjectName("tab_image_phase")
        self.mpl_image = QtGui.QWidget.QGraphicsView(self.tab_image_phase)
        self.mpl_image.setGeometry(QtCore.QRect(10, 30, 311, 301))
        self.mpl_image.setObjectName("mpl_image")
        self.mpl_phase = QtGui.QWidget.QGraphicsView(self.tab_image_phase)
        self.mpl_phase.setGeometry(QtCore.QRect(330, 30, 311, 301))
        self.mpl_phase.setObjectName("mpl_phase")
        self.tab_display.addTab(self.tab_image_phase, "")
        self.tab_metric = QtGui.QWidget()
        self.tab_metric.setObjectName("tab_metric")
        self.mpl_metrics = QtGui.QWidget.QGraphicsView(self.tab_metric)
        self.mpl_metrics.setGeometry(QtCore.QRect(20, 41, 571, 251))
        self.mpl_metrics.setObjectName("mpl_metrics")
        self.tab_display.addTab(self.tab_metric, "")
        self.tab_zfit = QtGui.QWidget()
        self.tab_zfit.setObjectName("tab_zfit")
        self.tab_display.addTab(self.tab_zfit, "")
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.verticalLayoutWidget_2.raise_()
        self.tab_display.raise_()
        self.table_Zcoeffs.raise_()
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QWidget.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 25))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtGui.QWidget.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        self.tab_display.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.label_nsteps.setText(_translate("Form", "# of steps"))
        self.label_fname.setText(_translate("Form", "Filename"))
        self.label_stepsize.setText(_translate("Form", "dz"))
        self.pushButton_synthesize.setText(_translate("Form", "Synthesize"))
        self.pushButton_clear.setText(_translate("Form", "Clear"))
        self.pushButton_apply2mirror.setText(_translate("Form", "Apply to mirror"))
        self.pushButton_reset.setText(_translate("Form", "Reset Mirror"))
        self.pushButton_acquire.setText(_translate("Form", "Acquire stack"))
        self.pushButton_snapshot.setText(_translate("Form", "Snapshot"))
        item = self.table_Zcoeffs.verticalHeaderItem(0)
        item.setText(_translate("Form", "Z4 (defocus)"))
        item = self.table_Zcoeffs.verticalHeaderItem(1)
        item.setText(_translate("Form", "Z5 (astigm. )"))
        item = self.table_Zcoeffs.verticalHeaderItem(2)
        item.setText(_translate("Form", "Z6 (astigm. )"))
        item = self.table_Zcoeffs.verticalHeaderItem(3)
        item.setText(_translate("Form", "Z7 (coma)"))
        item = self.table_Zcoeffs.verticalHeaderItem(4)
        item.setText(_translate("Form", "Z8 (coma)"))
        item = self.table_Zcoeffs.verticalHeaderItem(5)
        item.setText(_translate("Form", "Z9"))
        item = self.table_Zcoeffs.verticalHeaderItem(6)
        item.setText(_translate("Form", "Z10"))
        item = self.table_Zcoeffs.verticalHeaderItem(7)
        item.setText(_translate("Form", "Z11 (pri. spherical)"))
        item = self.table_Zcoeffs.verticalHeaderItem(8)
        item.setText(_translate("Form", "Z12"))
        item = self.table_Zcoeffs.verticalHeaderItem(9)
        item.setText(_translate("Form", "Z13"))
        item = self.table_Zcoeffs.verticalHeaderItem(10)
        item.setText(_translate("Form", "Z14"))
        item = self.table_Zcoeffs.verticalHeaderItem(11)
        item.setText(_translate("Form", "Z15"))
        item = self.table_Zcoeffs.verticalHeaderItem(12)
        item.setText(_translate("Form", "Z16"))
        item = self.table_Zcoeffs.verticalHeaderItem(13)
        item.setText(_translate("Form", "Z17"))
        item = self.table_Zcoeffs.verticalHeaderItem(14)
        item.setText(_translate("Form", "Z18"))
        item = self.table_Zcoeffs.verticalHeaderItem(15)
        item.setText(_translate("Form", "Z19"))
        item = self.table_Zcoeffs.verticalHeaderItem(16)
        item.setText(_translate("Form", "Z20"))
        item = self.table_Zcoeffs.verticalHeaderItem(17)
        item.setText(_translate("Form", "Z21"))
        item = self.table_Zcoeffs.verticalHeaderItem(18)
        item.setText(_translate("Form", "Z22"))
        item = self.table_Zcoeffs.verticalHeaderItem(19)
        item.setText(_translate("Form", "Z23"))
        item = self.table_Zcoeffs.verticalHeaderItem(20)
        item.setText(_translate("Form", "Z24"))
        item = self.table_Zcoeffs.verticalHeaderItem(21)
        item.setText(_translate("Form", "Z25"))
        item = self.table_Zcoeffs.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Amplitude"))
        self.label_Zselect.setText(_translate("Form", "Select Zernike mode"))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_image_phase), _translate("Form", "Image and phase"))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_metric), _translate("Form", "Metric"))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_zfit), _translate("Form", "Zernike_fit"))
