# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMC_Multicorrection.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui, QtWidgets

class UI_Form(object):
    def setupUi(self, BMC_Multicorrection):
        BMC_Multicorrection.setObjectName("BMC_Multicorrection")
        BMC_Multicorrection.resize(920, 698)
        self.centralwidget = QtWidgets.QWidget(BMC_Multicorrection)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 470, 231, 81))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.Continuous_varying = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.Continuous_varying.setContentsMargins(1, 0, 1, 0)
        self.Continuous_varying.setObjectName("Continuous_varying")
        self.Zernike_slider = QtWidgets.QSlider(self.verticalLayoutWidget)
        self.Zernike_slider.setMinimum(-50)
        self.Zernike_slider.setMaximum(50)
        self.Zernike_slider.setSingleStep(1)
        self.Zernike_slider.setOrientation(QtCore.Qt.Horizontal)
        self.Zernike_slider.setObjectName("Zernike_slider")
        self.Continuous_varying.addWidget(self.Zernike_slider)
        self.Zernike_mode = QtWidgets.QSpinBox(self.verticalLayoutWidget)
        self.Zernike_mode.setAutoFillBackground(False)
        self.Zernike_mode.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.Zernike_mode.setObjectName("Zernike_mode")
        self.Continuous_varying.addWidget(self.Zernike_mode)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(310, 70, 481, 481))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_clearpattern = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_clearpattern.setObjectName("pushButton_clearpattern")
        self.horizontalLayout.addWidget(self.pushButton_clearpattern)
        self.pushButton_Fit = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Fit.setObjectName("pushButton_Fit")
        self.horizontalLayout.addWidget(self.pushButton_Fit)
        self.pushButton_modulate = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_modulate.setObjectName("pushButton_modulate")
        self.horizontalLayout.addWidget(self.pushButton_modulate)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 2, 1)
        self.Pupil_pattern = QtWidgets.QGraphicsView(self.gridLayoutWidget)
        self.Pupil_pattern.setObjectName("Pupil_pattern")
        self.gridLayout.addWidget(self.Pupil_pattern, 0, 0, 1, 1)
        self.Zernike_coefficients = QtWidgets.QTableWidget(self.centralwidget)
        self.Zernike_coefficients.setGeometry(QtCore.QRect(40, 70, 251, 391))
        self.Zernike_coefficients.setObjectName("Zernike_coefficients")
        self.Zernike_coefficients.setColumnCount(1)
        self.Zernike_coefficients.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.Zernike_coefficients.setHorizontalHeaderItem(0, item)
        self.pushButton_reset = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_reset.setGeometry(QtCore.QRect(40, 600, 151, 41))
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.pushButton_apply2mirror = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_apply2mirror.setGeometry(QtCore.QRect(200, 600, 141, 41))
        self.pushButton_apply2mirror.setObjectName("pushButton_apply2mirror")
        self.pushButton_acquire = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_acquire.setGeometry(QtCore.QRect(350, 600, 141, 41))
        self.pushButton_acquire.setObjectName("pushButton_acquire")
        BMC_Multicorrection.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BMC_Multicorrection)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 25))
        self.menubar.setObjectName("menubar")
        BMC_Multicorrection.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BMC_Multicorrection)
        self.statusbar.setObjectName("statusbar")
        BMC_Multicorrection.setStatusBar(self.statusbar)

        self.retranslateUi(BMC_Multicorrection)
        QtCore.QMetaObject.connectSlotsByName(BMC_Multicorrection)

    def retranslateUi(self, BMC_Multicorrection):
        _translate = QtCore.QCoreApplication.translate
        BMC_Multicorrection.setWindowTitle(_translate("BMC_Multicorrection", "MainWindow"))
        self.pushButton_clearpattern.setText(_translate("BMC_Multicorrection", "Clear"))
        self.pushButton_Fit.setText(_translate("BMC_Multicorrection", "Fit"))
        self.pushButton_modulate.setText(_translate("BMC_Multicorrection", "Modulate"))
        item = self.Zernike_coefficients.verticalHeaderItem(0)
        item.setText(_translate("BMC_Multicorrection", "Z4 (defocus)"))
        item = self.Zernike_coefficients.verticalHeaderItem(1)
        item.setText(_translate("BMC_Multicorrection", "Z5 (astigm. )"))
        item = self.Zernike_coefficients.verticalHeaderItem(2)
        item.setText(_translate("BMC_Multicorrection", "Z6 (astigm. )"))
        item = self.Zernike_coefficients.verticalHeaderItem(3)
        item.setText(_translate("BMC_Multicorrection", "Z7 (coma)"))
        item = self.Zernike_coefficients.verticalHeaderItem(4)
        item.setText(_translate("BMC_Multicorrection", "Z8 (coma)"))
        item = self.Zernike_coefficients.verticalHeaderItem(5)
        item.setText(_translate("BMC_Multicorrection", "Z9"))
        item = self.Zernike_coefficients.verticalHeaderItem(6)
        item.setText(_translate("BMC_Multicorrection", "Z10"))
        item = self.Zernike_coefficients.verticalHeaderItem(7)
        item.setText(_translate("BMC_Multicorrection", "Z11 (pri. spherical)"))
        item = self.Zernike_coefficients.verticalHeaderItem(8)
        item.setText(_translate("BMC_Multicorrection", "Z12"))
        item = self.Zernike_coefficients.verticalHeaderItem(9)
        item.setText(_translate("BMC_Multicorrection", "Z13"))
        item = self.Zernike_coefficients.verticalHeaderItem(10)
        item.setText(_translate("BMC_Multicorrection", "Z14"))
        item = self.Zernike_coefficients.verticalHeaderItem(11)
        item.setText(_translate("BMC_Multicorrection", "Z15"))
        item = self.Zernike_coefficients.verticalHeaderItem(12)
        item.setText(_translate("BMC_Multicorrection", "Z16"))
        item = self.Zernike_coefficients.horizontalHeaderItem(0)
        item.setText(_translate("BMC_Multicorrection", "Amplitude"))
        self.pushButton_reset.setText(_translate("BMC_Multicorrection", "Reset Mirror"))
        self.pushButton_apply2mirror.setText(_translate("BMC_Multicorrection", "Apply to mirror"))
        self.pushButton_acquire.setText(_translate("BMC_Multicorrection", "Acquire image"))
