# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BMC_multicorrection_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(968, 698)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Form)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 440, 191, 128))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.grid_aqsettings = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.grid_aqsettings.setContentsMargins(0, 0, 0, 0)
        self.grid_aqsettings.setObjectName("grid_aqsettings")
        self.label_nsteps = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_nsteps.setObjectName("label_nsteps")
        self.grid_aqsettings.addWidget(self.label_nsteps, 2, 0, 1, 1)
        self.spinbox_Nsteps = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.spinbox_Nsteps.setMinimum(3)
        self.spinbox_Nsteps.setMaximum(50)
        self.spinbox_Nsteps.setObjectName("spinbox_Nsteps")
        self.grid_aqsettings.addWidget(self.spinbox_Nsteps, 2, 2, 1, 1)
        self.label_fname = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_fname.setObjectName("label_fname")
        self.grid_aqsettings.addWidget(self.label_fname, 0, 0, 1, 1)
        self.lineEdit_dz = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_dz.setObjectName("lineEdit_dz")
        self.grid_aqsettings.addWidget(self.lineEdit_dz, 1, 2, 1, 1)
        self.label_stepsize = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_stepsize.sizePolicy().hasHeightForWidth())
        self.label_stepsize.setSizePolicy(sizePolicy)
        self.label_stepsize.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_stepsize.setObjectName("label_stepsize")
        self.grid_aqsettings.addWidget(self.label_stepsize, 1, 0, 1, 1)
        self.lineEdit_mask = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_mask.setObjectName("lineEdit_mask")
        self.grid_aqsettings.addWidget(self.lineEdit_mask, 3, 2, 1, 1)
        self.line_Filename = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.line_Filename.setObjectName("line_Filename")
        self.grid_aqsettings.addWidget(self.line_Filename, 0, 2, 1, 1)
        self.label_masksize = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_masksize.setObjectName("label_masksize")
        self.grid_aqsettings.addWidget(self.label_masksize, 3, 0, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(210, 440, 451, 131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.grid_mainbuttons = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.grid_mainbuttons.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.grid_mainbuttons.setContentsMargins(0, 0, 0, 0)
        self.grid_mainbuttons.setHorizontalSpacing(6)
        self.grid_mainbuttons.setObjectName("grid_mainbuttons")
        self.pushButton_synthesize = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_synthesize.sizePolicy().hasHeightForWidth())
        self.pushButton_synthesize.setSizePolicy(sizePolicy)
        self.pushButton_synthesize.setObjectName("pushButton_synthesize")
        self.grid_mainbuttons.addWidget(self.pushButton_synthesize, 0, 1, 1, 1)
        self.pushButton_clear = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_clear.setSizePolicy(sizePolicy)
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.grid_mainbuttons.addWidget(self.pushButton_clear, 0, 4, 1, 1)
        self.pushButton_apply2mirror = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_apply2mirror.sizePolicy().hasHeightForWidth())
        self.pushButton_apply2mirror.setSizePolicy(sizePolicy)
        self.pushButton_apply2mirror.setObjectName("pushButton_apply2mirror")
        self.grid_mainbuttons.addWidget(self.pushButton_apply2mirror, 1, 1, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_reset.sizePolicy().hasHeightForWidth())
        self.pushButton_reset.setSizePolicy(sizePolicy)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.grid_mainbuttons.addWidget(self.pushButton_reset, 1, 4, 1, 1)
        self.pushButton_acquire = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_acquire.sizePolicy().hasHeightForWidth())
        self.pushButton_acquire.setSizePolicy(sizePolicy)
        self.pushButton_acquire.setObjectName("pushButton_acquire")
        self.grid_mainbuttons.addWidget(self.pushButton_acquire, 0, 0, 1, 1)
        self.pushButton_snapshot = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_snapshot.sizePolicy().hasHeightForWidth())
        self.pushButton_snapshot.setSizePolicy(sizePolicy)
        self.pushButton_snapshot.setObjectName("pushButton_snapshot")
        self.grid_mainbuttons.addWidget(self.pushButton_snapshot, 1, 0, 1, 1)
        self.tab_display = QtWidgets.QTabWidget(self.centralwidget)
        self.tab_display.setGeometry(QtCore.QRect(10, 50, 661, 381))
        self.tab_display.setObjectName("tab_display")
        self.tab_image_phase = QtWidgets.QWidget()
        self.tab_image_phase.setObjectName("tab_image_phase")
        self.mpl_image = QtWidgets.QGraphicsView(self.tab_image_phase)
        self.mpl_image.setGeometry(QtCore.QRect(10, 30, 311, 301))
        self.mpl_image.setObjectName("mpl_image")
        self.mpl_phase = QtWidgets.QGraphicsView(self.tab_image_phase)
        self.mpl_phase.setGeometry(QtCore.QRect(330, 30, 311, 301))
        self.mpl_phase.setObjectName("mpl_phase")
        self.tab_display.addTab(self.tab_image_phase, "")
        self.tab_metric = QtWidgets.QWidget()
        self.tab_metric.setObjectName("tab_metric")
        self.mpl_metrics = QtWidgets.QGraphicsView(self.tab_metric)
        self.mpl_metrics.setGeometry(QtCore.QRect(20, 41, 571, 251))
        self.mpl_metrics.setObjectName("mpl_metrics")
        self.tab_display.addTab(self.tab_metric, "")
        self.tab_zfit = QtWidgets.QWidget()
        self.tab_zfit.setObjectName("tab_zfit")
        self.tab_display.addTab(self.tab_zfit, "")
        self.table_Zcoeffs = QtWidgets.QTableWidget(self.centralwidget)
        self.table_Zcoeffs.setGeometry(QtCore.QRect(680, 40, 269, 391))
        self.table_Zcoeffs.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table_Zcoeffs.setObjectName("table_Zcoeffs")
        self.table_Zcoeffs.setColumnCount(1)
        self.table_Zcoeffs.setRowCount(22)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(16, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(17, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(18, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(19, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(20, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setVerticalHeaderItem(21, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_Zcoeffs.setItem(0, 0, item)
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(680, 440, 231, 131))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.label_zmode = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_zmode.sizePolicy().hasHeightForWidth())
        self.label_zmode.setSizePolicy(sizePolicy)
        self.label_zmode.setObjectName("label_zmode")
        self.gridLayout.addWidget(self.label_zmode, 0, 0, 1, 1)
        self.label_zamplitude = QtWidgets.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_zamplitude.sizePolicy().hasHeightForWidth())
        self.label_zamplitude.setSizePolicy(sizePolicy)
        self.label_zamplitude.setObjectName("label_zamplitude")
        self.gridLayout.addWidget(self.label_zamplitude, 0, 1, 1, 1)
        self.spinBox = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox.sizePolicy().hasHeightForWidth())
        self.spinBox.setSizePolicy(sizePolicy)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout.addWidget(self.spinBox, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 2, 1, 1, 1)
        self.gridLayoutWidget.raise_()
        self.gridLayoutWidget_2.raise_()
        self.tab_display.raise_()
        self.table_Zcoeffs.raise_()
        self.line_Filename.raise_()
        self.table_Zcoeffs.raise_()
        self.gridLayoutWidget_3.raise_()
        Form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 25))
        self.menubar.setObjectName("menubar")
        Form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form)
        self.statusbar.setObjectName("statusbar")
        Form.setStatusBar(self.statusbar)

        self.retranslateUi(Form)
        self.tab_display.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "MainWindow"))
        self.label_nsteps.setText(_translate("Form", "# of steps"))
        self.label_fname.setText(_translate("Form", "Filename"))
        self.label_stepsize.setText(_translate("Form", "dz"))
        self.label_masksize.setText(_translate("Form", "r_mask"))
        self.pushButton_synthesize.setText(_translate("Form", "Synthesize"))
        self.pushButton_clear.setText(_translate("Form", "Clear Pattern"))
        self.pushButton_apply2mirror.setText(_translate("Form", "Apply to mirror"))
        self.pushButton_reset.setText(_translate("Form", "Reset Mirror"))
        self.pushButton_acquire.setText(_translate("Form", "Acquire stack"))
        self.pushButton_snapshot.setText(_translate("Form", "Snapshot"))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_image_phase), _translate("Form", "Image and phase"))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_metric), _translate("Form", "Metric"))
        self.tab_display.setTabText(self.tab_display.indexOf(self.tab_zfit), _translate("Form", "Zernike_fit"))
        item = self.table_Zcoeffs.verticalHeaderItem(0)
        item.setText(_translate("Form", "Z4 (defocus)"))
        item = self.table_Zcoeffs.verticalHeaderItem(1)
        item.setText(_translate("Form", "Z5 (astigm. )"))
        item = self.table_Zcoeffs.verticalHeaderItem(2)
        item.setText(_translate("Form", "Z6 (astigm. )"))
        item = self.table_Zcoeffs.verticalHeaderItem(3)
        item.setText(_translate("Form", "Z7 (coma)"))
        item = self.table_Zcoeffs.verticalHeaderItem(4)
        item.setText(_translate("Form", "Z8 (coma)"))
        item = self.table_Zcoeffs.verticalHeaderItem(5)
        item.setText(_translate("Form", "Z9"))
        item = self.table_Zcoeffs.verticalHeaderItem(6)
        item.setText(_translate("Form", "Z10"))
        item = self.table_Zcoeffs.verticalHeaderItem(7)
        item.setText(_translate("Form", "Z11 (pri. spherical)"))
        item = self.table_Zcoeffs.verticalHeaderItem(8)
        item.setText(_translate("Form", "Z12"))
        item = self.table_Zcoeffs.verticalHeaderItem(9)
        item.setText(_translate("Form", "Z13"))
        item = self.table_Zcoeffs.verticalHeaderItem(10)
        item.setText(_translate("Form", "Z14"))
        item = self.table_Zcoeffs.verticalHeaderItem(11)
        item.setText(_translate("Form", "Z15"))
        item = self.table_Zcoeffs.verticalHeaderItem(12)
        item.setText(_translate("Form", "Z16"))
        item = self.table_Zcoeffs.verticalHeaderItem(13)
        item.setText(_translate("Form", "Z17"))
        item = self.table_Zcoeffs.verticalHeaderItem(14)
        item.setText(_translate("Form", "Z18"))
        item = self.table_Zcoeffs.verticalHeaderItem(15)
        item.setText(_translate("Form", "Z19"))
        item = self.table_Zcoeffs.verticalHeaderItem(16)
        item.setText(_translate("Form", "Z20"))
        item = self.table_Zcoeffs.verticalHeaderItem(17)
        item.setText(_translate("Form", "Z21"))
        item = self.table_Zcoeffs.verticalHeaderItem(18)
        item.setText(_translate("Form", "Z22"))
        item = self.table_Zcoeffs.verticalHeaderItem(19)
        item.setText(_translate("Form", "Z23"))
        item = self.table_Zcoeffs.verticalHeaderItem(20)
        item.setText(_translate("Form", "Z24"))
        item = self.table_Zcoeffs.verticalHeaderItem(21)
        item.setText(_translate("Form", "Z25"))
        item = self.table_Zcoeffs.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Amplitude"))
        __sortingEnabled = self.table_Zcoeffs.isSortingEnabled()
        self.table_Zcoeffs.setSortingEnabled(False)
        self.table_Zcoeffs.setSortingEnabled(__sortingEnabled)
        self.label_zmode.setText(_translate("Form", "Z_modes(4 -- 25)"))
        self.label_zamplitude.setText(_translate("Form", "Amplitude"))
        self.pushButton.setText(_translate("Form", "Set"))
        self.pushButton_2.setText(_translate("Form", "Flush"))

