# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orcaflash_design_simple.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(819, 743)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.tabWidget_2 = QtWidgets.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(250, 9, 531, 681))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(512, 512))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.Image = QtWidgets.QWidget()
        self.Image.setObjectName("Image")
        self.labelDisplay = QtWidgets.QLabel(self.Image)
        self.labelDisplay.setEnabled(True)
        self.labelDisplay.setGeometry(QtCore.QRect(9, 9, 512, 512))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDisplay.sizePolicy().hasHeightForWidth())
        self.labelDisplay.setSizePolicy(sizePolicy)
        self.labelDisplay.setMinimumSize(QtCore.QSize(512, 512))
        self.labelDisplay.setMaximumSize(QtCore.QSize(512, 512))
        self.labelDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.labelDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelDisplay.setText("")
        self.labelDisplay.setObjectName("labelDisplay")
        self.label_xy = QtWidgets.QLabel(self.Image)
        self.label_xy.setGeometry(QtCore.QRect(9, 527, 221, 16))
        self.label_xy.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_xy.setObjectName("label_xy")
        self.groupBox_5 = QtWidgets.QGroupBox(self.Image)
        self.groupBox_5.setGeometry(QtCore.QRect(15, 555, 501, 91))
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_5.setObjectName("groupBox_5")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_5)
        self.formLayout_2.setObjectName("formLayout_2")
        self.horizontalSlider_min = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_min.setMinimumSize(QtCore.QSize(360, 0))
        self.horizontalSlider_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_min.setObjectName("horizontalSlider_min")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_min)
        self.horizontalSlider_max = QtWidgets.QSlider(self.groupBox_5)
        self.horizontalSlider_max.setMinimumSize(QtCore.QSize(360, 0))
        self.horizontalSlider_max.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_max.setObjectName("horizontalSlider_max")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.horizontalSlider_max)
        self.label_minSlider = QtWidgets.QLabel(self.groupBox_5)
        self.label_minSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_minSlider.setObjectName("label_minSlider")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_minSlider)
        self.label_maxSlider = QtWidgets.QLabel(self.groupBox_5)
        self.label_maxSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_maxSlider.setObjectName("label_maxSlider")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_maxSlider)
        self.checkBox_lowLight = QtWidgets.QCheckBox(self.groupBox_5)
        self.checkBox_lowLight.setObjectName("checkBox_lowLight")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.checkBox_lowLight)
        self.label_xyArea_ = QtWidgets.QLabel(self.Image)
        self.label_xyArea_.setGeometry(QtCore.QRect(240, 530, 141, 16))
        self.label_xyArea_.setObjectName("label_xyArea_")
        self.label_xyArea = QtWidgets.QLabel(self.Image)
        self.label_xyArea.setGeometry(QtCore.QRect(380, 530, 141, 16))
        self.label_xyArea.setObjectName("label_xyArea")
        self.tabWidget_2.addTab(self.Image, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2.addTab(self.tab, "")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 220, 72))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_fileName = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_fileName.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_fileName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_fileName.setObjectName("lineEdit_fileName")
        self.gridLayout_4.addWidget(self.lineEdit_fileName, 1, 1, 1, 1)
        self.label_fn = QtWidgets.QLabel(self.groupBox)
        self.label_fn.setObjectName("label_fn")
        self.gridLayout_4.addWidget(self.label_fn, 1, 0, 1, 1)
        self.spinBox_fileNameIndex = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_fileNameIndex.setMaximum(999)
        self.spinBox_fileNameIndex.setObjectName("spinBox_fileNameIndex")
        self.gridLayout_4.addWidget(self.spinBox_fileNameIndex, 1, 2, 1, 1)
        self.label_currentDir = QtWidgets.QLabel(self.groupBox)
        self.label_currentDir.setObjectName("label_currentDir")
        self.gridLayout_4.addWidget(self.label_currentDir, 2, 0, 1, 3)
        self.groupBox_testing = QtWidgets.QGroupBox(Form)
        self.groupBox_testing.setEnabled(True)
        self.groupBox_testing.setGeometry(QtCore.QRect(10, 620, 191, 102))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.groupBox_testing.setFont(font)
        self.groupBox_testing.setObjectName("groupBox_testing")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_testing)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_11 = QtWidgets.QLabel(self.groupBox_testing)
        self.label_11.setObjectName("label_11")
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_testing)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_propID = QtWidgets.QLineEdit(self.groupBox_testing)
        self.lineEdit_propID.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_propID.setObjectName("lineEdit_propID")
        self.gridLayout_7.addWidget(self.lineEdit_propID, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 2, 1, 1)
        self.lineEdit_propVal = QtWidgets.QLineEdit(self.groupBox_testing)
        self.lineEdit_propVal.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_propVal.setObjectName("lineEdit_propVal")
        self.gridLayout_7.addWidget(self.lineEdit_propVal, 1, 1, 1, 1)
        self.pushButton_propSet = QtWidgets.QPushButton(self.groupBox_testing)
        self.pushButton_propSet.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_propSet.setObjectName("pushButton_propSet")
        self.gridLayout_7.addWidget(self.pushButton_propSet, 1, 2, 1, 1)
        self.label_propVal = QtWidgets.QLabel(self.groupBox_testing)
        self.label_propVal.setObjectName("label_propVal")
        self.gridLayout_7.addWidget(self.label_propVal, 2, 1, 1, 1)
        self.pushButton_propGet = QtWidgets.QPushButton(self.groupBox_testing)
        self.pushButton_propGet.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_propGet.setObjectName("pushButton_propGet")
        self.gridLayout_7.addWidget(self.pushButton_propGet, 2, 2, 1, 1)
        self.groupBox_image_property = QtWidgets.QGroupBox(Form)
        self.groupBox_image_property.setGeometry(QtCore.QRect(250, 690, 521, 40))
        self.groupBox_image_property.setObjectName("groupBox_image_property")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_image_property)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBoxAutoscale = QtWidgets.QCheckBox(self.groupBox_image_property)
        self.checkBoxAutoscale.setChecked(True)
        self.checkBoxAutoscale.setTristate(False)
        self.checkBoxAutoscale.setObjectName("checkBoxAutoscale")
        self.horizontalLayout.addWidget(self.checkBoxAutoscale)
        self.checkBox_autoscale90 = QtWidgets.QCheckBox(self.groupBox_image_property)
        self.checkBox_autoscale90.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_autoscale90.setAutoFillBackground(False)
        self.checkBox_autoscale90.setObjectName("checkBox_autoscale90")
        self.horizontalLayout.addWidget(self.checkBox_autoscale90)
        self.checkBox_showTarget = QtWidgets.QCheckBox(self.groupBox_image_property)
        self.checkBox_showTarget.setObjectName("checkBox_showTarget")
        self.horizontalLayout.addWidget(self.checkBox_showTarget)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.groupBox_filming = QtWidgets.QGroupBox(Form)
        self.groupBox_filming.setGeometry(QtCore.QRect(10, 90, 221, 141))
        self.groupBox_filming.setObjectName("groupBox_filming")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_filming)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_Record = QtWidgets.QPushButton(self.groupBox_filming)
        self.pushButton_Record.setMaximumSize(QtCore.QSize(80, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_Record.setPalette(palette)
        self.pushButton_Record.setObjectName("pushButton_Record")
        self.gridLayout_6.addWidget(self.pushButton_Record, 0, 0, 1, 1)
        self.comboBox_recordMode = QtWidgets.QComboBox(self.groupBox_filming)
        self.comboBox_recordMode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_recordMode.setObjectName("comboBox_recordMode")
        self.comboBox_recordMode.addItem("")
        self.comboBox_recordMode.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_recordMode, 0, 1, 1, 1)
        self.pushButton_stopCapture = QtWidgets.QPushButton(self.groupBox_filming)
        self.pushButton_stopCapture.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_stopCapture.setObjectName("pushButton_stopCapture")
        self.gridLayout_6.addWidget(self.pushButton_stopCapture, 2, 0, 1, 1)
        self.lineEdit_fixedLength = QtWidgets.QLineEdit(self.groupBox_filming)
        self.lineEdit_fixedLength.setEnabled(False)
        self.lineEdit_fixedLength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_fixedLength.setObjectName("lineEdit_fixedLength")
        self.gridLayout_6.addWidget(self.lineEdit_fixedLength, 1, 1, 1, 1)
        self.label_fixedLength = QtWidgets.QLabel(self.groupBox_filming)
        self.label_fixedLength.setEnabled(False)
        self.label_fixedLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fixedLength.setObjectName("label_fixedLength")
        self.gridLayout_6.addWidget(self.label_fixedLength, 1, 0, 1, 1)
        self.resetPreview_pushButton = QtWidgets.QPushButton(self.groupBox_filming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetPreview_pushButton.sizePolicy().hasHeightForWidth())
        self.resetPreview_pushButton.setSizePolicy(sizePolicy)
        self.resetPreview_pushButton.setMinimumSize(QtCore.QSize(80, 0))
        self.resetPreview_pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.resetPreview_pushButton.setObjectName("resetPreview_pushButton")
        self.gridLayout_6.addWidget(self.resetPreview_pushButton, 2, 1, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 500, 141, 116))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.labelMin = QtWidgets.QLabel(self.layoutWidget)
        self.labelMin.setObjectName("labelMin")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.labelMin)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.labelMax = QtWidgets.QLabel(self.layoutWidget)
        self.labelMax.setObjectName("labelMax")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.labelMax)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.labelMean = QtWidgets.QLabel(self.layoutWidget)
        self.labelMean.setObjectName("labelMean")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.labelMean)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.labelMedian = QtWidgets.QLabel(self.layoutWidget)
        self.labelMedian.setObjectName("labelMedian")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.labelMedian)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.labelImagesRecorded = QtWidgets.QLabel(self.layoutWidget)
        self.labelImagesRecorded.setObjectName("labelImagesRecorded")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.labelImagesRecorded)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.labelResolution = QtWidgets.QLabel(self.layoutWidget)
        self.labelResolution.setObjectName("labelResolution")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.labelResolution)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 240, 231, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tabWidget.setFont(font)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setObjectName("tabWidget")
        self.settings = QtWidgets.QWidget()
        self.settings.setEnabled(True)
        self.settings.setObjectName("settings")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 169))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settings1_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.settings1_radioButton.setObjectName("settings1_radioButton")
        self.verticalLayout_3.addWidget(self.settings1_radioButton)
        self.settings2_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.settings2_radioButton.setObjectName("settings2_radioButton")
        self.verticalLayout_3.addWidget(self.settings2_radioButton)
        self.settings3_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.settings3_radioButton.setObjectName("settings3_radioButton")
        self.verticalLayout_3.addWidget(self.settings3_radioButton)
        self.settings4_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.settings4_radioButton.setObjectName("settings4_radioButton")
        self.verticalLayout_3.addWidget(self.settings4_radioButton)
        self.settings5_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.settings5_radioButton.setObjectName("settings5_radioButton")
        self.verticalLayout_3.addWidget(self.settings5_radioButton)
        self.settings6_radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.settings6_radioButton.setObjectName("settings6_radioButton")
        self.verticalLayout_3.addWidget(self.settings6_radioButton)
        self.pushButton_printCamProps = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_printCamProps.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_printCamProps.setObjectName("pushButton_printCamProps")
        self.verticalLayout_3.addWidget(self.pushButton_printCamProps)
        spacerItem2 = QtWidgets.QSpacerItem(50, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.settings, "")
        self.Timing = QtWidgets.QWidget()
        self.Timing.setEnabled(True)
        self.Timing.setObjectName("Timing")
        self.gridLayout = QtWidgets.QGridLayout(self.Timing)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.Timing)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_ExposureTime = QtWidgets.QLineEdit(self.Timing)
        self.lineEdit_ExposureTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_ExposureTime.setObjectName("lineEdit_ExposureTime")
        self.gridLayout.addWidget(self.lineEdit_ExposureTime, 1, 0, 1, 1)
        self.pushButton_SetTimings = QtWidgets.QPushButton(self.Timing)
        self.pushButton_SetTimings.setObjectName("pushButton_SetTimings")
        self.gridLayout.addWidget(self.pushButton_SetTimings, 6, 0, 1, 1)
        self.comboBox_expunits = QtWidgets.QComboBox(self.Timing)
        self.comboBox_expunits.setEditable(False)
        self.comboBox_expunits.setMinimumContentsLength(0)
        self.comboBox_expunits.setObjectName("comboBox_expunits")
        self.gridLayout.addWidget(self.comboBox_expunits, 1, 1, 1, 1)
        self.labelExposure = QtWidgets.QLabel(self.Timing)
        self.labelExposure.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelExposure.setObjectName("labelExposure")
        self.gridLayout.addWidget(self.labelExposure, 2, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.Timing)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.pushButton_5hz = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_5hz.setObjectName("pushButton_5hz")
        self.gridLayout_5.addWidget(self.pushButton_5hz, 0, 0, 1, 1)
        self.pushButton_10hz = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_10hz.setObjectName("pushButton_10hz")
        self.gridLayout_5.addWidget(self.pushButton_10hz, 0, 1, 1, 1)
        self.pushButton_20hz = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_20hz.setObjectName("pushButton_20hz")
        self.gridLayout_5.addWidget(self.pushButton_20hz, 1, 0, 1, 1)
        self.pushButton_60hz = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_60hz.setObjectName("pushButton_60hz")
        self.gridLayout_5.addWidget(self.pushButton_60hz, 1, 1, 1, 1)
        self.pushButton_100hz = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_100hz.setObjectName("pushButton_100hz")
        self.gridLayout_5.addWidget(self.pushButton_100hz, 2, 0, 1, 1)
        self.pushButton_120hz = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_120hz.setObjectName("pushButton_120hz")
        self.gridLayout_5.addWidget(self.pushButton_120hz, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 0, 1, 2)
        self.tabWidget.addTab(self.Timing, "")
        self.Size = QtWidgets.QWidget()
        self.Size.setObjectName("Size")
        self.label_16 = QtWidgets.QLabel(self.Size)
        self.label_16.setGeometry(QtCore.QRect(10, 61, 51, 16))
        self.label_16.setObjectName("label_16")
        self.x0_lineEdit = QtWidgets.QLineEdit(self.Size)
        self.x0_lineEdit.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.x0_lineEdit.setObjectName("x0_lineEdit")
        self.y0_lineEdit = QtWidgets.QLineEdit(self.Size)
        self.y0_lineEdit.setGeometry(QtCore.QRect(120, 60, 31, 20))
        self.y0_lineEdit.setObjectName("y0_lineEdit")
        self.widget = QtWidgets.QWidget(self.Size)
        self.widget.setGeometry(QtCore.QRect(9, 0, 211, 51))
        self.widget.setObjectName("widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_8 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.x0_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.x0_label.setFont(font)
        self.x0_label.setObjectName("x0_label")
        self.gridLayout_3.addWidget(self.x0_label, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.y0_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.y0_label.setFont(font)
        self.y0_label.setObjectName("y0_label")
        self.gridLayout_3.addWidget(self.y0_label, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.xres_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.xres_label.setFont(font)
        self.xres_label.setObjectName("xres_label")
        self.gridLayout_3.addWidget(self.xres_label, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 2, 1, 1)
        self.yres_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.yres_label.setFont(font)
        self.yres_label.setObjectName("yres_label")
        self.gridLayout_3.addWidget(self.yres_label, 1, 3, 1, 1)
        self.xres_lineEdit = QtWidgets.QLineEdit(self.Size)
        self.xres_lineEdit.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.xres_lineEdit.setObjectName("xres_lineEdit")
        self.label_17 = QtWidgets.QLabel(self.Size)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_17.setObjectName("label_17")
        self.yres_lineEdit = QtWidgets.QLineEdit(self.Size)
        self.yres_lineEdit.setGeometry(QtCore.QRect(120, 80, 31, 20))
        self.yres_lineEdit.setObjectName("yres_lineEdit")
        self.setROI_pushButton = QtWidgets.QPushButton(self.Size)
        self.setROI_pushButton.setGeometry(QtCore.QRect(170, 60, 51, 41))
        self.setROI_pushButton.setObjectName("setROI_pushButton")
        self.labelROIDisplay = QtWidgets.QLabel(self.Size)
        self.labelROIDisplay.setGeometry(QtCore.QRect(100, 120, 111, 111))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelROIDisplay.sizePolicy().hasHeightForWidth())
        self.labelROIDisplay.setSizePolicy(sizePolicy)
        self.labelROIDisplay.setFrameShape(QtWidgets.QFrame.Box)
        self.labelROIDisplay.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.labelROIDisplay.setText("")
        self.labelROIDisplay.setObjectName("labelROIDisplay")
        self.radioButton_2x2Binning = QtWidgets.QRadioButton(self.Size)
        self.radioButton_2x2Binning.setGeometry(QtCore.QRect(0, 190, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_2x2Binning.setFont(font)
        self.radioButton_2x2Binning.setObjectName("radioButton_2x2Binning")
        self.radioButton_4x4Binning = QtWidgets.QRadioButton(self.Size)
        self.radioButton_4x4Binning.setGeometry(QtCore.QRect(0, 210, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_4x4Binning.setFont(font)
        self.radioButton_4x4Binning.setObjectName("radioButton_4x4Binning")
        self.radioButton_noBinning = QtWidgets.QRadioButton(self.Size)
        self.radioButton_noBinning.setGeometry(QtCore.QRect(0, 170, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_noBinning.setFont(font)
        self.radioButton_noBinning.setObjectName("radioButton_noBinning")
        self.pushButton_roi256256 = QtWidgets.QPushButton(self.Size)
        self.pushButton_roi256256.setGeometry(QtCore.QRect(50, 110, 41, 23))
        self.pushButton_roi256256.setObjectName("pushButton_roi256256")
        self.pushButton_roi512256 = QtWidgets.QPushButton(self.Size)
        self.pushButton_roi512256.setGeometry(QtCore.QRect(0, 140, 41, 23))
        self.pushButton_roi512256.setObjectName("pushButton_roi512256")
        self.pushButton_roi128128 = QtWidgets.QPushButton(self.Size)
        self.pushButton_roi128128.setGeometry(QtCore.QRect(0, 110, 41, 23))
        self.pushButton_roi128128.setObjectName("pushButton_roi128128")
        self.pushButton_roi512512 = QtWidgets.QPushButton(self.Size)
        self.pushButton_roi512512.setGeometry(QtCore.QRect(50, 140, 41, 23))
        self.pushButton_roi512512.setObjectName("pushButton_roi512512")
        self.tabWidget.addTab(self.Size, "")
        self.etc = QtWidgets.QWidget()
        self.etc.setObjectName("etc")
        self.groupBox1 = QtWidgets.QGroupBox(self.etc)
        self.groupBox1.setGeometry(QtCore.QRect(0, 10, 221, 111))
        self.groupBox1.setObjectName("groupBox1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_beginSnaps = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_beginSnaps.setObjectName("pushButton_beginSnaps")
        self.gridLayout_2.addWidget(self.pushButton_beginSnaps, 0, 0, 1, 1)
        self.pushButton_takeSnap = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_takeSnap.setObjectName("pushButton_takeSnap")
        self.gridLayout_2.addWidget(self.pushButton_takeSnap, 1, 0, 1, 1)
        self.pushButton_doneSnaps = QtWidgets.QPushButton(self.groupBox1)
        self.pushButton_doneSnaps.setObjectName("pushButton_doneSnaps")
        self.gridLayout_2.addWidget(self.pushButton_doneSnaps, 2, 0, 1, 1)
        self.pushButton_SaveFrame = QtWidgets.QPushButton(self.etc)
        self.pushButton_SaveFrame.setGeometry(QtCore.QRect(10, 210, 187, 15))
        self.pushButton_SaveFrame.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_SaveFrame.setFont(font)
        self.pushButton_SaveFrame.setAutoDefault(False)
        self.pushButton_SaveFrame.setDefault(False)
        self.pushButton_SaveFrame.setFlat(False)
        self.pushButton_SaveFrame.setObjectName("pushButton_SaveFrame")
        self.label_7 = QtWidgets.QLabel(self.etc)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 101, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_toDiskTime = QtWidgets.QLineEdit(self.etc)
        self.lineEdit_toDiskTime.setGeometry(QtCore.QRect(110, 160, 71, 20))
        self.lineEdit_toDiskTime.setObjectName("lineEdit_toDiskTime")
        self.checkBox_autoUpdateTime = QtWidgets.QCheckBox(self.etc)
        self.checkBox_autoUpdateTime.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.checkBox_autoUpdateTime.setChecked(True)
        self.checkBox_autoUpdateTime.setTristate(False)
        self.checkBox_autoUpdateTime.setObjectName("checkBox_autoUpdateTime")
        self.checkBox_defectMode = QtWidgets.QCheckBox(self.etc)
        self.checkBox_defectMode.setGeometry(QtCore.QRect(10, 190, 191, 17))
        self.checkBox_defectMode.setChecked(True)
        self.checkBox_defectMode.setObjectName("checkBox_defectMode")
        self.label_15 = QtWidgets.QLabel(self.etc)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 46, 13))
        self.label_15.setObjectName("label_15")
        self.triggerMode_lineEdit = QtWidgets.QLineEdit(self.etc)
        self.triggerMode_lineEdit.setGeometry(QtCore.QRect(60, 130, 31, 16))
        self.triggerMode_lineEdit.setObjectName("triggerMode_lineEdit")
        self.comboBox_triggermodes = QtWidgets.QComboBox(self.etc)
        self.comboBox_triggermodes.setGeometry(QtCore.QRect(90, 130, 69, 22))
        self.comboBox_triggermodes.setObjectName("comboBox_triggermodes")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.comboBox_triggermodes.addItem("")
        self.pushButton_triggermodes = QtWidgets.QPushButton(self.etc)
        self.pushButton_triggermodes.setGeometry(QtCore.QRect(160, 130, 41, 23))
        self.pushButton_triggermodes.setObjectName("pushButton_triggermodes")
        self.tabWidget.addTab(self.etc, "")

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        self.comboBox_expunits.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Camera"))
        self.label_xy.setText(_translate("Form", "x, y: "))
        self.groupBox_5.setTitle(_translate("Form", "Min/Max"))
        self.label_minSlider.setText(_translate("Form", "Min: "))
        self.label_maxSlider.setText(_translate("Form", "Max: "))
        self.checkBox_lowLight.setText(_translate("Form", "Low light limit?"))
        self.label_xyArea_.setText(_translate("Form", "Max in 10x10 around (x,y): "))
        self.label_xyArea.setText(_translate("Form", "---"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Image), _translate("Form", "Image"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), _translate("Form", "Plot"))
        self.groupBox.setTitle(_translate("Form", "Data saving settings:"))
        self.label_fn.setText(_translate("Form", "Filename:"))
        self.label_currentDir.setText(_translate("Form", "--"))
        self.groupBox_testing.setTitle(_translate("Form", "For Testing/Debugging"))
        self.label_11.setText(_translate("Form", "Property ID:"))
        self.label_14.setText(_translate("Form", "Value:"))
        self.pushButton_propSet.setText(_translate("Form", "SET"))
        self.label_propVal.setText(_translate("Form", "--"))
        self.pushButton_propGet.setText(_translate("Form", "GET"))
        self.checkBoxAutoscale.setText(_translate("Form", "Autoscale..."))
        self.checkBox_autoscale90.setText(_translate("Form", "...to 75% of max"))
        self.checkBox_showTarget.setText(_translate("Form", "Show Target"))
        self.groupBox_filming.setTitle(_translate("Form", "Filming"))
        self.pushButton_Record.setText(_translate("Form", "Record"))
        self.comboBox_recordMode.setItemText(0, _translate("Form", "Run until abort"))
        self.comboBox_recordMode.setItemText(1, _translate("Form", "Fixed length"))
        self.pushButton_stopCapture.setText(_translate("Form", "Disable Camera"))
        self.label_fixedLength.setText(_translate("Form", "Fixed length:"))
        self.resetPreview_pushButton.setText(_translate("Form", "Reset Preview"))
        self.label_2.setText(_translate("Form", "Min:"))
        self.labelMin.setText(_translate("Form", "-"))
        self.label.setText(_translate("Form", "Max:"))
        self.labelMax.setText(_translate("Form", "-"))
        self.label_4.setText(_translate("Form", "Mean:"))
        self.labelMean.setText(_translate("Form", "-"))
        self.label_3.setText(_translate("Form", "Median:"))
        self.labelMedian.setText(_translate("Form", "-"))
        self.label_5.setText(_translate("Form", "Images: "))
        self.labelImagesRecorded.setText(_translate("Form", "-"))
        self.label_9.setText(_translate("Form", "Resolution:"))
        self.labelResolution.setText(_translate("Form", "-"))
        self.settings1_radioButton.setText(_translate("Form", "settings1"))
        self.settings2_radioButton.setText(_translate("Form", "settings2"))
        self.settings3_radioButton.setText(_translate("Form", "settings3"))
        self.settings4_radioButton.setText(_translate("Form", "settings4"))
        self.settings5_radioButton.setText(_translate("Form", "settings5"))
        self.settings6_radioButton.setText(_translate("Form", "settings6"))
        self.pushButton_printCamProps.setText(_translate("Form", "Print Camera Properties"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), _translate("Form", "Settings"))
        self.label_6.setText(_translate("Form", "Exposure time:"))
        self.pushButton_SetTimings.setText(_translate("Form", "Set Timings"))
        self.labelExposure.setText(_translate("Form", "Actual: --"))
        self.groupBox_4.setTitle(_translate("Form", "Common Settings"))
        self.pushButton_5hz.setText(_translate("Form", "5 Hz"))
        self.pushButton_10hz.setText(_translate("Form", "10 Hz"))
        self.pushButton_20hz.setText(_translate("Form", "20 Hz"))
        self.pushButton_60hz.setText(_translate("Form", "60 Hz"))
        self.pushButton_100hz.setText(_translate("Form", "100 Hz"))
        self.pushButton_120hz.setText(_translate("Form", "120 Hz"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timing), _translate("Form", "Timing"))
        self.label_16.setText(_translate("Form", "x0, y0:"))
        self.label_8.setText(_translate("Form", "x0: "))
        self.x0_label.setText(_translate("Form", "----"))
        self.label_10.setText(_translate("Form", "y0:"))
        self.y0_label.setText(_translate("Form", "----"))
        self.label_12.setText(_translate("Form", "x dimension:"))
        self.xres_label.setText(_translate("Form", "----"))
        self.label_13.setText(_translate("Form", "y dimension:"))
        self.yres_label.setText(_translate("Form", "----"))
        self.label_17.setText(_translate("Form", "xsize, ysize:"))
        self.setROI_pushButton.setText(_translate("Form", "Set ROI"))
        self.radioButton_2x2Binning.setText(_translate("Form", "2x2"))
        self.radioButton_4x4Binning.setText(_translate("Form", "4x4"))
        self.radioButton_noBinning.setText(_translate("Form", "No Binning"))
        self.pushButton_roi256256.setText(_translate("Form", "256x256"))
        self.pushButton_roi512256.setText(_translate("Form", "512x256"))
        self.pushButton_roi128128.setText(_translate("Form", "128x128"))
        self.pushButton_roi512512.setText(_translate("Form", "512x512"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Size), _translate("Form", "Size"))
        self.groupBox1.setTitle(_translate("Form", "For taking series of snap shots (useful for 2 channel...)"))
        self.pushButton_beginSnaps.setText(_translate("Form", "Begin Snaps"))
        self.pushButton_takeSnap.setText(_translate("Form", "Take Snap Shot"))
        self.pushButton_doneSnaps.setText(_translate("Form", "Done"))
        self.pushButton_SaveFrame.setText(_translate("Form", "Save Frame (as npy array)"))
        self.label_7.setText(_translate("Form", "To-Disk Update Time (ms):"))
        self.lineEdit_toDiskTime.setText(_translate("Form", "200"))
        self.checkBox_autoUpdateTime.setText(_translate("Form", "Auto update time"))
        self.checkBox_defectMode.setText(_translate("Form", "Defect Correct Mode"))
        self.label_15.setText(_translate("Form", "Trigger Mode:"))
        self.comboBox_triggermodes.setItemText(0, _translate("Form", "Internal"))
        self.comboBox_triggermodes.setItemText(1, _translate("Form", "Edge"))
        self.comboBox_triggermodes.setItemText(2, _translate("Form", "Level"))
        self.comboBox_triggermodes.setItemText(3, _translate("Form", "Multishot"))
        self.comboBox_triggermodes.setItemText(4, _translate("Form", "CycleDelay"))
        self.comboBox_triggermodes.setItemText(5, _translate("Form", "Software"))
        self.comboBox_triggermodes.setItemText(6, _translate("Form", "Fastrep"))
        self.comboBox_triggermodes.setItemText(7, _translate("Form", "TDI"))
        self.comboBox_triggermodes.setItemText(8, _translate("Form", "TDI_Internal"))
        self.comboBox_triggermodes.setItemText(9, _translate("Form", "Start"))
        self.comboBox_triggermodes.setItemText(10, _translate("Form", "SyncReadout"))
        self.pushButton_triggermodes.setText(_translate("Form", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.etc), _translate("Form", "Etc."))

