# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'orcaflash_design.ui'
#
# Created: Wed Mar 25 11:47:08 2015
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(819, 743)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2 = QtGui.QTabWidget(Form)
        self.tabWidget_2.setGeometry(QtCore.QRect(250, 9, 531, 681))
        self.tabWidget_2.setMinimumSize(QtCore.QSize(512, 512))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.Image = QtGui.QWidget()
        self.Image.setObjectName(_fromUtf8("Image"))
        self.labelDisplay = QtGui.QLabel(self.Image)
        self.labelDisplay.setEnabled(True)
        self.labelDisplay.setGeometry(QtCore.QRect(9, 9, 512, 512))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelDisplay.sizePolicy().hasHeightForWidth())
        self.labelDisplay.setSizePolicy(sizePolicy)
        self.labelDisplay.setMinimumSize(QtCore.QSize(512, 512))
        self.labelDisplay.setMaximumSize(QtCore.QSize(512, 512))
        self.labelDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelDisplay.setText(_fromUtf8(""))
        self.labelDisplay.setObjectName(_fromUtf8("labelDisplay"))
        self.label_xy = QtGui.QLabel(self.Image)
        self.label_xy.setGeometry(QtCore.QRect(9, 527, 221, 16))
        self.label_xy.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_xy.setText(QtGui.QApplication.translate("Form", "x, y: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_xy.setObjectName(_fromUtf8("label_xy"))
        self.groupBox_5 = QtGui.QGroupBox(self.Image)
        self.groupBox_5.setGeometry(QtCore.QRect(15, 555, 501, 91))
        self.groupBox_5.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Min/Max", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox_5)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalSlider_min = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_min.setMinimumSize(QtCore.QSize(360, 0))
        self.horizontalSlider_min.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_min.setObjectName(_fromUtf8("horizontalSlider_min"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.horizontalSlider_min)
        self.horizontalSlider_max = QtGui.QSlider(self.groupBox_5)
        self.horizontalSlider_max.setMinimumSize(QtCore.QSize(360, 0))
        self.horizontalSlider_max.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_max.setObjectName(_fromUtf8("horizontalSlider_max"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.horizontalSlider_max)
        self.label_minSlider = QtGui.QLabel(self.groupBox_5)
        self.label_minSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_minSlider.setText(QtGui.QApplication.translate("Form", "Min: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_minSlider.setObjectName(_fromUtf8("label_minSlider"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.label_minSlider)
        self.label_maxSlider = QtGui.QLabel(self.groupBox_5)
        self.label_maxSlider.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_maxSlider.setText(QtGui.QApplication.translate("Form", "Max: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_maxSlider.setObjectName(_fromUtf8("label_maxSlider"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.label_maxSlider)
        self.checkBox_lowLight = QtGui.QCheckBox(self.groupBox_5)
        self.checkBox_lowLight.setText(QtGui.QApplication.translate("Form", "Low light limit?", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_lowLight.setObjectName(_fromUtf8("checkBox_lowLight"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.checkBox_lowLight)
        self.label_xyArea_ = QtGui.QLabel(self.Image)
        self.label_xyArea_.setGeometry(QtCore.QRect(240, 530, 141, 16))
        self.label_xyArea_.setText(QtGui.QApplication.translate("Form", "Max in 10x10 around (x,y): ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_xyArea_.setObjectName(_fromUtf8("label_xyArea_"))
        self.label_xyArea = QtGui.QLabel(self.Image)
        self.label_xyArea.setGeometry(QtCore.QRect(380, 530, 141, 16))
        self.label_xyArea.setText(QtGui.QApplication.translate("Form", "---", None, QtGui.QApplication.UnicodeUTF8))
        self.label_xyArea.setObjectName(_fromUtf8("label_xyArea"))
        self.tabWidget_2.addTab(self.Image, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.qwtPlot = Qwt5.QwtPlot(self.tab)
        self.qwtPlot.setGeometry(QtCore.QRect(10, 160, 501, 191))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 20, 491, 81))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Plot Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.radioButton_plotHor = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_plotHor.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.radioButton_plotHor.setText(QtGui.QApplication.translate("Form", "Horizontal line", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_plotHor.setObjectName(_fromUtf8("radioButton_plotHor"))
        self.radioButton_plotVert = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_plotVert.setGeometry(QtCore.QRect(20, 40, 82, 17))
        self.radioButton_plotVert.setText(QtGui.QApplication.translate("Form", "Vertical line", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_plotVert.setObjectName(_fromUtf8("radioButton_plotVert"))
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setGeometry(QtCore.QRect(300, 20, 46, 13))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.label_19 = QtGui.QLabel(self.groupBox_6)
        self.label_19.setGeometry(QtCore.QRect(300, 50, 46, 13))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_plotWidth = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_plotWidth.setGeometry(QtCore.QRect(350, 20, 113, 20))
        self.lineEdit_plotWidth.setObjectName(_fromUtf8("lineEdit_plotWidth"))
        self.lineEdit_plotLength = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_plotLength.setGeometry(QtCore.QRect(350, 50, 113, 20))
        self.lineEdit_plotLength.setObjectName(_fromUtf8("lineEdit_plotLength"))
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(140, 20, 46, 13))
        self.label_20.setText(QtGui.QApplication.translate("Form", "X, Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_xForPlot = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_xForPlot.setGeometry(QtCore.QRect(170, 20, 31, 20))
        self.lineEdit_xForPlot.setObjectName(_fromUtf8("lineEdit_xForPlot"))
        self.lineEdit_yForPlot = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_yForPlot.setGeometry(QtCore.QRect(210, 20, 31, 20))
        self.lineEdit_yForPlot.setObjectName(_fromUtf8("lineEdit_yForPlot"))
        self.checkBox_sharpness = QtGui.QCheckBox(self.tab)
        self.checkBox_sharpness.setGeometry(QtCore.QRect(30, 110, 70, 17))
        self.checkBox_sharpness.setText(QtGui.QApplication.translate("Form", "Sharpness", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_sharpness.setObjectName(_fromUtf8("checkBox_sharpness"))
        self.tabWidget_2.addTab(self.tab, _fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 220, 72))
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Data saving settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lineEdit_fileName = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_fileName.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_fileName.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_fileName.setObjectName(_fromUtf8("lineEdit_fileName"))
        self.gridLayout_4.addWidget(self.lineEdit_fileName, 1, 1, 1, 1)
        self.label_fn = QtGui.QLabel(self.groupBox)
        self.label_fn.setText(QtGui.QApplication.translate("Form", "Filename:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fn.setObjectName(_fromUtf8("label_fn"))
        self.gridLayout_4.addWidget(self.label_fn, 1, 0, 1, 1)
        self.spinBox_fileNameIndex = QtGui.QSpinBox(self.groupBox)
        self.spinBox_fileNameIndex.setMaximum(999)
        self.spinBox_fileNameIndex.setObjectName(_fromUtf8("spinBox_fileNameIndex"))
        self.gridLayout_4.addWidget(self.spinBox_fileNameIndex, 1, 2, 1, 1)
        self.label_currentDir = QtGui.QLabel(self.groupBox)
        self.label_currentDir.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_currentDir.setObjectName(_fromUtf8("label_currentDir"))
        self.gridLayout_4.addWidget(self.label_currentDir, 2, 0, 1, 3)
        self.groupBox_testing = QtGui.QGroupBox(Form)
        self.groupBox_testing.setEnabled(True)
        self.groupBox_testing.setGeometry(QtCore.QRect(10, 620, 191, 102))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.groupBox_testing.setFont(font)
        self.groupBox_testing.setTitle(QtGui.QApplication.translate("Form", "For Testing/Debugging", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_testing.setObjectName(_fromUtf8("groupBox_testing"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_testing)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_11 = QtGui.QLabel(self.groupBox_testing)
        self.label_11.setText(QtGui.QApplication.translate("Form", "Property ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_testing)
        self.label_14.setText(QtGui.QApplication.translate("Form", "Value:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 1, 0, 1, 1)
        self.lineEdit_propID = QtGui.QLineEdit(self.groupBox_testing)
        self.lineEdit_propID.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_propID.setObjectName(_fromUtf8("lineEdit_propID"))
        self.gridLayout_7.addWidget(self.lineEdit_propID, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem, 0, 2, 1, 1)
        self.lineEdit_propVal = QtGui.QLineEdit(self.groupBox_testing)
        self.lineEdit_propVal.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_propVal.setObjectName(_fromUtf8("lineEdit_propVal"))
        self.gridLayout_7.addWidget(self.lineEdit_propVal, 1, 1, 1, 1)
        self.pushButton_propSet = QtGui.QPushButton(self.groupBox_testing)
        self.pushButton_propSet.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_propSet.setText(QtGui.QApplication.translate("Form", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_propSet.setObjectName(_fromUtf8("pushButton_propSet"))
        self.gridLayout_7.addWidget(self.pushButton_propSet, 1, 2, 1, 1)
        self.label_propVal = QtGui.QLabel(self.groupBox_testing)
        self.label_propVal.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_propVal.setObjectName(_fromUtf8("label_propVal"))
        self.gridLayout_7.addWidget(self.label_propVal, 2, 1, 1, 1)
        self.pushButton_propGet = QtGui.QPushButton(self.groupBox_testing)
        self.pushButton_propGet.setMaximumSize(QtCore.QSize(40, 20))
        self.pushButton_propGet.setText(QtGui.QApplication.translate("Form", "GET", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_propGet.setObjectName(_fromUtf8("pushButton_propGet"))
        self.gridLayout_7.addWidget(self.pushButton_propGet, 2, 2, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(250, 690, 521, 40))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBoxAutoscale = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxAutoscale.setText(QtGui.QApplication.translate("Form", "Autoscale...", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxAutoscale.setChecked(True)
        self.checkBoxAutoscale.setTristate(False)
        self.checkBoxAutoscale.setObjectName(_fromUtf8("checkBoxAutoscale"))
        self.horizontalLayout.addWidget(self.checkBoxAutoscale)
        self.checkBox_autoscale90 = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_autoscale90.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBox_autoscale90.setAutoFillBackground(False)
        self.checkBox_autoscale90.setText(QtGui.QApplication.translate("Form", "...to 75% of max", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_autoscale90.setObjectName(_fromUtf8("checkBox_autoscale90"))
        self.horizontalLayout.addWidget(self.checkBox_autoscale90)
        self.checkBox_showTarget = QtGui.QCheckBox(self.groupBox_2)
        self.checkBox_showTarget.setText(QtGui.QApplication.translate("Form", "Show Target", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_showTarget.setObjectName(_fromUtf8("checkBox_showTarget"))
        self.horizontalLayout.addWidget(self.checkBox_showTarget)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 90, 221, 141))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Filming", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.pushButton_Record = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_Record.setMaximumSize(QtCore.QSize(80, 16777215))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.pushButton_Record.setPalette(palette)
        self.pushButton_Record.setText(QtGui.QApplication.translate("Form", "Record", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Record.setObjectName(_fromUtf8("pushButton_Record"))
        self.gridLayout_6.addWidget(self.pushButton_Record, 0, 0, 1, 1)
        self.comboBox_recordMode = QtGui.QComboBox(self.groupBox_3)
        self.comboBox_recordMode.setMaximumSize(QtCore.QSize(100, 16777215))
        self.comboBox_recordMode.setObjectName(_fromUtf8("comboBox_recordMode"))
        self.comboBox_recordMode.addItem(_fromUtf8(""))
        self.comboBox_recordMode.setItemText(0, QtGui.QApplication.translate("Form", "Run until abort", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_recordMode.addItem(_fromUtf8(""))
        self.comboBox_recordMode.setItemText(1, QtGui.QApplication.translate("Form", "Fixed length", None, QtGui.QApplication.UnicodeUTF8))
        self.gridLayout_6.addWidget(self.comboBox_recordMode, 0, 1, 1, 1)
        self.pushButton_stopCapture = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_stopCapture.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_stopCapture.setText(QtGui.QApplication.translate("Form", "Disable Camera", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_stopCapture.setObjectName(_fromUtf8("pushButton_stopCapture"))
        self.gridLayout_6.addWidget(self.pushButton_stopCapture, 2, 0, 1, 1)
        self.lineEdit_fixedLength = QtGui.QLineEdit(self.groupBox_3)
        self.lineEdit_fixedLength.setEnabled(False)
        self.lineEdit_fixedLength.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_fixedLength.setObjectName(_fromUtf8("lineEdit_fixedLength"))
        self.gridLayout_6.addWidget(self.lineEdit_fixedLength, 1, 1, 1, 1)
        self.label_fixedLength = QtGui.QLabel(self.groupBox_3)
        self.label_fixedLength.setEnabled(False)
        self.label_fixedLength.setText(QtGui.QApplication.translate("Form", "Fixed length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_fixedLength.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_fixedLength.setObjectName(_fromUtf8("label_fixedLength"))
        self.gridLayout_6.addWidget(self.label_fixedLength, 1, 0, 1, 1)
        self.resetPreview_pushButton = QtGui.QPushButton(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resetPreview_pushButton.sizePolicy().hasHeightForWidth())
        self.resetPreview_pushButton.setSizePolicy(sizePolicy)
        self.resetPreview_pushButton.setMinimumSize(QtCore.QSize(80, 0))
        self.resetPreview_pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.resetPreview_pushButton.setText(QtGui.QApplication.translate("Form", "Reset Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.resetPreview_pushButton.setObjectName(_fromUtf8("resetPreview_pushButton"))
        self.gridLayout_6.addWidget(self.resetPreview_pushButton, 2, 1, 1, 1)
        self.layoutWidget = QtGui.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 500, 141, 116))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Min:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.labelMin = QtGui.QLabel(self.layoutWidget)
        self.labelMin.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMin.setObjectName(_fromUtf8("labelMin"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.labelMin)
        self.label = QtGui.QLabel(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText(QtGui.QApplication.translate("Form", "Max:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label)
        self.labelMax = QtGui.QLabel(self.layoutWidget)
        self.labelMax.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMax.setObjectName(_fromUtf8("labelMax"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.labelMax)
        self.label_4 = QtGui.QLabel(self.layoutWidget)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Mean:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.labelMean = QtGui.QLabel(self.layoutWidget)
        self.labelMean.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMean.setObjectName(_fromUtf8("labelMean"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.labelMean)
        self.label_3 = QtGui.QLabel(self.layoutWidget)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Median:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.labelMedian = QtGui.QLabel(self.layoutWidget)
        self.labelMedian.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelMedian.setObjectName(_fromUtf8("labelMedian"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.labelMedian)
        self.label_5 = QtGui.QLabel(self.layoutWidget)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Images: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_5)
        self.labelImagesRecorded = QtGui.QLabel(self.layoutWidget)
        self.labelImagesRecorded.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelImagesRecorded.setObjectName(_fromUtf8("labelImagesRecorded"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.labelImagesRecorded)
        self.label_9 = QtGui.QLabel(self.layoutWidget)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Resolution:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_9)
        self.labelResolution = QtGui.QLabel(self.layoutWidget)
        self.labelResolution.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelResolution.setObjectName(_fromUtf8("labelResolution"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.labelResolution)
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(10, 240, 231, 251))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.tabWidget.setFont(font)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.settings = QtGui.QWidget()
        self.settings.setEnabled(True)
        self.settings.setObjectName(_fromUtf8("settings"))
        self.verticalLayoutWidget = QtGui.QWidget(self.settings)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 171, 169))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.settings1_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings1_radioButton.setText(QtGui.QApplication.translate("Form", "settings1", None, QtGui.QApplication.UnicodeUTF8))
        self.settings1_radioButton.setObjectName(_fromUtf8("settings1_radioButton"))
        self.verticalLayout_3.addWidget(self.settings1_radioButton)
        self.settings2_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings2_radioButton.setText(QtGui.QApplication.translate("Form", "settings2", None, QtGui.QApplication.UnicodeUTF8))
        self.settings2_radioButton.setObjectName(_fromUtf8("settings2_radioButton"))
        self.verticalLayout_3.addWidget(self.settings2_radioButton)
        self.settings3_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings3_radioButton.setText(QtGui.QApplication.translate("Form", "settings3", None, QtGui.QApplication.UnicodeUTF8))
        self.settings3_radioButton.setObjectName(_fromUtf8("settings3_radioButton"))
        self.verticalLayout_3.addWidget(self.settings3_radioButton)
        self.settings4_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings4_radioButton.setText(QtGui.QApplication.translate("Form", "settings4", None, QtGui.QApplication.UnicodeUTF8))
        self.settings4_radioButton.setObjectName(_fromUtf8("settings4_radioButton"))
        self.verticalLayout_3.addWidget(self.settings4_radioButton)
        self.settings5_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings5_radioButton.setText(QtGui.QApplication.translate("Form", "settings5", None, QtGui.QApplication.UnicodeUTF8))
        self.settings5_radioButton.setObjectName(_fromUtf8("settings5_radioButton"))
        self.verticalLayout_3.addWidget(self.settings5_radioButton)
        self.settings6_radioButton = QtGui.QRadioButton(self.verticalLayoutWidget)
        self.settings6_radioButton.setText(QtGui.QApplication.translate("Form", "settings6", None, QtGui.QApplication.UnicodeUTF8))
        self.settings6_radioButton.setObjectName(_fromUtf8("settings6_radioButton"))
        self.verticalLayout_3.addWidget(self.settings6_radioButton)
        self.pushButton_printCamProps = QtGui.QPushButton(self.verticalLayoutWidget)
        self.pushButton_printCamProps.setMaximumSize(QtCore.QSize(140, 16777215))
        self.pushButton_printCamProps.setText(QtGui.QApplication.translate("Form", "Print Camera Properties", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_printCamProps.setObjectName(_fromUtf8("pushButton_printCamProps"))
        self.verticalLayout_3.addWidget(self.pushButton_printCamProps)
        spacerItem2 = QtGui.QSpacerItem(50, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.tabWidget.addTab(self.settings, _fromUtf8(""))
        self.Timing = QtGui.QWidget()
        self.Timing.setEnabled(True)
        self.Timing.setObjectName(_fromUtf8("Timing"))
        self.gridLayout = QtGui.QGridLayout(self.Timing)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_6 = QtGui.QLabel(self.Timing)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_6.setText(QtGui.QApplication.translate("Form", "Exposure time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_ExposureTime = QtGui.QLineEdit(self.Timing)
        self.lineEdit_ExposureTime.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_ExposureTime.setObjectName(_fromUtf8("lineEdit_ExposureTime"))
        self.gridLayout.addWidget(self.lineEdit_ExposureTime, 1, 0, 1, 1)
        self.pushButton_SetTimings = QtGui.QPushButton(self.Timing)
        self.pushButton_SetTimings.setText(QtGui.QApplication.translate("Form", "Set Timings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SetTimings.setObjectName(_fromUtf8("pushButton_SetTimings"))
        self.gridLayout.addWidget(self.pushButton_SetTimings, 6, 0, 1, 1)
        self.comboBox_expunits = QtGui.QComboBox(self.Timing)
        self.comboBox_expunits.setEditable(False)
        self.comboBox_expunits.setMinimumContentsLength(0)
        self.comboBox_expunits.setObjectName(_fromUtf8("comboBox_expunits"))
        self.gridLayout.addWidget(self.comboBox_expunits, 1, 1, 1, 1)
        self.labelExposure = QtGui.QLabel(self.Timing)
        self.labelExposure.setMaximumSize(QtCore.QSize(16777215, 20))
        self.labelExposure.setText(QtGui.QApplication.translate("Form", "Actual: --", None, QtGui.QApplication.UnicodeUTF8))
        self.labelExposure.setObjectName(_fromUtf8("labelExposure"))
        self.gridLayout.addWidget(self.labelExposure, 2, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.Timing)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Common Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.pushButton_5hz = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_5hz.setText(QtGui.QApplication.translate("Form", "5 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_5hz.setObjectName(_fromUtf8("pushButton_5hz"))
        self.gridLayout_5.addWidget(self.pushButton_5hz, 0, 0, 1, 1)
        self.pushButton_10hz = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_10hz.setText(QtGui.QApplication.translate("Form", "10 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_10hz.setObjectName(_fromUtf8("pushButton_10hz"))
        self.gridLayout_5.addWidget(self.pushButton_10hz, 0, 1, 1, 1)
        self.pushButton_20hz = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_20hz.setText(QtGui.QApplication.translate("Form", "20 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_20hz.setObjectName(_fromUtf8("pushButton_20hz"))
        self.gridLayout_5.addWidget(self.pushButton_20hz, 1, 0, 1, 1)
        self.pushButton_60hz = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_60hz.setText(QtGui.QApplication.translate("Form", "60 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_60hz.setObjectName(_fromUtf8("pushButton_60hz"))
        self.gridLayout_5.addWidget(self.pushButton_60hz, 1, 1, 1, 1)
        self.pushButton_100hz = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_100hz.setText(QtGui.QApplication.translate("Form", "100 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_100hz.setObjectName(_fromUtf8("pushButton_100hz"))
        self.gridLayout_5.addWidget(self.pushButton_100hz, 2, 0, 1, 1)
        self.pushButton_120hz = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_120hz.setText(QtGui.QApplication.translate("Form", "120 Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_120hz.setObjectName(_fromUtf8("pushButton_120hz"))
        self.gridLayout_5.addWidget(self.pushButton_120hz, 2, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 7, 0, 1, 2)
        self.tabWidget.addTab(self.Timing, _fromUtf8(""))
        self.Size = QtGui.QWidget()
        self.Size.setObjectName(_fromUtf8("Size"))
        self.label_16 = QtGui.QLabel(self.Size)
        self.label_16.setGeometry(QtCore.QRect(10, 61, 51, 16))
        self.label_16.setText(QtGui.QApplication.translate("Form", "x0, y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.x0_lineEdit = QtGui.QLineEdit(self.Size)
        self.x0_lineEdit.setGeometry(QtCore.QRect(80, 60, 31, 20))
        self.x0_lineEdit.setObjectName(_fromUtf8("x0_lineEdit"))
        self.y0_lineEdit = QtGui.QLineEdit(self.Size)
        self.y0_lineEdit.setGeometry(QtCore.QRect(120, 60, 31, 20))
        self.y0_lineEdit.setObjectName(_fromUtf8("y0_lineEdit"))
        self.widget = QtGui.QWidget(self.Size)
        self.widget.setGeometry(QtCore.QRect(9, 0, 211, 51))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widget)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_8 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_8.setFont(font)
        self.label_8.setText(QtGui.QApplication.translate("Form", "x0: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.x0_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.x0_label.setFont(font)
        self.x0_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.x0_label.setObjectName(_fromUtf8("x0_label"))
        self.gridLayout_3.addWidget(self.x0_label, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_10.setFont(font)
        self.label_10.setText(QtGui.QApplication.translate("Form", "y0:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 0, 2, 1, 1)
        self.y0_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.y0_label.setFont(font)
        self.y0_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.y0_label.setObjectName(_fromUtf8("y0_label"))
        self.gridLayout_3.addWidget(self.y0_label, 0, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_12.setFont(font)
        self.label_12.setText(QtGui.QApplication.translate("Form", "x dimension:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.xres_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.xres_label.setFont(font)
        self.xres_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.xres_label.setObjectName(_fromUtf8("xres_label"))
        self.gridLayout_3.addWidget(self.xres_label, 1, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_13.setFont(font)
        self.label_13.setText(QtGui.QApplication.translate("Form", "y dimension:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 2, 1, 1)
        self.yres_label = QtGui.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(6)
        self.yres_label.setFont(font)
        self.yres_label.setText(QtGui.QApplication.translate("Form", "----", None, QtGui.QApplication.UnicodeUTF8))
        self.yres_label.setObjectName(_fromUtf8("yres_label"))
        self.gridLayout_3.addWidget(self.yres_label, 1, 3, 1, 1)
        self.xres_lineEdit = QtGui.QLineEdit(self.Size)
        self.xres_lineEdit.setGeometry(QtCore.QRect(80, 80, 31, 20))
        self.xres_lineEdit.setObjectName(_fromUtf8("xres_lineEdit"))
        self.label_17 = QtGui.QLabel(self.Size)
        self.label_17.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_17.setText(QtGui.QApplication.translate("Form", "xsize, ysize:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.yres_lineEdit = QtGui.QLineEdit(self.Size)
        self.yres_lineEdit.setGeometry(QtCore.QRect(120, 80, 31, 20))
        self.yres_lineEdit.setObjectName(_fromUtf8("yres_lineEdit"))
        self.setROI_pushButton = QtGui.QPushButton(self.Size)
        self.setROI_pushButton.setGeometry(QtCore.QRect(170, 60, 51, 41))
        self.setROI_pushButton.setText(QtGui.QApplication.translate("Form", "Set ROI", None, QtGui.QApplication.UnicodeUTF8))
        self.setROI_pushButton.setObjectName(_fromUtf8("setROI_pushButton"))
        self.labelROIDisplay = QtGui.QLabel(self.Size)
        self.labelROIDisplay.setGeometry(QtCore.QRect(100, 120, 111, 111))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelROIDisplay.sizePolicy().hasHeightForWidth())
        self.labelROIDisplay.setSizePolicy(sizePolicy)
        self.labelROIDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelROIDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelROIDisplay.setText(_fromUtf8(""))
        self.labelROIDisplay.setObjectName(_fromUtf8("labelROIDisplay"))
        self.radioButton_2x2Binning = QtGui.QRadioButton(self.Size)
        self.radioButton_2x2Binning.setGeometry(QtCore.QRect(0, 190, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_2x2Binning.setFont(font)
        self.radioButton_2x2Binning.setText(QtGui.QApplication.translate("Form", "2x2", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_2x2Binning.setObjectName(_fromUtf8("radioButton_2x2Binning"))
        self.radioButton_4x4Binning = QtGui.QRadioButton(self.Size)
        self.radioButton_4x4Binning.setGeometry(QtCore.QRect(0, 210, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_4x4Binning.setFont(font)
        self.radioButton_4x4Binning.setText(QtGui.QApplication.translate("Form", "4x4", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_4x4Binning.setObjectName(_fromUtf8("radioButton_4x4Binning"))
        self.radioButton_noBinning = QtGui.QRadioButton(self.Size)
        self.radioButton_noBinning.setGeometry(QtCore.QRect(0, 170, 82, 17))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.radioButton_noBinning.setFont(font)
        self.radioButton_noBinning.setText(QtGui.QApplication.translate("Form", "No Binning", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_noBinning.setObjectName(_fromUtf8("radioButton_noBinning"))
        self.pushButton_roi256256 = QtGui.QPushButton(self.Size)
        self.pushButton_roi256256.setGeometry(QtCore.QRect(50, 110, 41, 23))
        self.pushButton_roi256256.setText(QtGui.QApplication.translate("Form", "256x256", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_roi256256.setObjectName(_fromUtf8("pushButton_roi256256"))
        self.pushButton_roi512256 = QtGui.QPushButton(self.Size)
        self.pushButton_roi512256.setGeometry(QtCore.QRect(0, 140, 41, 23))
        self.pushButton_roi512256.setText(QtGui.QApplication.translate("Form", "512x256", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_roi512256.setObjectName(_fromUtf8("pushButton_roi512256"))
        self.pushButton_roi128128 = QtGui.QPushButton(self.Size)
        self.pushButton_roi128128.setGeometry(QtCore.QRect(0, 110, 41, 23))
        self.pushButton_roi128128.setText(QtGui.QApplication.translate("Form", "128x128", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_roi128128.setObjectName(_fromUtf8("pushButton_roi128128"))
        self.pushButton_roi512512 = QtGui.QPushButton(self.Size)
        self.pushButton_roi512512.setGeometry(QtCore.QRect(50, 140, 41, 23))
        self.pushButton_roi512512.setText(QtGui.QApplication.translate("Form", "512x512", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_roi512512.setObjectName(_fromUtf8("pushButton_roi512512"))
        self.tabWidget.addTab(self.Size, _fromUtf8(""))
        self.etc = QtGui.QWidget()
        self.etc.setObjectName(_fromUtf8("etc"))
        self.groupBox1 = QtGui.QGroupBox(self.etc)
        self.groupBox1.setGeometry(QtCore.QRect(0, 10, 221, 111))
        self.groupBox1.setTitle(QtGui.QApplication.translate("Form", "For taking series of snap shots (useful for 2 channel...)", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox1.setObjectName(_fromUtf8("groupBox1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pushButton_beginSnaps = QtGui.QPushButton(self.groupBox1)
        self.pushButton_beginSnaps.setText(QtGui.QApplication.translate("Form", "Begin Snaps", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_beginSnaps.setObjectName(_fromUtf8("pushButton_beginSnaps"))
        self.gridLayout_2.addWidget(self.pushButton_beginSnaps, 0, 0, 1, 1)
        self.pushButton_takeSnap = QtGui.QPushButton(self.groupBox1)
        self.pushButton_takeSnap.setText(QtGui.QApplication.translate("Form", "Take Snap Shot", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_takeSnap.setObjectName(_fromUtf8("pushButton_takeSnap"))
        self.gridLayout_2.addWidget(self.pushButton_takeSnap, 1, 0, 1, 1)
        self.pushButton_doneSnaps = QtGui.QPushButton(self.groupBox1)
        self.pushButton_doneSnaps.setText(QtGui.QApplication.translate("Form", "Done", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_doneSnaps.setObjectName(_fromUtf8("pushButton_doneSnaps"))
        self.gridLayout_2.addWidget(self.pushButton_doneSnaps, 2, 0, 1, 1)
        self.pushButton_SaveFrame = QtGui.QPushButton(self.etc)
        self.pushButton_SaveFrame.setGeometry(QtCore.QRect(10, 210, 187, 15))
        self.pushButton_SaveFrame.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_SaveFrame.setFont(font)
        self.pushButton_SaveFrame.setText(QtGui.QApplication.translate("Form", "Save Frame (as npy array)", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_SaveFrame.setAutoDefault(False)
        self.pushButton_SaveFrame.setDefault(False)
        self.pushButton_SaveFrame.setFlat(False)
        self.pushButton_SaveFrame.setObjectName(_fromUtf8("pushButton_SaveFrame"))
        self.label_7 = QtGui.QLabel(self.etc)
        self.label_7.setGeometry(QtCore.QRect(10, 160, 101, 16))
        self.label_7.setText(QtGui.QApplication.translate("Form", "To-Disk Update Time (ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lineEdit_toDiskTime = QtGui.QLineEdit(self.etc)
        self.lineEdit_toDiskTime.setGeometry(QtCore.QRect(110, 160, 71, 20))
        self.lineEdit_toDiskTime.setText(QtGui.QApplication.translate("Form", "200", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_toDiskTime.setObjectName(_fromUtf8("lineEdit_toDiskTime"))
        self.checkBox_autoUpdateTime = QtGui.QCheckBox(self.etc)
        self.checkBox_autoUpdateTime.setGeometry(QtCore.QRect(10, 170, 121, 20))
        self.checkBox_autoUpdateTime.setText(QtGui.QApplication.translate("Form", "Auto update time", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_autoUpdateTime.setChecked(True)
        self.checkBox_autoUpdateTime.setTristate(False)
        self.checkBox_autoUpdateTime.setObjectName(_fromUtf8("checkBox_autoUpdateTime"))
        self.checkBox_defectMode = QtGui.QCheckBox(self.etc)
        self.checkBox_defectMode.setGeometry(QtCore.QRect(10, 190, 191, 17))
        self.checkBox_defectMode.setText(QtGui.QApplication.translate("Form", "Defect Correct Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_defectMode.setChecked(True)
        self.checkBox_defectMode.setObjectName(_fromUtf8("checkBox_defectMode"))
        self.label_15 = QtGui.QLabel(self.etc)
        self.label_15.setGeometry(QtCore.QRect(10, 130, 46, 13))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Trigger Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.triggerMode_lineEdit = QtGui.QLineEdit(self.etc)
        self.triggerMode_lineEdit.setGeometry(QtCore.QRect(60, 130, 31, 16))
        self.triggerMode_lineEdit.setObjectName(_fromUtf8("triggerMode_lineEdit"))
        self.comboBox_triggermodes = QtGui.QComboBox(self.etc)
        self.comboBox_triggermodes.setGeometry(QtCore.QRect(90, 130, 69, 22))
        self.comboBox_triggermodes.setObjectName(_fromUtf8("comboBox_triggermodes"))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(0, QtGui.QApplication.translate("Form", "Internal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(1, QtGui.QApplication.translate("Form", "Edge", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(2, QtGui.QApplication.translate("Form", "Level", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(3, QtGui.QApplication.translate("Form", "Multishot", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(4, QtGui.QApplication.translate("Form", "CycleDelay", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(5, QtGui.QApplication.translate("Form", "Software", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(6, QtGui.QApplication.translate("Form", "Fastrep", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(7, QtGui.QApplication.translate("Form", "TDI", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(8, QtGui.QApplication.translate("Form", "TDI_Internal", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(9, QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_triggermodes.addItem(_fromUtf8(""))
        self.comboBox_triggermodes.setItemText(10, QtGui.QApplication.translate("Form", "SyncReadout", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_triggermodes = QtGui.QPushButton(self.etc)
        self.pushButton_triggermodes.setGeometry(QtCore.QRect(160, 130, 41, 23))
        self.pushButton_triggermodes.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_triggermodes.setObjectName(_fromUtf8("pushButton_triggermodes"))
        self.tabWidget.addTab(self.etc, _fromUtf8(""))

        self.retranslateUi(Form)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(3)
        self.comboBox_expunits.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.Image), QtGui.QApplication.translate("Form", "Image", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab), QtGui.QApplication.translate("Form", "Plot", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.settings), QtGui.QApplication.translate("Form", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Timing), QtGui.QApplication.translate("Form", "Timing", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Size), QtGui.QApplication.translate("Form", "Size", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.etc), QtGui.QApplication.translate("Form", "Etc.", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
