# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageBasedFocusLock_design.ui'
#
# Created: Wed Mar 12 10:00:10 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(988, 651)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 241, 221))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Acquire Targets", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.noz_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.noz_checkBox.setGeometry(QtCore.QRect(100, 150, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.noz_checkBox.setFont(font)
        self.noz_checkBox.setText(QtGui.QApplication.translate("Form", "Only acquire in-focus", None, QtGui.QApplication.UnicodeUTF8))
        self.noz_checkBox.setObjectName(_fromUtf8("noz_checkBox"))
        self.getTargets_pushButton = QtGui.QPushButton(self.groupBox_2)
        self.getTargets_pushButton.setGeometry(QtCore.QRect(10, 150, 75, 23))
        self.getTargets_pushButton.setText(QtGui.QApplication.translate("Form", "Acquire", None, QtGui.QApplication.UnicodeUTF8))
        self.getTargets_pushButton.setObjectName(_fromUtf8("getTargets_pushButton"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        self.widget.setGeometry(QtCore.QRect(10, 10, 221, 131))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setText(QtGui.QApplication.translate("Form", "Z sep.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.zsep_doubleSpinBox = QtGui.QDoubleSpinBox(self.widget)
        self.zsep_doubleSpinBox.setObjectName(_fromUtf8("zsep_doubleSpinBox"))
        self.gridLayout_7.addWidget(self.zsep_doubleSpinBox, 0, 2, 1, 1)
        self.target_lineEdit = QtGui.QLineEdit(self.widget)
        self.target_lineEdit.setObjectName(_fromUtf8("target_lineEdit"))
        self.gridLayout_7.addWidget(self.target_lineEdit, 2, 0, 1, 1)
        self.below_lineEdit = QtGui.QLineEdit(self.widget)
        self.below_lineEdit.setObjectName(_fromUtf8("below_lineEdit"))
        self.gridLayout_7.addWidget(self.below_lineEdit, 2, 2, 1, 1)
        self.above_lineEdit = QtGui.QLineEdit(self.widget)
        self.above_lineEdit.setObjectName(_fromUtf8("above_lineEdit"))
        self.gridLayout_7.addWidget(self.above_lineEdit, 2, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.widget)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Target", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_7.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.widget)
        self.label_27.setText(QtGui.QApplication.translate("Form", "Below", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_7.addWidget(self.label_27, 1, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.widget)
        self.label_28.setText(QtGui.QApplication.translate("Form", "Above", None, QtGui.QApplication.UnicodeUTF8))
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_7.addWidget(self.label_28, 1, 3, 1, 1)
        self.targetToCurrent_pushButton = QtGui.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(5)
        font.setKerning(True)
        self.targetToCurrent_pushButton.setFont(font)
        self.targetToCurrent_pushButton.setText(QtGui.QApplication.translate("Form", "Set Target To Current", None, QtGui.QApplication.UnicodeUTF8))
        self.targetToCurrent_pushButton.setObjectName(_fromUtf8("targetToCurrent_pushButton"))
        self.gridLayout_7.addWidget(self.targetToCurrent_pushButton, 0, 3, 1, 1)
        self.useReflection_checkBox = QtGui.QCheckBox(self.widget)
        self.useReflection_checkBox.setText(QtGui.QApplication.translate("Form", "Use reflection, not transmitted images", None, QtGui.QApplication.UnicodeUTF8))
        self.useReflection_checkBox.setObjectName(_fromUtf8("useReflection_checkBox"))
        self.gridLayout_7.addWidget(self.useReflection_checkBox, 3, 0, 1, 4)
        self.findCOM_checkBox = QtGui.QCheckBox(self.widget)
        self.findCOM_checkBox.setText(QtGui.QApplication.translate("Form", "Find centroid, don\'t fit", None, QtGui.QApplication.UnicodeUTF8))
        self.findCOM_checkBox.setObjectName(_fromUtf8("findCOM_checkBox"))
        self.gridLayout_7.addWidget(self.findCOM_checkBox, 4, 0, 1, 3)
        self.dryrun_checkBox = QtGui.QCheckBox(self.groupBox_2)
        self.dryrun_checkBox.setGeometry(QtCore.QRect(20, 180, 163, 17))
        self.dryrun_checkBox.setText(QtGui.QApplication.translate("Form", "Dry run?", None, QtGui.QApplication.UnicodeUTF8))
        self.dryrun_checkBox.setObjectName(_fromUtf8("dryrun_checkBox"))
        self.numFrames_lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.numFrames_lineEdit.setGeometry(QtCore.QRect(130, 200, 55, 20))
        self.numFrames_lineEdit.setText(QtGui.QApplication.translate("Form", "200000", None, QtGui.QApplication.UnicodeUTF8))
        self.numFrames_lineEdit.setObjectName(_fromUtf8("numFrames_lineEdit"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(22, 200, 102, 20))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Number of iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.groupBox_3 = QtGui.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 430, 221, 81))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Error Signals", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label1 = QtGui.QLabel(self.groupBox_3)
        self.label1.setText(QtGui.QApplication.translate("Form", "Target signal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label1.setObjectName(_fromUtf8("label1"))
        self.gridLayout.addWidget(self.label1, 0, 0, 1, 1)
        self.label2 = QtGui.QLabel(self.groupBox_3)
        self.label2.setText(QtGui.QApplication.translate("Form", "Current signal:", None, QtGui.QApplication.UnicodeUTF8))
        self.label2.setObjectName(_fromUtf8("label2"))
        self.gridLayout.addWidget(self.label2, 1, 0, 1, 1)
        self.label3 = QtGui.QLabel(self.groupBox_3)
        self.label3.setText(QtGui.QApplication.translate("Form", "X,Y drift:", None, QtGui.QApplication.UnicodeUTF8))
        self.label3.setObjectName(_fromUtf8("label3"))
        self.gridLayout.addWidget(self.label3, 2, 0, 1, 1)
        self.targetsig_label = QtGui.QLabel(self.groupBox_3)
        self.targetsig_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.targetsig_label.setObjectName(_fromUtf8("targetsig_label"))
        self.gridLayout.addWidget(self.targetsig_label, 0, 1, 1, 1)
        self.currentsig_label = QtGui.QLabel(self.groupBox_3)
        self.currentsig_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.currentsig_label.setObjectName(_fromUtf8("currentsig_label"))
        self.gridLayout.addWidget(self.currentsig_label, 1, 1, 1, 1)
        self.xyd_label = QtGui.QLabel(self.groupBox_3)
        self.xyd_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.xyd_label.setObjectName(_fromUtf8("xyd_label"))
        self.gridLayout.addWidget(self.xyd_label, 2, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(0, 510, 221, 101))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Distances Moved", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setText(QtGui.QApplication.translate("Form", "X travel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_4)
        self.label_9.setText(QtGui.QApplication.translate("Form", "Y travel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setText(QtGui.QApplication.translate("Form", "Z travel:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.xtravel_label = QtGui.QLabel(self.groupBox_4)
        self.xtravel_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.xtravel_label.setObjectName(_fromUtf8("xtravel_label"))
        self.gridLayout_2.addWidget(self.xtravel_label, 0, 1, 1, 1)
        self.ytravel_label = QtGui.QLabel(self.groupBox_4)
        self.ytravel_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.ytravel_label.setObjectName(_fromUtf8("ytravel_label"))
        self.gridLayout_2.addWidget(self.ytravel_label, 1, 1, 1, 1)
        self.ztravel_label = QtGui.QLabel(self.groupBox_4)
        self.ztravel_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.ztravel_label.setObjectName(_fromUtf8("ztravel_label"))
        self.gridLayout_2.addWidget(self.ztravel_label, 2, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_4)
        self.label_24.setText(QtGui.QApplication.translate("Form", "Z stage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 3, 0, 1, 1)
        self.zstage_label = QtGui.QLabel(self.groupBox_4)
        self.zstage_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.zstage_label.setObjectName(_fromUtf8("zstage_label"))
        self.gridLayout_2.addWidget(self.zstage_label, 3, 1, 1, 1)
        self.tabWidget_5 = QtGui.QTabWidget(Form)
        self.tabWidget_5.setEnabled(True)
        self.tabWidget_5.setGeometry(QtCore.QRect(0, 230, 241, 201))
        self.tabWidget_5.setObjectName(_fromUtf8("tabWidget_5"))
        self.ZFeedback = QtGui.QWidget()
        self.ZFeedback.setObjectName(_fromUtf8("ZFeedback"))
        self.formLayout_2 = QtGui.QFormLayout(self.ZFeedback)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_6 = QtGui.QLabel(self.ZFeedback)
        self.label_6.setText(QtGui.QApplication.translate("Form", "Proportional feedback:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.propz_lineEdit = QtGui.QLineEdit(self.ZFeedback)
        self.propz_lineEdit.setObjectName(_fromUtf8("propz_lineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.propz_lineEdit)
        self.label_7 = QtGui.QLabel(self.ZFeedback)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.threshold_lineEdit = QtGui.QLineEdit(self.ZFeedback)
        self.threshold_lineEdit.setEnabled(True)
        self.threshold_lineEdit.setText(QtGui.QApplication.translate("Form", "0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.threshold_lineEdit.setObjectName(_fromUtf8("threshold_lineEdit"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.threshold_lineEdit)
        self.label_8 = QtGui.QLabel(self.ZFeedback)
        self.label_8.setText(QtGui.QApplication.translate("Form", "Rolling av.:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_8)
        self.rolling_lineEdit = QtGui.QLineEdit(self.ZFeedback)
        self.rolling_lineEdit.setEnabled(True)
        self.rolling_lineEdit.setText(QtGui.QApplication.translate("Form", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.rolling_lineEdit.setObjectName(_fromUtf8("rolling_lineEdit"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.rolling_lineEdit)
        self.label_3 = QtGui.QLabel(self.ZFeedback)
        self.label_3.setText(QtGui.QApplication.translate("Form", "Z offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_3)
        self.zoff_lineEdit = QtGui.QLineEdit(self.ZFeedback)
        self.zoff_lineEdit.setObjectName(_fromUtf8("zoff_lineEdit"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.zoff_lineEdit)
        self.label_14 = QtGui.QLabel(self.ZFeedback)
        self.label_14.setText(QtGui.QApplication.translate("Form", "Reflection min diff:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_14)
        self.reflectionMin_lineEdit = QtGui.QLineEdit(self.ZFeedback)
        self.reflectionMin_lineEdit.setText(QtGui.QApplication.translate("Form", "10000", None, QtGui.QApplication.UnicodeUTF8))
        self.reflectionMin_lineEdit.setObjectName(_fromUtf8("reflectionMin_lineEdit"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.reflectionMin_lineEdit)
        self.label_15 = QtGui.QLabel(self.ZFeedback)
        self.label_15.setText(QtGui.QApplication.translate("Form", "Integral feedback:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_15)
        self.intz_lineEdit = QtGui.QLineEdit(self.ZFeedback)
        self.intz_lineEdit.setObjectName(_fromUtf8("intz_lineEdit"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.intz_lineEdit)
        self.tabWidget_5.addTab(self.ZFeedback, _fromUtf8(""))
        self.tab_xy = QtGui.QWidget()
        self.tab_xy.setEnabled(True)
        self.tab_xy.setObjectName(_fromUtf8("tab_xy"))
        self.widget1 = QtGui.QWidget(self.tab_xy)
        self.widget1.setGeometry(QtCore.QRect(0, 0, 221, 171))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label = QtGui.QLabel(self.widget1)
        self.label.setText(QtGui.QApplication.translate("Form", "x proportional feedback:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.propx_lineEdit = QtGui.QLineEdit(self.widget1)
        self.propx_lineEdit.setText(QtGui.QApplication.translate("Form", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.propx_lineEdit.setObjectName(_fromUtf8("propx_lineEdit"))
        self.gridLayout_6.addWidget(self.propx_lineEdit, 0, 1, 1, 1)
        self.label_25 = QtGui.QLabel(self.widget1)
        self.label_25.setText(QtGui.QApplication.translate("Form", "y proportional feedback:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_6.addWidget(self.label_25, 1, 0, 1, 1)
        self.propy_lineEdit = QtGui.QLineEdit(self.widget1)
        self.propy_lineEdit.setText(QtGui.QApplication.translate("Form", "0.1", None, QtGui.QApplication.UnicodeUTF8))
        self.propy_lineEdit.setObjectName(_fromUtf8("propy_lineEdit"))
        self.gridLayout_6.addWidget(self.propy_lineEdit, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.widget1)
        self.label_2.setText(QtGui.QApplication.translate("Form", "xy threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 2, 0, 1, 1)
        self.xythresh_lineEdit = QtGui.QLineEdit(self.widget1)
        self.xythresh_lineEdit.setEnabled(True)
        self.xythresh_lineEdit.setText(QtGui.QApplication.translate("Form", "0.05", None, QtGui.QApplication.UnicodeUTF8))
        self.xythresh_lineEdit.setObjectName(_fromUtf8("xythresh_lineEdit"))
        self.gridLayout_6.addWidget(self.xythresh_lineEdit, 2, 1, 1, 1)
        self.checkBox_rollingXY = QtGui.QCheckBox(self.widget1)
        self.checkBox_rollingXY.setText(QtGui.QApplication.translate("Form", "Rolling av for xy?", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_rollingXY.setObjectName(_fromUtf8("checkBox_rollingXY"))
        self.gridLayout_6.addWidget(self.checkBox_rollingXY, 5, 0, 1, 1)
        self.checkBox_useMarz = QtGui.QCheckBox(self.widget1)
        self.checkBox_useMarz.setText(QtGui.QApplication.translate("Form", "Use Marzhauser for xy?", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_useMarz.setObjectName(_fromUtf8("checkBox_useMarz"))
        self.gridLayout_6.addWidget(self.checkBox_useMarz, 4, 0, 1, 1)
        self.checkBox_noxy = QtGui.QCheckBox(self.widget1)
        self.checkBox_noxy.setText(QtGui.QApplication.translate("Form", "No xy correction?", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_noxy.setObjectName(_fromUtf8("checkBox_noxy"))
        self.gridLayout_6.addWidget(self.checkBox_noxy, 3, 0, 1, 1)
        self.tabWidget_5.addTab(self.tab_xy, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setGeometry(QtCore.QRect(30, 20, 181, 121))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setText(QtGui.QApplication.translate("Form", "Move:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.calMove_lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.calMove_lineEdit.setEnabled(False)
        self.calMove_lineEdit.setObjectName(_fromUtf8("calMove_lineEdit"))
        self.gridLayout_3.addWidget(self.calMove_lineEdit, 1, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        self.label_18.setText(QtGui.QApplication.translate("Form", "Distance", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_3.addWidget(self.label_18, 0, 1, 1, 1)
        self.calRepeats_lineEdit = QtGui.QLineEdit(self.groupBox_6)
        self.calRepeats_lineEdit.setText(QtGui.QApplication.translate("Form", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.calRepeats_lineEdit.setObjectName(_fromUtf8("calRepeats_lineEdit"))
        self.gridLayout_3.addWidget(self.calRepeats_lineEdit, 1, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.groupBox_6)
        self.label_19.setText(QtGui.QApplication.translate("Form", "Repeats", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_3.addWidget(self.label_19, 0, 2, 1, 1)
        self.widget_2 = QtGui.QWidget(self.groupBox_6)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioButton_x = QtGui.QRadioButton(self.widget_2)
        self.radioButton_x.setText(QtGui.QApplication.translate("Form", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_x.setObjectName(_fromUtf8("radioButton_x"))
        self.buttonGroup_2 = QtGui.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName(_fromUtf8("buttonGroup_2"))
        self.buttonGroup_2.addButton(self.radioButton_x)
        self.horizontalLayout.addWidget(self.radioButton_x)
        self.radioButton_y = QtGui.QRadioButton(self.widget_2)
        self.radioButton_y.setText(QtGui.QApplication.translate("Form", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_y.setObjectName(_fromUtf8("radioButton_y"))
        self.buttonGroup_2.addButton(self.radioButton_y)
        self.horizontalLayout.addWidget(self.radioButton_y)
        self.radioButton_z = QtGui.QRadioButton(self.widget_2)
        self.radioButton_z.setText(QtGui.QApplication.translate("Form", "z", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_z.setObjectName(_fromUtf8("radioButton_z"))
        self.buttonGroup_2.addButton(self.radioButton_z)
        self.horizontalLayout.addWidget(self.radioButton_z)
        self.gridLayout_3.addWidget(self.widget_2, 2, 0, 1, 3)
        self.tabWidget_5.addTab(self.tab_2, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.label_17 = QtGui.QLabel(self.tab_4)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 121, 16))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Spastic stage threshold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.maybeTrouble_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.maybeTrouble_lineEdit.setGeometry(QtCore.QRect(140, 10, 81, 20))
        self.maybeTrouble_lineEdit.setObjectName(_fromUtf8("maybeTrouble_lineEdit"))
        self.timesToMove_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.timesToMove_lineEdit.setGeometry(QtCore.QRect(70, 50, 161, 20))
        self.timesToMove_lineEdit.setObjectName(_fromUtf8("timesToMove_lineEdit"))
        self.label_21 = QtGui.QLabel(self.tab_4)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 46, 13))
        self.label_21.setText(QtGui.QApplication.translate("Form", "Times:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_31 = QtGui.QLabel(self.tab_4)
        self.label_31.setGeometry(QtCore.QRect(10, 90, 46, 13))
        self.label_31.setText(QtGui.QApplication.translate("Form", "Positions:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.posToMove_lineEdit = QtGui.QLineEdit(self.tab_4)
        self.posToMove_lineEdit.setGeometry(QtCore.QRect(70, 90, 161, 20))
        self.posToMove_lineEdit.setObjectName(_fromUtf8("posToMove_lineEdit"))
        self.toMove_checkBox = QtGui.QCheckBox(self.tab_4)
        self.toMove_checkBox.setGeometry(QtCore.QRect(10, 120, 211, 20))
        self.toMove_checkBox.setText(QtGui.QApplication.translate("Form", "Move to these positions at these times?", None, QtGui.QApplication.UnicodeUTF8))
        self.toMove_checkBox.setObjectName(_fromUtf8("toMove_checkBox"))
        self.tabWidget_5.addTab(self.tab_4, _fromUtf8(""))
        self.groupBox_7 = QtGui.QGroupBox(Form)
        self.groupBox_7.setGeometry(QtCore.QRect(250, 0, 181, 211))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Form", "Camera Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_12 = QtGui.QLabel(self.groupBox_7)
        self.label_12.setMinimumSize(QtCore.QSize(95, 0))
        self.label_12.setText(QtGui.QApplication.translate("Form", "Exposure Time(ms):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        self.label_16.setText(QtGui.QApplication.translate("Form", "Monitor Delay (s):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_4.addWidget(self.label_16, 4, 0, 1, 1)
        self.monitorDelay_lineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.monitorDelay_lineEdit.setEnabled(True)
        self.monitorDelay_lineEdit.setObjectName(_fromUtf8("monitorDelay_lineEdit"))
        self.gridLayout_4.addWidget(self.monitorDelay_lineEdit, 4, 1, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_22 = QtGui.QLabel(self.groupBox_7)
        self.label_22.setText(QtGui.QApplication.translate("Form", "x,y shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_5.addWidget(self.label_22, 2, 0, 1, 1)
        self.lineEdit_yshape = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_yshape.setText(QtGui.QApplication.translate("Form", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_yshape.setObjectName(_fromUtf8("lineEdit_yshape"))
        self.gridLayout_5.addWidget(self.lineEdit_yshape, 2, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_7)
        self.label_23.setText(QtGui.QApplication.translate("Form", "x_0, y_0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_5.addWidget(self.label_23, 3, 0, 1, 1)
        self.lineEdit_y0 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_y0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_y0.setObjectName(_fromUtf8("lineEdit_y0"))
        self.gridLayout_5.addWidget(self.lineEdit_y0, 3, 2, 1, 1)
        self.lineEdit_xshape = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_xshape.setText(QtGui.QApplication.translate("Form", "512", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_xshape.setObjectName(_fromUtf8("lineEdit_xshape"))
        self.gridLayout_5.addWidget(self.lineEdit_xshape, 2, 1, 1, 1)
        self.lineEdit_x0 = QtGui.QLineEdit(self.groupBox_7)
        self.lineEdit_x0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_x0.setObjectName(_fromUtf8("lineEdit_x0"))
        self.gridLayout_5.addWidget(self.lineEdit_x0, 3, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_5, 0, 0, 1, 2)
        self.pushButton_preview = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_preview.setText(QtGui.QApplication.translate("Form", "Preview", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_preview.setObjectName(_fromUtf8("pushButton_preview"))
        self.gridLayout_4.addWidget(self.pushButton_preview, 1, 0, 1, 2)
        self.checkBox_saveAllIms = QtGui.QCheckBox(self.groupBox_7)
        self.checkBox_saveAllIms.setText(QtGui.QApplication.translate("Form", "Save all images", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_saveAllIms.setObjectName(_fromUtf8("checkBox_saveAllIms"))
        self.gridLayout_4.addWidget(self.checkBox_saveAllIms, 5, 0, 1, 1)
        self.pushButton_flatfield = QtGui.QPushButton(self.groupBox_7)
        self.pushButton_flatfield.setMaximumSize(QtCore.QSize(68, 16777215))
        self.pushButton_flatfield.setText(QtGui.QApplication.translate("Form", "Flat field", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_flatfield.setObjectName(_fromUtf8("pushButton_flatfield"))
        self.gridLayout_4.addWidget(self.pushButton_flatfield, 5, 1, 1, 1)
        self.rot90_checkBox = QtGui.QCheckBox(self.groupBox_7)
        self.rot90_checkBox.setText(QtGui.QApplication.translate("Form", "Rotate image 90 degrees", None, QtGui.QApplication.UnicodeUTF8))
        self.rot90_checkBox.setObjectName(_fromUtf8("rot90_checkBox"))
        self.gridLayout_4.addWidget(self.rot90_checkBox, 6, 0, 1, 2)
        self.exposuretime_lineEdit = QtGui.QLineEdit(self.groupBox_7)
        self.exposuretime_lineEdit.setMaximumSize(QtCore.QSize(60, 16777215))
        self.exposuretime_lineEdit.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.exposuretime_lineEdit.setObjectName(_fromUtf8("exposuretime_lineEdit"))
        self.gridLayout_4.addWidget(self.exposuretime_lineEdit, 2, 1, 1, 1)
        self.fl_pushButton = QtGui.QPushButton(Form)
        self.fl_pushButton.setEnabled(False)
        self.fl_pushButton.setGeometry(QtCore.QRect(250, 310, 181, 31))
        self.fl_pushButton.setText(QtGui.QApplication.translate("Form", "Focus Lock Start", None, QtGui.QApplication.UnicodeUTF8))
        self.fl_pushButton.setObjectName(_fromUtf8("fl_pushButton"))
        self.shutdown_pushButton = QtGui.QPushButton(Form)
        self.shutdown_pushButton.setGeometry(QtCore.QRect(340, 340, 91, 31))
        self.shutdown_pushButton.setText(QtGui.QApplication.translate("Form", "Shut down", None, QtGui.QApplication.UnicodeUTF8))
        self.shutdown_pushButton.setObjectName(_fromUtf8("shutdown_pushButton"))
        self.reset_pushButton = QtGui.QPushButton(Form)
        self.reset_pushButton.setGeometry(QtCore.QRect(250, 340, 91, 31))
        self.reset_pushButton.setText(QtGui.QApplication.translate("Form", "Reset Focus Lock", None, QtGui.QApplication.UnicodeUTF8))
        self.reset_pushButton.setObjectName(_fromUtf8("reset_pushButton"))
        self.groupBox_9 = QtGui.QGroupBox(Form)
        self.groupBox_9.setGeometry(QtCore.QRect(250, 220, 181, 81))
        self.groupBox_9.setTitle(QtGui.QApplication.translate("Form", "New Target", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.newTarget_lineEdit = QtGui.QLineEdit(self.groupBox_9)
        self.newTarget_lineEdit.setObjectName(_fromUtf8("newTarget_lineEdit"))
        self.gridLayout_8.addWidget(self.newTarget_lineEdit, 0, 1, 1, 1)
        self.label_29 = QtGui.QLabel(self.groupBox_9)
        self.label_29.setText(QtGui.QApplication.translate("Form", "New Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_8.addWidget(self.label_29, 0, 0, 1, 1)
        self.relative_checkBox = QtGui.QCheckBox(self.groupBox_9)
        self.relative_checkBox.setText(QtGui.QApplication.translate("Form", "Relative?", None, QtGui.QApplication.UnicodeUTF8))
        self.relative_checkBox.setChecked(True)
        self.relative_checkBox.setObjectName(_fromUtf8("relative_checkBox"))
        self.gridLayout_8.addWidget(self.relative_checkBox, 0, 2, 1, 1)
        self.newTarget_pushButton = QtGui.QPushButton(self.groupBox_9)
        self.newTarget_pushButton.setText(QtGui.QApplication.translate("Form", "Acquire New Target", None, QtGui.QApplication.UnicodeUTF8))
        self.newTarget_pushButton.setObjectName(_fromUtf8("newTarget_pushButton"))
        self.gridLayout_8.addWidget(self.newTarget_pushButton, 1, 1, 1, 2)
        self.qwtPlot = Qwt5.QwtPlot(Form)
        self.qwtPlot.setGeometry(QtCore.QRect(260, 430, 581, 200))
        self.qwtPlot.setObjectName(_fromUtf8("qwtPlot"))
        self.label_calibration = QtGui.QLabel(Form)
        self.label_calibration.setGeometry(QtCore.QRect(850, 410, 131, 16))
        self.label_calibration.setText(QtGui.QApplication.translate("Form", "Calibration: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_calibration.setObjectName(_fromUtf8("label_calibration"))
        self.stop_pushButton = QtGui.QPushButton(Form)
        self.stop_pushButton.setGeometry(QtCore.QRect(150, 610, 75, 23))
        self.stop_pushButton.setText(QtGui.QApplication.translate("Form", "STOP", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        self.plotFit_checkBox = QtGui.QCheckBox(Form)
        self.plotFit_checkBox.setGeometry(QtCore.QRect(850, 450, 70, 17))
        self.plotFit_checkBox.setText(QtGui.QApplication.translate("Form", "Plot Fit?", None, QtGui.QApplication.UnicodeUTF8))
        self.plotFit_checkBox.setObjectName(_fromUtf8("plotFit_checkBox"))
        self.label_calResult = QtGui.QLabel(Form)
        self.label_calResult.setGeometry(QtCore.QRect(850, 430, 131, 20))
        self.label_calResult.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_calResult.setObjectName(_fromUtf8("label_calResult"))
        self.plotColumn_checkBox = QtGui.QCheckBox(Form)
        self.plotColumn_checkBox.setGeometry(QtCore.QRect(850, 470, 111, 17))
        self.plotColumn_checkBox.setText(QtGui.QApplication.translate("Form", "Plot column sum?", None, QtGui.QApplication.UnicodeUTF8))
        self.plotColumn_checkBox.setObjectName(_fromUtf8("plotColumn_checkBox"))
        self.label_xyValue = QtGui.QLabel(Form)
        self.label_xyValue.setGeometry(QtCore.QRect(250, 390, 191, 16))
        self.label_xyValue.setText(QtGui.QApplication.translate("Form", "x,y: -,-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_xyValue.setObjectName(_fromUtf8("label_xyValue"))
        self.verticalSlider = QtGui.QSlider(Form)
        self.verticalSlider.setGeometry(QtCore.QRect(870, 500, 20, 141))
        self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider.setObjectName(_fromUtf8("verticalSlider"))
        self.upperLim_lineEdit = QtGui.QLineEdit(Form)
        self.upperLim_lineEdit.setGeometry(QtCore.QRect(890, 490, 51, 20))
        self.upperLim_lineEdit.setObjectName(_fromUtf8("upperLim_lineEdit"))
        self.lowerLim_lineEdit = QtGui.QLineEdit(Form)
        self.lowerLim_lineEdit.setGeometry(QtCore.QRect(900, 620, 51, 20))
        self.lowerLim_lineEdit.setObjectName(_fromUtf8("lowerLim_lineEdit"))
        self.setSlider_pushButton = QtGui.QPushButton(Form)
        self.setSlider_pushButton.setGeometry(QtCore.QRect(890, 510, 51, 23))
        self.setSlider_pushButton.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.setSlider_pushButton.setObjectName(_fromUtf8("setSlider_pushButton"))
        self.sliderVal_label = QtGui.QLabel(Form)
        self.sliderVal_label.setGeometry(QtCore.QRect(900, 600, 51, 16))
        self.sliderVal_label.setText(QtGui.QApplication.translate("Form", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.sliderVal_label.setObjectName(_fromUtf8("sliderVal_label"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(430, 0, 551, 411))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.labelDisplay = QtGui.QLabel(self.tab)
        self.labelDisplay.setGeometry(QtCore.QRect(0, 0, 512, 384))
        self.labelDisplay.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelDisplay.setText(_fromUtf8(""))
        self.labelDisplay.setObjectName(_fromUtf8("labelDisplay"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.labelDisplay2 = QtGui.QLabel(self.tab_3)
        self.labelDisplay2.setGeometry(QtCore.QRect(10, 10, 256, 256))
        self.labelDisplay2.setFrameShape(QtGui.QFrame.Box)
        self.labelDisplay2.setText(QtGui.QApplication.translate("Form", "TextLabel", None, QtGui.QApplication.UnicodeUTF8))
        self.labelDisplay2.setObjectName(_fromUtf8("labelDisplay2"))
        self.layoutWidget = QtGui.QWidget(self.tab_3)
        self.layoutWidget.setGeometry(QtCore.QRect(310, 30, 231, 91))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_9 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_26 = QtGui.QLabel(self.layoutWidget)
        self.label_26.setText(QtGui.QApplication.translate("Form", "x,y shape:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_9.addWidget(self.label_26, 2, 0, 1, 1)
        self.lineEdit_yshape_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_yshape_2.setText(QtGui.QApplication.translate("Form", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_yshape_2.setObjectName(_fromUtf8("lineEdit_yshape_2"))
        self.gridLayout_9.addWidget(self.lineEdit_yshape_2, 2, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.layoutWidget)
        self.label_30.setText(QtGui.QApplication.translate("Form", "x_0, y_0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_9.addWidget(self.label_30, 3, 0, 1, 1)
        self.lineEdit_y0_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_y0_2.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_y0_2.setObjectName(_fromUtf8("lineEdit_y0_2"))
        self.gridLayout_9.addWidget(self.lineEdit_y0_2, 3, 2, 1, 1)
        self.lineEdit_xshape_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_xshape_2.setText(QtGui.QApplication.translate("Form", "256", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_xshape_2.setObjectName(_fromUtf8("lineEdit_xshape_2"))
        self.gridLayout_9.addWidget(self.lineEdit_xshape_2, 2, 1, 1, 1)
        self.lineEdit_x0_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_x0_2.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEdit_x0_2.setObjectName(_fromUtf8("lineEdit_x0_2"))
        self.gridLayout_9.addWidget(self.lineEdit_x0_2, 3, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem1, 0, 1, 1, 1)
        self.image2size_pushButton = QtGui.QPushButton(self.layoutWidget)
        self.image2size_pushButton.setText(QtGui.QApplication.translate("Form", "Set", None, QtGui.QApplication.UnicodeUTF8))
        self.image2size_pushButton.setObjectName(_fromUtf8("image2size_pushButton"))
        self.gridLayout_9.addWidget(self.image2size_pushButton, 4, 2, 1, 1)
        self.use2ndImage_checkBox = QtGui.QCheckBox(self.tab_3)
        self.use2ndImage_checkBox.setGeometry(QtCore.QRect(310, 10, 231, 17))
        self.use2ndImage_checkBox.setText(QtGui.QApplication.translate("Form", "Use second image?", None, QtGui.QApplication.UnicodeUTF8))
        self.use2ndImage_checkBox.setObjectName(_fromUtf8("use2ndImage_checkBox"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.resetCOM_pushButton = QtGui.QPushButton(Form)
        self.resetCOM_pushButton.setGeometry(QtCore.QRect(250, 370, 91, 23))
        self.resetCOM_pushButton.setText(QtGui.QApplication.translate("Form", "Reset c.o.m.", None, QtGui.QApplication.UnicodeUTF8))
        self.resetCOM_pushButton.setObjectName(_fromUtf8("resetCOM_pushButton"))
        self.label_minmaxpixel = QtGui.QLabel(Form)
        self.label_minmaxpixel.setGeometry(QtCore.QRect(250, 410, 171, 16))
        self.label_minmaxpixel.setText(QtGui.QApplication.translate("Form", "Min, max pixel value: -,-", None, QtGui.QApplication.UnicodeUTF8))
        self.label_minmaxpixel.setObjectName(_fromUtf8("label_minmaxpixel"))
        self.newFocusValue_lineEdit = QtGui.QLineEdit(Form)
        self.newFocusValue_lineEdit.setGeometry(QtCore.QRect(880, 540, 51, 20))
        self.newFocusValue_lineEdit.setObjectName(_fromUtf8("newFocusValue_lineEdit"))
        self.usenm_radioButton = QtGui.QRadioButton(Form)
        self.usenm_radioButton.setGeometry(QtCore.QRect(900, 570, 51, 17))
        self.usenm_radioButton.setText(QtGui.QApplication.translate("Form", "nm", None, QtGui.QApplication.UnicodeUTF8))
        self.usenm_radioButton.setObjectName(_fromUtf8("usenm_radioButton"))
        self.useraw_radioButton = QtGui.QRadioButton(Form)
        self.useraw_radioButton.setGeometry(QtCore.QRect(900, 590, 82, 17))
        self.useraw_radioButton.setText(QtGui.QApplication.translate("Form", "focus value", None, QtGui.QApplication.UnicodeUTF8))
        self.useraw_radioButton.setObjectName(_fromUtf8("useraw_radioButton"))
        self.scaleValue_doubleSpinBox = QtGui.QDoubleSpinBox(Form)
        self.scaleValue_doubleSpinBox.setGeometry(QtCore.QRect(940, 540, 41, 22))
        self.scaleValue_doubleSpinBox.setSingleStep(0.01)
        self.scaleValue_doubleSpinBox.setObjectName(_fromUtf8("scaleValue_doubleSpinBox"))

        self.retranslateUi(Form)
        self.tabWidget_5.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.calMove_lineEdit, self.calRepeats_lineEdit)
        Form.setTabOrder(self.calRepeats_lineEdit, self.target_lineEdit)
        Form.setTabOrder(self.target_lineEdit, self.below_lineEdit)
        Form.setTabOrder(self.below_lineEdit, self.above_lineEdit)
        Form.setTabOrder(self.above_lineEdit, self.getTargets_pushButton)
        Form.setTabOrder(self.getTargets_pushButton, self.propx_lineEdit)
        Form.setTabOrder(self.propx_lineEdit, self.propy_lineEdit)
        Form.setTabOrder(self.propy_lineEdit, self.xythresh_lineEdit)
        Form.setTabOrder(self.xythresh_lineEdit, self.propz_lineEdit)
        Form.setTabOrder(self.propz_lineEdit, self.threshold_lineEdit)
        Form.setTabOrder(self.threshold_lineEdit, self.rolling_lineEdit)
        Form.setTabOrder(self.rolling_lineEdit, self.zoff_lineEdit)
        Form.setTabOrder(self.zoff_lineEdit, self.lineEdit_xshape)
        Form.setTabOrder(self.lineEdit_xshape, self.lineEdit_yshape)
        Form.setTabOrder(self.lineEdit_yshape, self.lineEdit_x0)
        Form.setTabOrder(self.lineEdit_x0, self.lineEdit_y0)
        Form.setTabOrder(self.lineEdit_y0, self.pushButton_preview)
        Form.setTabOrder(self.pushButton_preview, self.fl_pushButton)
        Form.setTabOrder(self.fl_pushButton, self.reset_pushButton)
        Form.setTabOrder(self.reset_pushButton, self.shutdown_pushButton)
        Form.setTabOrder(self.shutdown_pushButton, self.relative_checkBox)
        Form.setTabOrder(self.relative_checkBox, self.zsep_doubleSpinBox)
        Form.setTabOrder(self.zsep_doubleSpinBox, self.noz_checkBox)
        Form.setTabOrder(self.noz_checkBox, self.newTarget_lineEdit)
        Form.setTabOrder(self.newTarget_lineEdit, self.targetToCurrent_pushButton)
        Form.setTabOrder(self.targetToCurrent_pushButton, self.monitorDelay_lineEdit)
        Form.setTabOrder(self.monitorDelay_lineEdit, self.newTarget_pushButton)

    def retranslateUi(self, Form):
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.ZFeedback), QtGui.QApplication.translate("Form", "Z Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_xy), QtGui.QApplication.translate("Form", "XY Feedback", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_2), QtGui.QApplication.translate("Form", "Calibration", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget_5.setTabText(self.tabWidget_5.indexOf(self.tab_4), QtGui.QApplication.translate("Form", "Etc.", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Form", "Main Image", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Form", "Secondary Image", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import Qwt5
