# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adaptiveOptics_design.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
sys.path.append('D:\\Dan\\Programs\\InControl\\myWidget\\')
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(912, 514)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.doubleSpinBoxRange = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBoxRange.sizePolicy().hasHeightForWidth())
        self.doubleSpinBoxRange.setSizePolicy(sizePolicy)
        self.doubleSpinBoxRange.setDecimals(1)
        self.doubleSpinBoxRange.setMinimum(-100.0)
        self.doubleSpinBoxRange.setSingleStep(0.1)
        self.doubleSpinBoxRange.setProperty("value", 4.0)
        self.doubleSpinBoxRange.setObjectName("doubleSpinBoxRange")
        self.gridLayout_4.addWidget(self.doubleSpinBoxRange, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 2, 0, 1, 1)
        self.spinBoxSlices = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxSlices.sizePolicy().hasHeightForWidth())
        self.spinBoxSlices.setSizePolicy(sizePolicy)
        self.spinBoxSlices.setReadOnly(False)
        self.spinBoxSlices.setMinimum(3)
        self.spinBoxSlices.setSingleStep(2)
        self.spinBoxSlices.setProperty("value", 21)
        self.spinBoxSlices.setObjectName("spinBoxSlices")
        self.gridLayout_4.addWidget(self.spinBoxSlices, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBoxFrames = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBoxFrames.sizePolicy().hasHeightForWidth())
        self.spinBoxFrames.setSizePolicy(sizePolicy)
        self.spinBoxFrames.setMinimum(1)
        self.spinBoxFrames.setProperty("value", 5)
        self.spinBoxFrames.setObjectName("spinBoxFrames")
        self.gridLayout_4.addWidget(self.spinBoxFrames, 3, 2, 1, 1)
        self.pushButtonPSF = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPSF.sizePolicy().hasHeightForWidth())
        self.pushButtonPSF.setSizePolicy(sizePolicy)
        self.pushButtonPSF.setObjectName("pushButtonPSF")
        self.gridLayout_4.addWidget(self.pushButtonPSF, 10, 0, 1, 3)
        self.checkBoxSave = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxSave.setObjectName("checkBoxSave")
        self.gridLayout_4.addWidget(self.checkBoxSave, 9, 0, 1, 1)
        self.lineEditFile = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEditFile.sizePolicy().hasHeightForWidth())
        self.lineEditFile.setSizePolicy(sizePolicy)
        self.lineEditFile.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEditFile.setObjectName("lineEditFile")
        self.gridLayout_4.addWidget(self.lineEditFile, 9, 2, 1, 1)
        self.checkBoxCenterLateral = QtWidgets.QCheckBox(self.groupBox)
        self.checkBoxCenterLateral.setChecked(True)
        self.checkBoxCenterLateral.setObjectName("checkBoxCenterLateral")
        self.gridLayout_4.addWidget(self.checkBoxCenterLateral, 7, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 4, 0, 1, 1)
        self.spinBox_maskRadius = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_maskRadius.setMinimum(16)
        self.spinBox_maskRadius.setMaximum(512)
        self.spinBox_maskRadius.setSingleStep(10)
        self.spinBox_maskRadius.setProperty("value", 80)
        self.spinBox_maskRadius.setObjectName("spinBox_maskRadius")
        self.gridLayout_4.addWidget(self.spinBox_maskRadius, 4, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        self.lineEdit_cX = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cX.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_cX.setObjectName("lineEdit_cX")
        self.gridLayout_4.addWidget(self.lineEdit_cX, 5, 2, 1, 1)
        self.lineEdit_cY = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_cY.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_cY.setObjectName("lineEdit_cY")
        self.gridLayout_4.addWidget(self.lineEdit_cY, 6, 2, 1, 1)
        self.pushButton_runningSharpness = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_runningSharpness.setObjectName("pushButton_runningSharpness")
        self.gridLayout_4.addWidget(self.pushButton_runningSharpness, 11, 0, 1, 3)
        self.pushButton_stopSharpness = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_stopSharpness.setObjectName("pushButton_stopSharpness")
        self.gridLayout_4.addWidget(self.pushButton_stopSharpness, 14, 0, 1, 3)
        self.pushButton_sharpnessVsZern = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_sharpnessVsZern.setObjectName("pushButton_sharpnessVsZern")
        self.gridLayout_4.addWidget(self.pushButton_sharpnessVsZern, 12, 0, 1, 3)
        self.doubleSpinBox_zernAmpMin = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_zernAmpMin.setDecimals(3)
        self.doubleSpinBox_zernAmpMin.setMinimum(-10.0)
        self.doubleSpinBox_zernAmpMin.setMaximum(10.0)
        self.doubleSpinBox_zernAmpMin.setObjectName("doubleSpinBox_zernAmpMin")
        self.gridLayout_4.addWidget(self.doubleSpinBox_zernAmpMin, 17, 2, 1, 1)
        self.doubleSpinBox_zernAmpMax = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_zernAmpMax.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_zernAmpMax.setSizePolicy(sizePolicy)
        self.doubleSpinBox_zernAmpMax.setDecimals(3)
        self.doubleSpinBox_zernAmpMax.setMinimum(-10.0)
        self.doubleSpinBox_zernAmpMax.setMaximum(10.0)
        self.doubleSpinBox_zernAmpMax.setObjectName("doubleSpinBox_zernAmpMax")
        self.gridLayout_4.addWidget(self.doubleSpinBox_zernAmpMax, 18, 2, 1, 1)
        self.label_mod_index = QtWidgets.QLabel(self.groupBox)
        self.label_mod_index.setObjectName("label_mod_index")
        self.gridLayout_4.addWidget(self.label_mod_index, 17, 0, 1, 1)
        self.label_mod_value = QtWidgets.QLabel(self.groupBox)
        self.label_mod_value.setObjectName("label_mod_value")
        self.gridLayout_4.addWidget(self.label_mod_value, 18, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 19, 0, 1, 1)
        self.lineEdit_diffLimit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_diffLimit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_diffLimit.setObjectName("lineEdit_diffLimit")
        self.gridLayout_4.addWidget(self.lineEdit_diffLimit, 19, 2, 1, 1)
        self.label_sharpnessArgMax = QtWidgets.QLabel(self.groupBox)
        self.label_sharpnessArgMax.setObjectName("label_sharpnessArgMax")
        self.gridLayout_4.addWidget(self.label_sharpnessArgMax, 20, 0, 1, 3)
        self.label_sharpnessFitMax = QtWidgets.QLabel(self.groupBox)
        self.label_sharpnessFitMax.setObjectName("label_sharpnessFitMax")
        self.gridLayout_4.addWidget(self.label_sharpnessFitMax, 21, 0, 1, 3)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 13, 0, 1, 1)
        self.lineEdit_waitTime = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_waitTime.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_waitTime.setObjectName("lineEdit_waitTime")
        self.gridLayout_4.addWidget(self.lineEdit_waitTime, 13, 2, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBoxPhase = QtWidgets.QGroupBox(Form)
        self.groupBoxPhase.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBoxPhase.sizePolicy().hasHeightForWidth())
        self.groupBoxPhase.setSizePolicy(sizePolicy)
        self.groupBoxPhase.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBoxPhase.setObjectName("groupBoxPhase")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBoxPhase)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 0, 0, 1, 1)
        self.doubleSpinBoxPixel = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxPixel.setDecimals(3)
        self.doubleSpinBoxPixel.setMaximum(9.0)
        self.doubleSpinBoxPixel.setSingleStep(0.01)
        self.doubleSpinBoxPixel.setProperty("value", 0.163)
        self.doubleSpinBoxPixel.setObjectName("doubleSpinBoxPixel")
        self.gridLayout_3.addWidget(self.doubleSpinBoxPixel, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 1, 0, 1, 1)
        self.doubleSpinBoxWavelength = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxWavelength.setDecimals(3)
        self.doubleSpinBoxWavelength.setProperty("value", 0.525)
        self.doubleSpinBoxWavelength.setObjectName("doubleSpinBoxWavelength")
        self.gridLayout_3.addWidget(self.doubleSpinBoxWavelength, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 2, 0, 1, 1)
        self.doubleSpinBoxIndex = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxIndex.setSingleStep(0.01)
        self.doubleSpinBoxIndex.setProperty("value", 1.33)
        self.doubleSpinBoxIndex.setObjectName("doubleSpinBoxIndex")
        self.gridLayout_3.addWidget(self.doubleSpinBoxIndex, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.doubleSpinBoxNA = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxNA.setSingleStep(0.01)
        self.doubleSpinBoxNA.setProperty("value", 0.8)
        self.doubleSpinBoxNA.setObjectName("doubleSpinBoxNA")
        self.gridLayout_3.addWidget(self.doubleSpinBoxNA, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.doubleSpinBoxFocal = QtWidgets.QDoubleSpinBox(self.groupBoxPhase)
        self.doubleSpinBoxFocal.setMaximum(9999.99)
        self.doubleSpinBoxFocal.setProperty("value", 5000.0)
        self.doubleSpinBoxFocal.setObjectName("doubleSpinBoxFocal")
        self.gridLayout_3.addWidget(self.doubleSpinBoxFocal, 4, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBoxPhase)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButtonPlane = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonPlane.setChecked(True)
        self.radioButtonPlane.setObjectName("radioButtonPlane")
        self.gridLayout_2.addWidget(self.radioButtonPlane, 0, 0, 1, 1)
        self.radioButtonMirror = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonMirror.setObjectName("radioButtonMirror")
        self.gridLayout_2.addWidget(self.radioButtonMirror, 1, 0, 1, 1)
        self.doubleSpinBoxMirrorDistance = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.doubleSpinBoxMirrorDistance.setSingleStep(0.01)
        self.doubleSpinBoxMirrorDistance.setProperty("value", 2.0)
        self.doubleSpinBoxMirrorDistance.setObjectName("doubleSpinBoxMirrorDistance")
        self.gridLayout_2.addWidget(self.doubleSpinBoxMirrorDistance, 1, 1, 1, 1)
        self.radioButtonFromFile = QtWidgets.QRadioButton(self.groupBox_4)
        self.radioButtonFromFile.setObjectName("radioButtonFromFile")
        self.gridLayout_2.addWidget(self.radioButtonFromFile, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_4, 7, 0, 1, 3)
        self.label_10 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 8, 0, 1, 1)
        self.spinBoxIterations = QtWidgets.QSpinBox(self.groupBoxPhase)
        self.spinBoxIterations.setMinimum(1)
        self.spinBoxIterations.setMaximum(999)
        self.spinBoxIterations.setProperty("value", 20)
        self.spinBoxIterations.setObjectName("spinBoxIterations")
        self.gridLayout_3.addWidget(self.spinBoxIterations, 8, 1, 1, 1)
        self.pushButtonPhase = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButtonPhase.setObjectName("pushButtonPhase")
        self.gridLayout_3.addWidget(self.pushButtonPhase, 10, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 16, 0, 1, 1)
        self.checkBoxNeglectDefocus = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBoxNeglectDefocus.setChecked(True)
        self.checkBoxNeglectDefocus.setObjectName("checkBoxNeglectDefocus")
        self.gridLayout_3.addWidget(self.checkBoxNeglectDefocus, 6, 0, 1, 2)
        self.checkBox_invertPF = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_invertPF.setObjectName("checkBox_invertPF")
        self.gridLayout_3.addWidget(self.checkBox_invertPF, 11, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 5, 0, 1, 1)
        self.spinBox_numWavelengths = QtWidgets.QSpinBox(self.groupBoxPhase)
        self.spinBox_numWavelengths.setMinimum(1)
        self.spinBox_numWavelengths.setProperty("value", 1)
        self.spinBox_numWavelengths.setObjectName("spinBox_numWavelengths")
        self.gridLayout_3.addWidget(self.spinBox_numWavelengths, 5, 1, 1, 1)
        self.checkBox_resetAmp = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_resetAmp.setObjectName("checkBox_resetAmp")
        self.gridLayout_3.addWidget(self.checkBox_resetAmp, 12, 0, 1, 1)
        self.pushButton_unwrap = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButton_unwrap.setObjectName("pushButton_unwrap")
        self.gridLayout_3.addWidget(self.pushButton_unwrap, 10, 1, 1, 1)
        self.pushButton_modUnwrapped = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButton_modUnwrapped.setObjectName("pushButton_modUnwrapped")
        self.gridLayout_3.addWidget(self.pushButton_modUnwrapped, 11, 1, 1, 1)
        self.pushButton_zernFitUnwrapped = QtWidgets.QPushButton(self.groupBoxPhase)
        self.pushButton_zernFitUnwrapped.setObjectName("pushButton_zernFitUnwrapped")
        self.gridLayout_3.addWidget(self.pushButton_zernFitUnwrapped, 12, 1, 1, 1)
        self.checkBox_ignore4 = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_ignore4.setObjectName("checkBox_ignore4")
        self.gridLayout_3.addWidget(self.checkBox_ignore4, 16, 1, 1, 1)
        self.spinBox_zernModesToFit = QtWidgets.QSpinBox(self.groupBoxPhase)
        self.spinBox_zernModesToFit.setObjectName("spinBox_zernModesToFit")
        self.gridLayout_3.addWidget(self.spinBox_zernModesToFit, 13, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBoxPhase)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 13, 0, 1, 1)
        self.checkBox_symmeterize = QtWidgets.QCheckBox(self.groupBoxPhase)
        self.checkBox_symmeterize.setObjectName("checkBox_symmeterize")
        self.gridLayout_3.addWidget(self.checkBox_symmeterize, 9, 0, 1, 1)
        self.horizontalLayout.addWidget(self.groupBoxPhase)
        self.tabWidgetPF = QtWidgets.QTabWidget(Form)
        self.tabWidgetPF.setEnabled(False)
        self.tabWidgetPF.setIconSize(QtCore.QSize(15, 16))
        self.tabWidgetPF.setObjectName("tabWidgetPF")
        self.tabWidgetPFPage1 = QtWidgets.QWidget()
        self.tabWidgetPFPage1.setObjectName("tabWidgetPFPage1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tabWidgetPFPage1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mplwidgetPhase = MatplotlibWidget(self.tabWidgetPFPage1)
        self.mplwidgetPhase.setObjectName("mplwidgetPhase")
        self.verticalLayout.addWidget(self.mplwidgetPhase)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButtonSave = QtWidgets.QPushButton(self.tabWidgetPFPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSave.sizePolicy().hasHeightForWidth())
        self.pushButtonSave.setSizePolicy(sizePolicy)
        self.pushButtonSave.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.gridLayout.addWidget(self.pushButtonSave, 1, 1, 1, 1)
        self.pushButtonModulate = QtWidgets.QPushButton(self.tabWidgetPFPage1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonModulate.sizePolicy().hasHeightForWidth())
        self.pushButtonModulate.setSizePolicy(sizePolicy)
        self.pushButtonModulate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonModulate.setObjectName("pushButtonModulate")
        self.gridLayout.addWidget(self.pushButtonModulate, 1, 3, 1, 1)
        self.pushButtonFit = QtWidgets.QPushButton(self.tabWidgetPFPage1)
        self.pushButtonFit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButtonFit.setObjectName("pushButtonFit")
        self.gridLayout.addWidget(self.pushButtonFit, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.tabWidgetPF.addTab(self.tabWidgetPFPage1, "")
        self.Sharpness = QtWidgets.QWidget()
        self.Sharpness.setObjectName("Sharpness")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.Sharpness)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.mplwidgetSharpness = MatplotlibWidget(self.Sharpness)
        self.mplwidgetSharpness.setObjectName("mplwidgetSharpness")
        self.verticalLayout_3.addWidget(self.mplwidgetSharpness)
        self.tabWidgetPF.addTab(self.Sharpness, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.mplwidgetSharpness2 = MatplotlibWidget(self.tab)
        self.mplwidgetSharpness2.setObjectName("mplwidgetSharpness2")
        self.verticalLayout_2.addWidget(self.mplwidgetSharpness2)
        self.tabWidgetPF.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.mplwidgetPhase_2 = MatplotlibWidget(self.tab_2)
        self.mplwidgetPhase_2.setGeometry(QtCore.QRect(10, 0, 380, 349))
        self.mplwidgetPhase_2.setObjectName("mplwidgetPhase_2")
        self.pushButton_modulateZernike = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_modulateZernike.setGeometry(QtCore.QRect(20, 360, 75, 23))
        self.pushButton_modulateZernike.setObjectName("pushButton_modulateZernike")
        self.checkBox_useMask = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_useMask.setGeometry(QtCore.QRect(110, 360, 70, 17))
        self.checkBox_useMask.setObjectName("checkBox_useMask")
        self.lineEdit_zernRadius = QtWidgets.QLineEdit(self.tab_2)
        self.lineEdit_zernRadius.setGeometry(QtCore.QRect(20, 390, 113, 20))
        self.lineEdit_zernRadius.setObjectName("lineEdit_zernRadius")
        self.pushButton_setZernRadius = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_setZernRadius.setGeometry(QtCore.QRect(140, 390, 131, 23))
        self.pushButton_setZernRadius.setObjectName("pushButton_setZernRadius")
        self.tabWidgetPF.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidgetPF.addTab(self.tab_3, "")
        self.horizontalLayout.addWidget(self.tabWidgetPF)
        self.groupBoxModulations = QtWidgets.QGroupBox(Form)
        self.groupBoxModulations.setCheckable(True)
        self.groupBoxModulations.setObjectName("groupBoxModulations")
        self.verticalLayoutModulations = QtWidgets.QVBoxLayout(self.groupBoxModulations)
        self.verticalLayoutModulations.setObjectName("verticalLayoutModulations")
        spacerItem1 = QtWidgets.QSpacerItem(20, 317, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutModulations.addItem(spacerItem1)
        self.pushButton_setMods = QtWidgets.QPushButton(self.groupBoxModulations)
        self.pushButton_setMods.setObjectName("pushButton_setMods")
        self.verticalLayoutModulations.addWidget(self.pushButton_setMods)
        self.horizontalLayout.addWidget(self.groupBoxModulations)

        self.retranslateUi(Form)
        self.tabWidgetPF.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Adaptive Optics"))
        self.groupBox.setTitle(_translate("Form", "PSF"))
        self.label_2.setText(_translate("Form", "Range [um]:"))
        self.label_3.setText(_translate("Form", "# Slices:"))
        self.label_4.setText(_translate("Form", "# Frames/slice:"))
        self.pushButtonPSF.setText(_translate("Form", "Acquire PSF"))
        self.checkBoxSave.setText(_translate("Form", "Save"))
        self.checkBoxCenterLateral.setText(_translate("Form", "Center PSF laterally"))
        self.label.setText(_translate("Form", "Mask radius:"))
        self.label_11.setText(_translate("Form", "Center X:"))
        self.label_12.setText(_translate("Form", "Center Y:"))
        self.lineEdit_cX.setText(_translate("Form", "-1"))
        self.lineEdit_cY.setText(_translate("Form", "-1"))
        self.pushButton_runningSharpness.setText(_translate("Form", "Continuous Sharpness"))
        self.pushButton_stopSharpness.setText(_translate("Form", "Stop Sharpness"))
        self.pushButton_sharpnessVsZern.setText(_translate("Form", "Sharpness vs. Zernike"))
        self.label_mod_index.setText(_translate("Form", "Index: --"))
        self.label_mod_value.setText(_translate("Form", "Value: --"))
        self.label_15.setText(_translate("Form", "Diffraction limit:"))
        self.label_sharpnessArgMax.setText(_translate("Form", "Arg. max: --"))
        self.label_sharpnessFitMax.setText(_translate("Form", "Fit max: --"))
        self.label_16.setText(_translate("Form", "Wait time (s):"))
        self.groupBoxPhase.setTitle(_translate("Form", "Phase retrieval"))
        self.label_5.setText(_translate("Form", "Pixel size [um]:"))
        self.label_6.setText(_translate("Form", "Wavelength [um]:"))
        self.label_7.setText(_translate("Form", "Refractive index:"))
        self.label_8.setText(_translate("Form", "NA:"))
        self.label_9.setText(_translate("Form", "Focal length:"))
        self.groupBox_4.setTitle(_translate("Form", "Initial guess"))
        self.radioButtonPlane.setText(_translate("Form", "Plane wave"))
        self.radioButtonMirror.setText(_translate("Form", "Mirror"))
        self.radioButtonFromFile.setText(_translate("Form", "From file"))
        self.label_10.setText(_translate("Form", "# Iterations:"))
        self.pushButtonPhase.setText(_translate("Form", "Retrieve phase"))
        self.checkBoxNeglectDefocus.setText(_translate("Form", "Neglect defocus"))
        self.checkBox_invertPF.setText(_translate("Form", "Invert?"))
        self.label_13.setText(_translate("Form", "# Wavelengths:"))
        self.checkBox_resetAmp.setText(_translate("Form", "Reset amplitude?"))
        self.pushButton_unwrap.setText(_translate("Form", "Unwrap"))
        self.pushButton_modUnwrapped.setText(_translate("Form", "Mod. Unwrpd"))
        self.pushButton_zernFitUnwrapped.setText(_translate("Form", "Fit Unwrpd"))
        self.checkBox_ignore4.setText(_translate("Form", "Ignore 1st 4?"))
        self.label_14.setText(_translate("Form", "Num modes to fit to:"))
        self.checkBox_symmeterize.setText(_translate("Form", "Make symmetric?"))
        self.pushButtonSave.setText(_translate("Form", "Save to file"))
        self.pushButtonModulate.setText(_translate("Form", "Modulate"))
        self.pushButtonFit.setText(_translate("Form", "Fit to Zernike"))
        self.tabWidgetPF.setTabText(self.tabWidgetPF.indexOf(self.tabWidgetPFPage1), _translate("Form", "Pupil Function"))
        self.tabWidgetPF.setTabText(self.tabWidgetPF.indexOf(self.Sharpness), _translate("Form", "Sharpness"))
        self.tabWidgetPF.setTabText(self.tabWidgetPF.indexOf(self.tab), _translate("Form", "Running Sharpness"))
        self.pushButton_modulateZernike.setText(_translate("Form", "Modulate"))
        self.checkBox_useMask.setText(_translate("Form", "Use mask?"))
        self.lineEdit_zernRadius.setText(_translate("Form", "256"))
        self.pushButton_setZernRadius.setText(_translate("Form", "Set Zernike Radius"))
        self.tabWidgetPF.setTabText(self.tabWidgetPF.indexOf(self.tab_2), _translate("Form", "Zernike Fit to Unwrapped"))
        self.tabWidgetPF.setTabText(self.tabWidgetPF.indexOf(self.tab_3), _translate("Form", "Gen Zernikes"))
        self.groupBoxModulations.setTitle(_translate("Form", "Modulations"))
        self.pushButton_setMods.setText(_translate("Form", "Set"))


from matplotlibwidgets import MatplotlibWidget
