# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'thMotor_dll_design.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(490, 286)
        self.gridLayoutWidget = QtGui.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 79, 301, 141))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_position = QtGui.QLabel(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_position.sizePolicy().hasHeightForWidth())
        self.label_position.setSizePolicy(sizePolicy)
        self.label_position.setObjectName(_fromUtf8("label_position"))
        self.gridLayout.addWidget(self.label_position, 0, 1, 1, 1)
        self.lineEdit_stepsize = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_stepsize.setObjectName(_fromUtf8("lineEdit_stepsize"))
        self.gridLayout.addWidget(self.lineEdit_stepsize, 1, 2, 1, 1)
        self.lineEdit_absolute = QtGui.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_absolute.setObjectName(_fromUtf8("lineEdit_absolute"))
        self.gridLayout.addWidget(self.lineEdit_absolute, 1, 1, 1, 1)
        self.label_stepsize = QtGui.QLabel(self.gridLayoutWidget)
        self.label_stepsize.setObjectName(_fromUtf8("label_stepsize"))
        self.gridLayout.addWidget(self.label_stepsize, 0, 2, 1, 1)
        self.pushButton_stepsize = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_stepsize.sizePolicy().hasHeightForWidth())
        self.pushButton_stepsize.setSizePolicy(sizePolicy)
        self.pushButton_stepsize.setObjectName(_fromUtf8("pushButton_stepsize"))
        self.gridLayout.addWidget(self.pushButton_stepsize, 2, 2, 1, 1)
        self.pushButton_absolute = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_absolute.sizePolicy().hasHeightForWidth())
        self.pushButton_absolute.setSizePolicy(sizePolicy)
        self.pushButton_absolute.setObjectName(_fromUtf8("pushButton_absolute"))
        self.gridLayout.addWidget(self.pushButton_absolute, 2, 1, 1, 1)
        self.lineEdit_relative = QtGui.QLineEdit(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_relative.sizePolicy().hasHeightForWidth())
        self.lineEdit_relative.setSizePolicy(sizePolicy)
        self.lineEdit_relative.setObjectName(_fromUtf8("lineEdit_relative"))
        self.gridLayout.addWidget(self.lineEdit_relative, 1, 3, 1, 1)
        self.label_relative = QtGui.QLabel(self.gridLayoutWidget)
        self.label_relative.setObjectName(_fromUtf8("label_relative"))
        self.gridLayout.addWidget(self.label_relative, 0, 3, 1, 1)
        self.pushButton_relative = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_relative.sizePolicy().hasHeightForWidth())
        self.pushButton_relative.setSizePolicy(sizePolicy)
        self.pushButton_relative.setObjectName(_fromUtf8("pushButton_relative"))
        self.gridLayout.addWidget(self.pushButton_relative, 2, 3, 1, 1)
        self.verticalLayoutWidget = QtGui.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(360, 80, 101, 201))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pushButton_up = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_up.sizePolicy().hasHeightForWidth())
        self.pushButton_up.setSizePolicy(sizePolicy)
        self.pushButton_up.setObjectName(_fromUtf8("pushButton_up"))
        self.verticalLayout.addWidget(self.pushButton_up)
        self.pushButton_home = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_home.sizePolicy().hasHeightForWidth())
        self.pushButton_home.setSizePolicy(sizePolicy)
        self.pushButton_home.setObjectName(_fromUtf8("pushButton_home"))
        self.verticalLayout.addWidget(self.pushButton_home)
        self.pushButton_down = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_down.sizePolicy().hasHeightForWidth())
        self.pushButton_down.setSizePolicy(sizePolicy)
        self.pushButton_down.setObjectName(_fromUtf8("pushButton_down"))
        self.verticalLayout.addWidget(self.pushButton_down)
        self.horizontalLayoutWidget = QtGui.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(60, 220, 301, 61))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_BL = QtGui.QLabel(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_BL.sizePolicy().hasHeightForWidth())
        self.label_BL.setSizePolicy(sizePolicy)
        self.label_BL.setObjectName(_fromUtf8("label_BL"))
        self.verticalLayout_3.addWidget(self.label_BL)
        self.lineEdit_dest = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_dest.setObjectName(_fromUtf8("lineEdit_dest"))
        self.verticalLayout_3.addWidget(self.lineEdit_dest)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.pushButton_BL = QtGui.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_BL.sizePolicy().hasHeightForWidth())
        self.pushButton_BL.setSizePolicy(sizePolicy)
        self.pushButton_BL.setObjectName(_fromUtf8("pushButton_BL"))
        self.horizontalLayout.addWidget(self.pushButton_BL)
        self.horizontalLayoutWidget_2 = QtGui.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(60, 29, 401, 51))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_currentPosition = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_currentPosition.setFont(font)
        self.label_currentPosition.setObjectName(_fromUtf8("label_currentPosition"))
        self.horizontalLayout_2.addWidget(self.label_currentPosition)
        self.lcd_current = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcd_current.setFont(font)
        self.lcd_current.setSmallDecimalPoint(True)
        self.lcd_current.setProperty("value", 0.0)
        self.lcd_current.setProperty("intValue", 0)
        self.lcd_current.setObjectName(_fromUtf8("lcd_current"))
        self.horizontalLayout_2.addWidget(self.lcd_current)
        self.label_currentStep = QtGui.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_currentStep.setFont(font)
        self.label_currentStep.setObjectName(_fromUtf8("label_currentStep"))
        self.horizontalLayout_2.addWidget(self.label_currentStep)
        self.lcd_step = QtGui.QLCDNumber(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lcd_step.setFont(font)
        self.lcd_step.setSmallDecimalPoint(True)
        self.lcd_step.setProperty("value", 0.0)
        self.lcd_step.setProperty("intValue", 0)
        self.lcd_step.setObjectName(_fromUtf8("lcd_step"))
        self.horizontalLayout_2.addWidget(self.lcd_step)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Dialog", None))
        self.label_position.setText(_translate("Form", "Absolute", None))
        self.label_stepsize.setText(_translate("Form", "Stepsize", None))
        self.pushButton_stepsize.setText(_translate("Form", "Stepsize", None))
        self.pushButton_absolute.setText(_translate("Form", "Position", None))
        self.label_relative.setText(_translate("Form", "Relative", None))
        self.pushButton_relative.setText(_translate("Form", "Relative", None))
        self.pushButton_up.setText(_translate("Form", "up", None))
        self.pushButton_home.setText(_translate("Form", "Home", None))
        self.pushButton_down.setText(_translate("Form", "down", None))
        self.label_BL.setText(_translate("Form", "Destination", None))
        self.pushButton_BL.setText(_translate("Form", "BL_correct", None))
        self.label_currentPosition.setText(_translate("Form", "Position", None))
        self.label_currentStep.setText(_translate("Form", "Stepsize", None))

