# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DAQ_design.ui'
#
# Created: Mon Mar 24 16:42:30 2014
#      by: PyQt4 UI code generator 4.8.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(570, 740)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "DAQ", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout = QtGui.QVBoxLayout(Form)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.control_groupbox = QtGui.QGroupBox(Form)
        self.control_groupbox.setAcceptDrops(True)
        self.control_groupbox.setTitle(QtGui.QApplication.translate("Form", "NI DAQ Board Control", None, QtGui.QApplication.UnicodeUTF8))
        self.control_groupbox.setObjectName(_fromUtf8("control_groupbox"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.control_groupbox)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.control_groupbox)
        self.groupBox.setMinimumSize(QtCore.QSize(20, 0))
        self.groupBox.setAcceptDrops(True)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Triggered Digital Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_frames = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_frames.sizePolicy().hasHeightForWidth())
        self.lineEdit_frames.setSizePolicy(sizePolicy)
        self.lineEdit_frames.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEdit_frames.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_frames.setObjectName(_fromUtf8("lineEdit_frames"))
        self.gridLayout_2.addWidget(self.lineEdit_frames, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setText(QtGui.QApplication.translate("Form", "Frames:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setText(QtGui.QApplication.translate("Form", "# of channels:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_numChannels = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_numChannels.sizePolicy().hasHeightForWidth())
        self.lineEdit_numChannels.setSizePolicy(sizePolicy)
        self.lineEdit_numChannels.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEdit_numChannels.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_numChannels.setObjectName(_fromUtf8("lineEdit_numChannels"))
        self.gridLayout_2.addWidget(self.lineEdit_numChannels, 0, 1, 1, 1)
        self.setup_pushButton = QtGui.QPushButton(self.groupBox)
        self.setup_pushButton.setText(QtGui.QApplication.translate("Form", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.setup_pushButton.setObjectName(_fromUtf8("setup_pushButton"))
        self.gridLayout_2.addWidget(self.setup_pushButton, 8, 0, 1, 1)
        self.start_pushButton = QtGui.QPushButton(self.groupBox)
        self.start_pushButton.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.start_pushButton.setObjectName(_fromUtf8("start_pushButton"))
        self.gridLayout_2.addWidget(self.start_pushButton, 8, 1, 1, 1)
        self.stop_pushButton = QtGui.QPushButton(self.groupBox)
        self.stop_pushButton.setText(QtGui.QApplication.translate("Form", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.stop_pushButton.setObjectName(_fromUtf8("stop_pushButton"))
        self.gridLayout_2.addWidget(self.stop_pushButton, 8, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 8, 4, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setAcceptDrops(True)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Channel Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setText(QtGui.QApplication.translate("Form", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setText(QtGui.QApplication.translate("Form", "On", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_ch0 = QtGui.QLabel(self.groupBox_2)
        self.label_ch0.setText(QtGui.QApplication.translate("Form", "0 (642)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch0.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch0.setObjectName(_fromUtf8("label_ch0"))
        self.gridLayout_3.addWidget(self.label_ch0, 1, 0, 1, 1)
        self.label_ch1 = QtGui.QLabel(self.groupBox_2)
        self.label_ch1.setText(QtGui.QApplication.translate("Form", "1 (488)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ch1.setObjectName(_fromUtf8("label_ch1"))
        self.gridLayout_3.addWidget(self.label_ch1, 2, 0, 1, 1)
        self.lineEdit_power0 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_power0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_power0.setObjectName(_fromUtf8("lineEdit_power0"))
        self.gridLayout_3.addWidget(self.lineEdit_power0, 1, 1, 1, 1)
        self.lineEdit_on0 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_on0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_on0.setObjectName(_fromUtf8("lineEdit_on0"))
        self.gridLayout_3.addWidget(self.lineEdit_on0, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Off", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 3, 1, 1)
        self.lineEdit_off0 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_off0.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_off0.setObjectName(_fromUtf8("lineEdit_off0"))
        self.gridLayout_3.addWidget(self.lineEdit_off0, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setText(QtGui.QApplication.translate("Form", "2 (401)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setText(QtGui.QApplication.translate("Form", "3 (561)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 4, 0, 1, 1)
        self.lineEdit_power1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_power1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_power1.setObjectName(_fromUtf8("lineEdit_power1"))
        self.gridLayout_3.addWidget(self.lineEdit_power1, 2, 1, 1, 1)
        self.lineEdit_on1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_on1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_on1.setObjectName(_fromUtf8("lineEdit_on1"))
        self.gridLayout_3.addWidget(self.lineEdit_on1, 2, 2, 1, 1)
        self.lineEdit_off1 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_off1.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_off1.setObjectName(_fromUtf8("lineEdit_off1"))
        self.gridLayout_3.addWidget(self.lineEdit_off1, 2, 3, 1, 1)
        self.lineEdit_power2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_power2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_power2.setObjectName(_fromUtf8("lineEdit_power2"))
        self.gridLayout_3.addWidget(self.lineEdit_power2, 3, 1, 1, 1)
        self.lineEdit_on2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_on2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_on2.setObjectName(_fromUtf8("lineEdit_on2"))
        self.gridLayout_3.addWidget(self.lineEdit_on2, 3, 2, 1, 1)
        self.lineEdit_off2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_off2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_off2.setObjectName(_fromUtf8("lineEdit_off2"))
        self.gridLayout_3.addWidget(self.lineEdit_off2, 3, 3, 1, 1)
        self.lineEdit_power3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_power3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_power3.setObjectName(_fromUtf8("lineEdit_power3"))
        self.gridLayout_3.addWidget(self.lineEdit_power3, 4, 1, 1, 1)
        self.lineEdit_on3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_on3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_on3.setObjectName(_fromUtf8("lineEdit_on3"))
        self.gridLayout_3.addWidget(self.lineEdit_on3, 4, 2, 1, 1)
        self.lineEdit_off3 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_off3.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_off3.setObjectName(_fromUtf8("lineEdit_off3"))
        self.gridLayout_3.addWidget(self.lineEdit_off3, 4, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setText(QtGui.QApplication.translate("Form", "4 (LED)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 1)
        self.lineEdit_power4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_power4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_power4.setObjectName(_fromUtf8("lineEdit_power4"))
        self.gridLayout_3.addWidget(self.lineEdit_power4, 5, 1, 1, 1)
        self.lineEdit_on4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_on4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_on4.setObjectName(_fromUtf8("lineEdit_on4"))
        self.gridLayout_3.addWidget(self.lineEdit_on4, 5, 2, 1, 1)
        self.lineEdit_off4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_off4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_off4.setObjectName(_fromUtf8("lineEdit_off4"))
        self.gridLayout_3.addWidget(self.lineEdit_off4, 5, 3, 1, 1)
        self.lineEdit_power5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_power5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_power5.setObjectName(_fromUtf8("lineEdit_power5"))
        self.gridLayout_3.addWidget(self.lineEdit_power5, 6, 1, 1, 1)
        self.lineEdit_on5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_on5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_on5.setObjectName(_fromUtf8("lineEdit_on5"))
        self.gridLayout_3.addWidget(self.lineEdit_on5, 6, 2, 1, 1)
        self.lineEdit_off5 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_off5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lineEdit_off5.setObjectName(_fromUtf8("lineEdit_off5"))
        self.gridLayout_3.addWidget(self.lineEdit_off5, 6, 3, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_4.setText(QtGui.QApplication.translate("Form", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 7, 0, 1, 6)
        self.lineEdit_oversampling = QtGui.QLineEdit(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_oversampling.sizePolicy().hasHeightForWidth())
        self.lineEdit_oversampling.setSizePolicy(sizePolicy)
        self.lineEdit_oversampling.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_oversampling.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_oversampling.setObjectName(_fromUtf8("lineEdit_oversampling"))
        self.gridLayout_2.addWidget(self.lineEdit_oversampling, 0, 3, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setText(QtGui.QApplication.translate("Form", "Frame time:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 1, 2, 1, 1)
        self.lineEdit_frameTime = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_frameTime.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_frameTime.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_frameTime.setObjectName(_fromUtf8("lineEdit_frameTime"))
        self.gridLayout_2.addWidget(self.lineEdit_frameTime, 1, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.pushButton_updateTDO = QtGui.QPushButton(self.groupBox)
        self.pushButton_updateTDO.setText(QtGui.QApplication.translate("Form", "Update Triggered DO Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_updateTDO.setObjectName(_fromUtf8("pushButton_updateTDO"))
        self.gridLayout_2.addWidget(self.pushButton_updateTDO, 1, 4, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setText(QtGui.QApplication.translate("Form", "Oversampling:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_21 = QtGui.QGroupBox(self.control_groupbox)
        self.groupBox_21.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox_21.setTitle(QtGui.QApplication.translate("Form", "Analog Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_21.setObjectName(_fromUtf8("groupBox_21"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_21)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_11 = QtGui.QLabel(self.groupBox_21)
        self.label_11.setText(QtGui.QApplication.translate("Form", "Output 0 (for 561):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_21)
        self.label_12.setText(QtGui.QApplication.translate("Form", "Output 1 (for LED):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_analogout0 = QtGui.QLineEdit(self.groupBox_21)
        self.lineEdit_analogout0.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEdit_analogout0.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_analogout0.setObjectName(_fromUtf8("lineEdit_analogout0"))
        self.gridLayout_4.addWidget(self.lineEdit_analogout0, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 1, 3, 1, 1)
        self.lineEdit_analogout1 = QtGui.QLineEdit(self.groupBox_21)
        self.lineEdit_analogout1.setMinimumSize(QtCore.QSize(20, 0))
        self.lineEdit_analogout1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.lineEdit_analogout1.setObjectName(_fromUtf8("lineEdit_analogout1"))
        self.gridLayout_4.addWidget(self.lineEdit_analogout1, 2, 1, 1, 1)
        self.pushButton_analog0 = QtGui.QPushButton(self.groupBox_21)
        self.pushButton_analog0.setText(QtGui.QApplication.translate("Form", "Turn ON", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_analog0.setObjectName(_fromUtf8("pushButton_analog0"))
        self.gridLayout_4.addWidget(self.pushButton_analog0, 1, 2, 1, 1)
        self.pushButton_analog1 = QtGui.QPushButton(self.groupBox_21)
        self.pushButton_analog1.setText(QtGui.QApplication.translate("Form", "Turn ON", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_analog1.setObjectName(_fromUtf8("pushButton_analog1"))
        self.gridLayout_4.addWidget(self.pushButton_analog1, 2, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_21)
        self.groupBox_3 = QtGui.QGroupBox(self.control_groupbox)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Form", "Non-triggered Digital Outputs", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.checkBox_ch0 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch0.setObjectName(_fromUtf8("checkBox_ch0"))
        self.horizontalLayout.addWidget(self.checkBox_ch0)
        self.checkBox_ch1 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch1.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch1.setObjectName(_fromUtf8("checkBox_ch1"))
        self.horizontalLayout.addWidget(self.checkBox_ch1)
        self.checkBox_ch2 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch2.setText(QtGui.QApplication.translate("Form", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch2.setObjectName(_fromUtf8("checkBox_ch2"))
        self.horizontalLayout.addWidget(self.checkBox_ch2)
        self.checkBox_ch3 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch3.setText(QtGui.QApplication.translate("Form", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch3.setObjectName(_fromUtf8("checkBox_ch3"))
        self.horizontalLayout.addWidget(self.checkBox_ch3)
        self.checkBox_ch4 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch4.setText(QtGui.QApplication.translate("Form", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch4.setObjectName(_fromUtf8("checkBox_ch4"))
        self.horizontalLayout.addWidget(self.checkBox_ch4)
        self.checkBox_ch5 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch5.setText(QtGui.QApplication.translate("Form", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch5.setObjectName(_fromUtf8("checkBox_ch5"))
        self.horizontalLayout.addWidget(self.checkBox_ch5)
        self.checkBox_ch6 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch6.setText(QtGui.QApplication.translate("Form", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch6.setObjectName(_fromUtf8("checkBox_ch6"))
        self.horizontalLayout.addWidget(self.checkBox_ch6)
        self.checkBox_ch7 = QtGui.QCheckBox(self.groupBox_3)
        self.checkBox_ch7.setText(QtGui.QApplication.translate("Form", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_ch7.setObjectName(_fromUtf8("checkBox_ch7"))
        self.horizontalLayout.addWidget(self.checkBox_ch7)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.control_groupbox)
        self.groupBox_4.setTitle(QtGui.QApplication.translate("Form", "Analog Waveform Output", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 20, 84, 50))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("Form", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioButton_waveformCh0 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_waveformCh0.setText(QtGui.QApplication.translate("Form", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_waveformCh0.setChecked(False)
        self.radioButton_waveformCh0.setObjectName(_fromUtf8("radioButton_waveformCh0"))
        self.horizontalLayout_2.addWidget(self.radioButton_waveformCh0)
        self.radioButton_waveformCh1 = QtGui.QRadioButton(self.groupBox_5)
        self.radioButton_waveformCh1.setText(QtGui.QApplication.translate("Form", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_waveformCh1.setChecked(True)
        self.radioButton_waveformCh1.setObjectName(_fromUtf8("radioButton_waveformCh1"))
        self.horizontalLayout_2.addWidget(self.radioButton_waveformCh1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(110, 20, 111, 16))
        self.label_15.setText(QtGui.QApplication.translate("Form", "Number of samples:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lineEdit_waveformNumSamples = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_waveformNumSamples.setGeometry(QtCore.QRect(210, 20, 81, 20))
        self.lineEdit_waveformNumSamples.setObjectName(_fromUtf8("lineEdit_waveformNumSamples"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(150, 50, 61, 16))
        self.label_16.setText(QtGui.QApplication.translate("Form", "Frequency: ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_waveformFrequency = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_waveformFrequency.setGeometry(QtCore.QRect(210, 50, 81, 20))
        self.lineEdit_waveformFrequency.setObjectName(_fromUtf8("lineEdit_waveformFrequency"))
        self.comboBox_waveformClock = QtGui.QComboBox(self.groupBox_4)
        self.comboBox_waveformClock.setGeometry(QtCore.QRect(360, 20, 111, 22))
        self.comboBox_waveformClock.setObjectName(_fromUtf8("comboBox_waveformClock"))
        self.comboBox_waveformClock.addItem(_fromUtf8(""))
        self.comboBox_waveformClock.setItemText(0, QtGui.QApplication.translate("Form", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_waveformClock.addItem(_fromUtf8(""))
        self.comboBox_waveformClock.setItemText(1, QtGui.QApplication.translate("Form", "ctr0out", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_waveformClock.addItem(_fromUtf8(""))
        self.comboBox_waveformClock.setItemText(2, QtGui.QApplication.translate("Form", "ctr0InternalOutput", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_waveformClock.addItem(_fromUtf8(""))
        self.comboBox_waveformClock.setItemText(3, QtGui.QApplication.translate("Form", "ctr1InternalOutput", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17 = QtGui.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(320, 20, 46, 13))
        self.label_17.setText(QtGui.QApplication.translate("Form", "Clock:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.pushButton_waveformSetup = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_waveformSetup.setGeometry(QtCore.QRect(290, 50, 41, 23))
        self.pushButton_waveformSetup.setText(QtGui.QApplication.translate("Form", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_waveformSetup.setObjectName(_fromUtf8("pushButton_waveformSetup"))
        self.pushButton_waveformStart = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_waveformStart.setGeometry(QtCore.QRect(330, 50, 41, 23))
        self.pushButton_waveformStart.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_waveformStart.setObjectName(_fromUtf8("pushButton_waveformStart"))
        self.pushButton_waveformStop = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_waveformStop.setGeometry(QtCore.QRect(370, 50, 41, 23))
        self.pushButton_waveformStop.setText(QtGui.QApplication.translate("Form", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_waveformStop.setObjectName(_fromUtf8("pushButton_waveformStop"))
        self.label_18 = QtGui.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(16, 80, 71, 20))
        self.label_18.setText(QtGui.QApplication.translate("Form", "Min Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.lineEdit_waveformMin = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_waveformMin.setGeometry(QtCore.QRect(80, 80, 41, 20))
        self.lineEdit_waveformMin.setObjectName(_fromUtf8("lineEdit_waveformMin"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 71, 20))
        self.label_19.setText(QtGui.QApplication.translate("Form", "Max Voltage:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.lineEdit_waveformMax = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_waveformMax.setGeometry(QtCore.QRect(80, 110, 41, 20))
        self.lineEdit_waveformMax.setObjectName(_fromUtf8("lineEdit_waveformMax"))
        self.groupBox_6 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_6.setGeometry(QtCore.QRect(140, 80, 381, 61))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("Form", "Counter", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.pushButton_counterStop = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_counterStop.setGeometry(QtCore.QRect(330, 20, 41, 23))
        self.pushButton_counterStop.setText(QtGui.QApplication.translate("Form", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_counterStop.setObjectName(_fromUtf8("pushButton_counterStop"))
        self.pushButton_counterStart = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_counterStart.setGeometry(QtCore.QRect(280, 20, 41, 23))
        self.pushButton_counterStart.setText(QtGui.QApplication.translate("Form", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_counterStart.setObjectName(_fromUtf8("pushButton_counterStart"))
        self.pushButton_counterSet = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_counterSet.setGeometry(QtCore.QRect(230, 20, 41, 23))
        self.pushButton_counterSet.setText(QtGui.QApplication.translate("Form", "Setup", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_counterSet.setObjectName(_fromUtf8("pushButton_counterSet"))
        self.label_20 = QtGui.QLabel(self.groupBox_6)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label_20.setText(QtGui.QApplication.translate("Form", "Freq:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lineEdit_counterFreq = QtGui.QLineEdit(self.groupBox_6)
        self.lineEdit_counterFreq.setGeometry(QtCore.QRect(40, 20, 51, 20))
        self.lineEdit_counterFreq.setObjectName(_fromUtf8("lineEdit_counterFreq"))
        self.radioButton_counterCh0 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_counterCh0.setGeometry(QtCore.QRect(100, 10, 51, 17))
        self.radioButton_counterCh0.setText(QtGui.QApplication.translate("Form", "Ch 0", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_counterCh0.setChecked(False)
        self.radioButton_counterCh0.setObjectName(_fromUtf8("radioButton_counterCh0"))
        self.radioButton_counterCh1 = QtGui.QRadioButton(self.groupBox_6)
        self.radioButton_counterCh1.setGeometry(QtCore.QRect(100, 40, 51, 17))
        self.radioButton_counterCh1.setText(QtGui.QApplication.translate("Form", "Ch 1", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_counterCh1.setChecked(True)
        self.radioButton_counterCh1.setObjectName(_fromUtf8("radioButton_counterCh1"))
        self.checkBox_counter2 = QtGui.QCheckBox(self.groupBox_6)
        self.checkBox_counter2.setGeometry(QtCore.QRect(150, 10, 71, 18))
        self.checkBox_counter2.setText(QtGui.QApplication.translate("Form", "Counter 2?", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_counter2.setChecked(True)
        self.checkBox_counter2.setObjectName(_fromUtf8("checkBox_counter2"))
        self.confocal10_pushButton = QtGui.QPushButton(self.groupBox_4)
        self.confocal10_pushButton.setGeometry(QtCore.QRect(480, 20, 41, 23))
        self.confocal10_pushButton.setText(QtGui.QApplication.translate("Form", "10Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.confocal10_pushButton.setObjectName(_fromUtf8("confocal10_pushButton"))
        self.confocal40_pushButton = QtGui.QPushButton(self.groupBox_4)
        self.confocal40_pushButton.setGeometry(QtCore.QRect(480, 50, 41, 23))
        self.confocal40_pushButton.setText(QtGui.QApplication.translate("Form", "40Hz", None, QtGui.QApplication.UnicodeUTF8))
        self.confocal40_pushButton.setObjectName(_fromUtf8("confocal40_pushButton"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_4)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 140, 155, 50))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("Form", "Waveform", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioButton_triangle = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_triangle.setText(QtGui.QApplication.translate("Form", "Triangle", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_triangle.setChecked(True)
        self.radioButton_triangle.setObjectName(_fromUtf8("radioButton_triangle"))
        self.horizontalLayout_3.addWidget(self.radioButton_triangle)
        self.radioButton_sawtooth = QtGui.QRadioButton(self.groupBox_7)
        self.radioButton_sawtooth.setText(QtGui.QApplication.translate("Form", "Sawtooth", None, QtGui.QApplication.UnicodeUTF8))
        self.radioButton_sawtooth.setObjectName(_fromUtf8("radioButton_sawtooth"))
        self.horizontalLayout_3.addWidget(self.radioButton_sawtooth)
        self.pushButton_waveformClear = QtGui.QPushButton(self.groupBox_4)
        self.pushButton_waveformClear.setGeometry(QtCore.QRect(410, 50, 41, 23))
        self.pushButton_waveformClear.setText(QtGui.QApplication.translate("Form", "Clr", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_waveformClear.setObjectName(_fromUtf8("pushButton_waveformClear"))
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.verticalLayout.addWidget(self.control_groupbox)

        self.retranslateUi(Form)
        self.comboBox_waveformClock.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

