# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\sliscan_design.ui'
#
# Created: Thu Apr 12 10:34:11 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(418, 171)
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "SLI Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.horizontalLayout = QtGui.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.groupBox = QtGui.QGroupBox(Form)
        self.groupBox.setTitle(QtGui.QApplication.translate("Form", "Create scan files", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setText(QtGui.QApplication.translate("Form", "Start [um]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.doubleSpinBoxStart = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxStart.setMinimum(-99.99)
        self.doubleSpinBoxStart.setProperty("value", -2.0)
        self.doubleSpinBoxStart.setObjectName(_fromUtf8("doubleSpinBoxStart"))
        self.gridLayout.addWidget(self.doubleSpinBoxStart, 0, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setText(QtGui.QApplication.translate("Form", "End [um]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.doubleSpinBoxEnd = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBoxEnd.setProperty("value", 2.0)
        self.doubleSpinBoxEnd.setObjectName(_fromUtf8("doubleSpinBoxEnd"))
        self.gridLayout.addWidget(self.doubleSpinBoxEnd, 1, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setText(QtGui.QApplication.translate("Form", "# Steps:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.spinBoxNSteps = QtGui.QSpinBox(self.groupBox)
        self.spinBoxNSteps.setMinimum(2)
        self.spinBoxNSteps.setMaximum(9999)
        self.spinBoxNSteps.setProperty("value", 5)
        self.spinBoxNSteps.setObjectName(_fromUtf8("spinBoxNSteps"))
        self.gridLayout.addWidget(self.spinBoxNSteps, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setText(QtGui.QApplication.translate("Form", "Step size [nm]:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.labelStepSize = QtGui.QLabel(self.groupBox)
        self.labelStepSize.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelStepSize.setObjectName(_fromUtf8("labelStepSize"))
        self.gridLayout.addWidget(self.labelStepSize, 3, 1, 1, 1)
        self.pushButtonCalculateSLI = QtGui.QPushButton(self.groupBox)
        self.pushButtonCalculateSLI.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonCalculateSLI.setText(QtGui.QApplication.translate("Form", "Calculate", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonCalculateSLI.setObjectName(_fromUtf8("pushButtonCalculateSLI"))
        self.gridLayout.addWidget(self.pushButtonCalculateSLI, 4, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(Form)
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Form", "Run scans", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setText(QtGui.QApplication.translate("Form", "Scan file:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.labelFile = QtGui.QLabel(self.groupBox_2)
        self.labelFile.setMinimumSize(QtCore.QSize(120, 0))
        self.labelFile.setMaximumSize(QtCore.QSize(120, 16777215))
        self.labelFile.setAcceptDrops(True)
        self.labelFile.setText(QtGui.QApplication.translate("Form", "-", None, QtGui.QApplication.UnicodeUTF8))
        self.labelFile.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFile.setObjectName(_fromUtf8("labelFile"))
        self.gridLayout_2.addWidget(self.labelFile, 0, 3, 1, 1)
        self.checkBoxSave = QtGui.QCheckBox(self.groupBox_2)
        self.checkBoxSave.setText(QtGui.QApplication.translate("Form", "Save:", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBoxSave.setObjectName(_fromUtf8("checkBoxSave"))
        self.gridLayout_2.addWidget(self.checkBoxSave, 2, 0, 1, 1)
        self.lineEditSave = QtGui.QLineEdit(self.groupBox_2)
        self.lineEditSave.setMinimumSize(QtCore.QSize(120, 0))
        self.lineEditSave.setMaximumSize(QtCore.QSize(120, 16777215))
        self.lineEditSave.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditSave.setObjectName(_fromUtf8("lineEditSave"))
        self.gridLayout_2.addWidget(self.lineEditSave, 2, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setText(QtGui.QApplication.translate("Form", "# Frames/step:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 3, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.spinBoxNFrames = QtGui.QSpinBox(self.groupBox_2)
        self.spinBoxNFrames.setMinimumSize(QtCore.QSize(60, 0))
        self.spinBoxNFrames.setMaximumSize(QtCore.QSize(60, 16777215))
        self.spinBoxNFrames.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.spinBoxNFrames.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBoxNFrames.setMinimum(1)
        self.spinBoxNFrames.setMaximum(100)
        self.spinBoxNFrames.setProperty("value", 1)
        self.spinBoxNFrames.setObjectName(_fromUtf8("spinBoxNFrames"))
        self.horizontalLayout_2.addWidget(self.spinBoxNFrames)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 3, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.pushButtonScan = QtGui.QPushButton(self.groupBox_2)
        self.pushButtonScan.setEnabled(True)
        self.pushButtonScan.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButtonScan.setText(QtGui.QApplication.translate("Form", "Scan", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButtonScan.setObjectName(_fromUtf8("pushButtonScan"))
        self.horizontalLayout_3.addWidget(self.pushButtonScan)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 8, 3, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass

